ALTER TABLE I500_DATILIBERI ADD TIPO VARCHAR2(1);

ALTER TABLE I090_ENTI ADD QUALIF_MINIST VARCHAR2(20);

CREATE TABLE T361_OROLOGI (
  CODICE VARCHAR2(2) NOT NULL,
  DESCRIZIONE VARCHAR2(40),
  FUNZIONE VARCHAR2(1),
  PRIMARY KEY (CODICE) USING INDEX TABLESPACE INDICI
)
  TABLESPACE LAVORO;
