ALTER TABLE T275_CAUPRESENZE ADD SIGLA VARCHAR2(1);
UPDATE T275_CAUPRESENZE SET SIGLA = SUBSTR(CODICE,1,1);

ALTER TABLE T305_CAUGIUSTIF ADD SIGLA VARCHAR2(1);
UPDATE T305_CAUGIUSTIF SET SIGLA = SUBSTR(CODICE,1,1);

ALTER TABLE T950_STAMPACARTELLINO ADD SEPARARIGHE VARCHAR2(1);
ALTER TABLE T950_STAMPACARTELLINO ADD SEPARADATI VARCHAR2(1);
UPDATE T950_STAMPACARTELLINO SET SEPARARIGHE = 'N';
UPDATE T950_STAMPACARTELLINO SET SEPARADATI = 'N';
