ALTER TABLE T950_STAMPACARTELLINO ADD ANOMALIA VARCHAR2(1);
ALTER TABLE T950_STAMPACARTELLINO ADD FESTIVO VARCHAR2(1);
ALTER TABLE T950_STAMPACARTELLINO ADD NONLAV VARCHAR2(1);
ALTER TABLE T950_STAMPACARTELLINO ADD GRASSETTO VARCHAR2(1);
UPDATE T950_STAMPACARTELLINO SET FESTIVO = 'S';
UPDATE T950_STAMPACARTELLINO SET NONLAV = 'N';
UPDATE T950_STAMPACARTELLINO SET GRASSETTO = 'N';
ALTER TABLE T220_PROFILIORARI ADD SCOSTENTRATA VARCHAR2(1);
UPDATE T220_PROFILIORARI SET SCOSTENTRATA = 'N';
UPDATE T220_PROFILIORARI SET PRITIMSC = 'N';

