ALTER TABLE T191_PARPAGHE ADD USERPAGHE VARCHAR2(20);
ALTER TABLE T430_STORICO MODIFY PERSELASTICO VARCHAR2(5); 
UPDATE T020_ORARI SET COMPFASCIA = '1' WHERE COMPFASCIA = 'A';
UPDATE T020_ORARI SET COMPFASCIA = '3' WHERE COMPFASCIA = 'B';
