ALTER TABLE I500_DATILIBERI ADD FORMATO VARCHAR2(1);
UPDATE I500_DATILIBERI SET FORMATO='S';

create table T033NEW_LAYOUT
(
  NOME VARCHAR2(30) not null,
  TOP NUMBER(38,2),
  LFT NUMBER(38,2),
  CAPTION VARCHAR2(50),
  ACCESSO VARCHAR2(1),
  NOMEPAGINA VARCHAR2(20),
  CAMPODB VARCHAR2(20)
)
  tablespace LAVORO
  pctfree 10
  pctused 60
  initrans 1
  maxtrans 255
  storage
  (
    initial 256K
    next 256K
    minextents 1
    pctincrease 0
  );

UPDATE T033_LAYOUT SET CAMPODB = 'D_ProvinciaNas' WHERE NUMCOMP = 7;
INSERT INTO T033NEW_LAYOUT (NOME,TOP,LFT,CAPTION,ACCESSO,NOMEPAGINA,CAMPODB)
  SELECT NOME,TOP,LFT,CAPTION,VISIBLE,PARENT,CAMPODB FROM T033_LAYOUT;

UPDATE T033NEW_LAYOUT SET NOMEPAGINA = 
  DECODE(NOMEPAGINA,
  '1','Dati Anagrafici',
  '2','Parametri orario',
  '3','Presenze/Assenze',
  '4','Dati liberi 1',
  '5','Dati liberi 2');

DROP TABLE T033_LAYOUT;
RENAME T033NEW_LAYOUT TO T033_LAYOUT;

-- Create/Recreate primary, unique and foreign key constraints 
alter table T033_LAYOUT
  add constraint T033_PK primary key (NOME,CAMPODB)
  using index 
  tablespace INDICI
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    pctincrease 0
  );

UPDATE I500_DATILIBERI SET TIPO = '0' WHERE TIPO IN ('2','3');

ALTER TABLE I072_INIBFUNZ ADD APPLICAZIONE VARCHAR2(6);
UPDATE I072_INIBFUNZ SET APPLICAZIONE = 'RILPRE';
CREATE TABLE I072_NEW AS SELECT * FROM I072_INIBFUNZ;
DROP TABLE I072_INIBFUNZ;
RENAME I072_NEW TO I072_INIBFUNZ;
ALTER TABLE I072_INIBFUNZ ADD CONSTRAINT I072_PK PRIMARY KEY (PROGRESSIVO,MENU,APPLICAZIONE)
  USING INDEX TABLESPACE INDICI STORAGE(INITIAL 128K NEXT 128K PCTINCREASE 0);
