ALTER TABLE T161_INDGRUPPO ADD DECORRENZA DATE;
ALTER TABLE T161_INDGRUPPO DROP CONSTRAINT T161_PK CASCADE;
UPDATE T161_INDGRUPPO SET DECORRENZA = TO_DATE('01011900','DDMMYYYY'); 
ALTER TABLE T161_INDGRUPPO
  ADD CONSTRAINT T161_PK PRIMARY KEY (DECORRENZA, CODICE, CODICE2)
  USING INDEX 
  TABLESPACE INDICI
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
  (
    INITIAL 128K
    NEXT 128K
    MINEXTENTS 1
    PCTINCREASE 0
  );