ALTER TABLE I070_OPERATORI DROP CONSTRAINT I070_PK;
ALTER TABLE I071_INIBIZIONI DROP CONSTRAINT I071_PK;
ALTER TABLE I072_INIBFUNZ DROP CONSTRAINT I072_PK;

--Tabella operatori
CREATE TABLE MONDOEDP.I070_UTENTI (
  AZIENDA VARCHAR2(30),  
  UTENTE VARCHAR2(30),
  PROGRESSIVO NUMBER(8),
  PASSWD VARCHAR2(20),
  OCCUPATO VARCHAR2(1) DEFAULT 'N',
  SBLOCCO VARCHAR2(1) DEFAULT 'S',
  INTEGRAZIONEANAGRAFE VARCHAR2(1) DEFAULT 'N',
  PERMESSI VARCHAR2(20),
  FILTRO_ANAGRAFE VARCHAR2(20),
  FILTRO_FUNZIONI VARCHAR2(20),
  FILTRO_DIZIONARIO VARCHAR2(20)
)
STORAGE (PCTINCREASE 0 INITIAL 64K NEXT 64K)
TABLESPACE LAVORO;  

ALTER TABLE MONDOEDP.I070_UTENTI ADD CONSTRAINT I070_PK 
  PRIMARY KEY (AZIENDA,UTENTE) USING INDEX TABLESPACE INDICI STORAGE(PCTINCREASE 0 INITIAL 32K NEXT 32K);

--Profilo dei permessi
CREATE TABLE MONDOEDP.I071_PERMESSI (
  PROFILO VARCHAR2(20),  
  CANCELLA_TIMBRATURE/*FUNZIONE1*/ VARCHAR2(1) DEFAULT 'S',
  ABILITA_SCHEDE_CHIUSE /*FUNZIONE2*/ VARCHAR2(1) DEFAULT 'S',
  T100_ORA VARCHAR2(1) DEFAULT 'S',
  T100_RILEVATORE VARCHAR2(1) DEFAULT 'S',
  T100_CAUSALE VARCHAR2(1) DEFAULT 'S',
  A029_SALDI VARCHAR2(1) DEFAULT 'S',
  A029_INDENNITA VARCHAR2(1) DEFAULT 'S',
  A029_STRAORDINARIO VARCHAR2(1) DEFAULT 'S',
  A029_CAUPRESENZA VARCHAR2(1) DEFAULT 'S',
  LIQUIDAZIONE_FORZATA VARCHAR2(1) DEFAULT 'S',
  INSERIMENTO_MATRICOLE VARCHAR2(1) DEFAULT 'S',
  STORICIZZAZIONE VARCHAR2(1) DEFAULT 'S',
  LAYOUT VARCHAR2(30),
  RIPRISTINO_TIMB_ORI VARCHAR2(1) DEFAULT 'S',
  CANCELLAZIONE_DATI VARCHAR2(1) DEFAULT 'N',
  MONITOR_INTEGRANAGRA VARCHAR2(1) DEFAULT 'N'
)
STORAGE (PCTINCREASE 0 INITIAL 64K NEXT 64K)
TABLESPACE LAVORO;  

ALTER TABLE MONDOEDP.I071_PERMESSI ADD CONSTRAINT I071_PK 
  PRIMARY KEY (PROFILO) USING INDEX TABLESPACE INDICI STORAGE(PCTINCREASE 0 INITIAL 32K NEXT 32K);

--Profilo dei filtri sull'archivio anagrafico  
CREATE TABLE MONDOEDP.I072_FILTROANAGRAFE (
  PROFILO VARCHAR2(20),
  PROGRESSIVO NUMBER(8),
  FILTRO VARCHAR2(255)
)
STORAGE (PCTINCREASE 0 INITIAL 64K NEXT 64K)
TABLESPACE LAVORO;

ALTER TABLE MONDOEDP.I072_FILTROANAGRAFE ADD CONSTRAINT I072_PK 
  PRIMARY KEY (PROFILO,PROGRESSIVO) USING INDEX TABLESPACE INDICI STORAGE(PCTINCREASE 0 INITIAL 32K NEXT 32K);

--Profilo dei filtri sulle funzioni
CREATE TABLE MONDOEDP.I073_FILTROFUNZIONI (
  PROFILO VARCHAR2(20),  
  APPLICAZIONE VARCHAR2(6),
  TAG NUMBER(8), 
  FUNZIONE VARCHAR2(50), 
  GRUPPO VARCHAR2(50),
  DESCRIZIONE VARCHAR2(50),
  INIBIZIONE VARCHAR2(1)
)
STORAGE (PCTINCREASE 0 INITIAL 64K NEXT 64K)
TABLESPACE LAVORO;  

ALTER TABLE MONDOEDP.I073_FILTROFUNZIONI ADD CONSTRAINT I073_PK 
  PRIMARY KEY (PROFILO,APPLICAZIONE,TAG) USING INDEX TABLESPACE INDICI STORAGE(PCTINCREASE 0 INITIAL 32K NEXT 32K);
  
--Profilo dei filtri sul dizionario dati
CREATE TABLE MONDOEDP.I074_FILTRODIZIONARIO (
  PROFILO VARCHAR2(20),  
  TABELLA VARCHAR2(40),
  CODICE VARCHAR2(10)
)
STORAGE (PCTINCREASE 0 INITIAL 64K NEXT 64K)
TABLESPACE LAVORO;  

ALTER TABLE MONDOEDP.I074_FILTRODIZIONARIO ADD CONSTRAINT I074_PK 
  PRIMARY KEY (PROFILO,TABELLA,CODICE) USING INDEX TABLESPACE INDICI STORAGE(PCTINCREASE 0 INITIAL 32K NEXT 32K);

INSERT INTO MONDOEDP.I070_UTENTI 
  (AZIENDA,UTENTE,PROGRESSIVO,PASSWD,OCCUPATO,SBLOCCO,INTEGRAZIONEANAGRAFE,PERMESSI,FILTRO_FUNZIONI)
SELECT AZIENDA,UTENTE,PROGRESSIVO,PASSWD,OCCUPATO,SBLOCCO,INTEGRAZIONEANAGRAFE,UTENTE||PROGRESSIVO,UTENTE||PROGRESSIVO
FROM MONDOEDP.I070_OPERATORI;

INSERT INTO MONDOEDP.I071_PERMESSI
  (PROFILO,CANCELLA_TIMBRATURE,ABILITA_SCHEDE_CHIUSE,
   T100_ORA,T100_RILEVATORE,T100_CAUSALE,LIQUIDAZIONE_FORZATA,RIPRISTINO_TIMB_ORI, 
   CANCELLAZIONE_DATI,MONITOR_INTEGRANAGRA)
SELECT
  UTENTE||PROGRESSIVO,FUNZIONE1,FUNZIONE2,
   T100_ORA,T100_RILEVATORE,T100_CAUSALE,DECODE(UTENTE,'SYSMAN','S','N'),SUPERVISORE,
   DECODE(UTENTE,'SYSMAN','S','N'),DECODE(UTENTE,'SYSMAN','S','N')
FROM MONDOEDP.I070_OPERATORI;

INSERT INTO MONDOEDP.I072_FILTROANAGRAFE 
  (PROFILO,PROGRESSIVO,FILTRO)
SELECT
  I070.UTENTE||I070.PROGRESSIVO,I071.PROGRESSIVO,CAMPO||OPERATORE||''''||VALORE||''''||OPLOGICO
FROM MONDOEDP.I071_INIBIZIONI I071,MONDOEDP.I070_OPERATORI I070
WHERE I071.PROGOPER = I070.PROGRESSIVO;

UPDATE MONDOEDP.I070_UTENTI T SET FILTRO_ANAGRAFE = UTENTE||PROGRESSIVO 
WHERE EXISTS(SELECT 'X' FROM MONDOEDP.I072_FILTROANAGRAFE WHERE PROFILO = T.UTENTE||T.PROGRESSIVO);

INSERT INTO MONDOEDP.I073_FILTROFUNZIONI
  (PROFILO,APPLICAZIONE,TAG,FUNZIONE,DESCRIZIONE,INIBIZIONE)
SELECT
  I070.UTENTE||I070.PROGRESSIVO,I072.APPLICAZIONE,I072.TAG,I072.FUNZIONE,I072.DESCRIZIONE,I072.INIBIZIONE
FROM MONDOEDP.I072_INIBFUNZ I072,MONDOEDP.I070_OPERATORI I070
WHERE I072.PROGRESSIVO = I070.PROGRESSIVO;

ALTER TABLE T020_ORARI ADD STR_DOPO_HHMAX VARCHAR2(1) DEFAULT 'N';