UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '7.8',PATCHDB = 0 WHERE AZIENDA = :AZIENDA;

create index I006_ID on I006_MSGDATI (ID) tablespace INDICI;
create index I006_TIPO_ID on I006_MSGDATI(TIPO,ID) tablespace INDICI;

-- *****************************************************************************
-- IMPOSTAZIONE NUOVO SCAGLIONE PER CPDEL, CPS, ENPAM EX CONVENZIONATI, 
-- OPTANTI INPS E PERSONALE RELIGIOSO INPS
-- ****************  2010 ****************
-- *****************************************************************************
declare 
  AnnoNuovo integer;
  CodVoce varchar2(5);
  CodVoceSpeciale varchar2(5);
  Scaglione real;

  CURSOR C1 IS  
  SELECT '11010' AS COD_VOCE, 'BASE' AS COD_VOCE_SPECIALE FROM DUAL UNION
  SELECT '11010', 'ENTE' FROM DUAL UNION
  SELECT '11020', 'BASE' FROM DUAL UNION
  SELECT '11020', 'ENTE' FROM DUAL UNION
  SELECT '11160', 'BASE' FROM DUAL UNION
  SELECT '11170', 'BASE' FROM DUAL UNION
  SELECT '11410', 'BASE' FROM DUAL;
begin
  -- IMPOSTARE QUI IL NUOVO ANNO DA GESTIRE
  AnnoNuovo:=2010;
  -- IMPOSTARE QUI IL NUOVO SCAGLIONE PER CPDEL, CPS, ENPAM EX CONVENZIONATI E OPTANTI INPS
  Scaglione:=42364;

  FOR T1 IN C1 LOOP
    CodVoce:=T1.COD_VOCE;
    CodVoceSpeciale:=T1.COD_VOCE_SPECIALE;
    
    UPDATE P233_SCAGLIONIFASCE P233 SET IMPORTO_A=Scaglione WHERE P233.IMPORTO_DA=0
      AND P233.ID_SCAGLIONE=
      (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=CodVoce AND P232.COD_VOCE_SPECIALE=CodVoceSpeciale AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

    UPDATE P233_SCAGLIONIFASCE P233 SET IMPORTO_DA=Scaglione+0.01 WHERE P233.IMPORTO_A=0
      AND P233.ID_SCAGLIONE=
      (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=CodVoce AND P232.COD_VOCE_SPECIALE=CodVoceSpeciale AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));
  END LOOP;
 
end;

/

-- *****************************************************************************
-- IMPOSTAZIONE MASSIMALE PER I PARASUBORDINATI
-- ****************  2010 ****************
-- *****************************************************************************
declare 
  AnnoNuovo integer;
  CodVoce varchar2(5);
  CodVoceSpeciale varchar2(5);
  Massimale real;

  CURSOR C1 IS  
  SELECT '11110' AS COD_VOCE, 'BASE' AS COD_VOCE_SPECIALE FROM DUAL UNION
  SELECT '11115', 'BASE' FROM DUAL UNION
  SELECT '11120', 'BASE' FROM DUAL UNION
  SELECT '11125', 'BASE' FROM DUAL UNION
  SELECT '11130', 'BASE' FROM DUAL UNION
  SELECT '11135', 'BASE' FROM DUAL;  

begin
  -- IMPOSTARE QUI IL NUOVO ANNO DA GESTIRE
  AnnoNuovo:=2010;
  -- IMPOSTARE QUI IL NUOVO MASSIMALE
  Massimale:=92147;

  FOR T1 IN C1 LOOP
    CodVoce:=T1.COD_VOCE;
    CodVoceSpeciale:=T1.COD_VOCE_SPECIALE;
    
    UPDATE P233_SCAGLIONIFASCE P233 SET IMPORTO_A=Massimale WHERE P233.IMPORTO_DA=0
      AND P233.ID_SCAGLIONE=
      (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=CodVoce AND P232.COD_VOCE_SPECIALE=CodVoceSpeciale AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

    UPDATE P233_SCAGLIONIFASCE P233 SET IMPORTO_DA=Massimale+0.01 WHERE P233.IMPORTO_A=0
      AND P233.ID_SCAGLIONE=
      (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=CodVoce AND P232.COD_VOCE_SPECIALE=CodVoceSpeciale AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));
  END LOOP;
 
end;
 
/

UPDATE P200_VOCI T SET
T.DESCRIZIONE='Somma eredi indennità preavviso', T.DESCRIZIONE_STAMPA='Somma eredi indennita'' preavviso'
WHERE T.COD_VOCE='06004' AND T.DESCRIZIONE LIKE '%preavvisio';

declare
  i integer;
begin
  select COUNT(*) into i from P441_CEDOLINO;
  if i > 0 then
    select COUNT(*) into i from i500_datiliberi t where NOMECAMPO = 'INCARICO' and TABELLA = 'S';
    if i > 0 then
      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-020-2010'',''Dirigente medico equiparato con struttura semplice (dec. 2010)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-020-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV025-020-2010'',''Dirigente medico incarico lett. c) con struttura semplice (dec. 2010)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV025-020-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV035-020-2010'',''Dirigente medico < 5 anni con struttura semplice (dec. 2010)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV035-020-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV020-006-2010'',''Dirigente medico ex modulo con struttura complessa area medicina (dec. 2010)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV020-006-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR015-010-2010'',''Dirigente ruolo sanitario incarico lett. c) con struttura semplice (dec. 2010)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR015-010-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR015-006-2010-S2006'',''Dirigente ruolo sanitario incarico lett. c) con struttura complessa (dec. 2010) - semplice (dec. 2006)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR015-006-2010-S2006'')';
      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR020-010-2010'',''Dirigente ruolo sanitario equiparato con struttura semplice (dec. 2010)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR020-010-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV030-020-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico equiparato con S.S. (dec. 2010)'',
        ''00212'', ''BASE'', 457.5, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV030-020-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV025-020-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico lett. c) con S.S. (dec. 2010)'',
        ''00212'', ''BASE'', 368.19, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV025-020-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV035-020-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico < 5 anni con S.S. (dec. 2010)'',
        ''00212'', ''BASE'', 721.15, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV035-020-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV020-006-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico ex modulo con S.C. medicina (dec. 2010)'',
        ''00212'', ''BASE'', 290.64, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV020-006-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''DR015-010-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. ruolo sanitario lett. c) con S.S. (dec. 2010)'',
        ''00212'', ''BASE'', 222.88, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''DR015-010-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''DR015-006-2010-S2006'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. ruolo sanitario lett. c) con S.C. (dec. 2010) - S.S. (dec. 2006)'',
        ''00208'', ''BASE'', 22.66, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''DR015-006-2010-S2006'' AND T.COD_VOCE=''00208'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''DR015-006-2010-S2006'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. ruolo sanitario lett. c) con S.C. (dec. 2010) - S.S. (dec. 2006)'',
        ''00212'', ''BASE'', 618.81, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''DR015-006-2010-S2006'' AND T.COD_VOCE=''00212'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''DR020-010-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. ruolo sanitario equiparato con S.S. (dec. 2010)'',
        ''00212'', ''BASE'', 268.54, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''DR020-010-2010'')';
    end if;
  end if;
end;

/

create table T919_SEMAFORO (
OPERATORE varchar2(40),
DATA date)
tablespace LAVORO storage (initial 256K next 256K pctincrease 0);

alter table T020_ORARI add TIMBRATURAMENSA_FLEX varchar2(1) default 'N';
comment on column T020_ORARI.TIMBRATURAMENSA_FLEX is 'N=L''esistenza della timbratura di mensa non comporta alcuna differenza ai punti nominali, S=L''esistenza della timbratura di mensa estende il punto nominale di uscita dei minuti specificati in TIMBRATURAMENSA_DETRAZIONE';

update T020_ORARI set TIMBRATURAMENSA_FLEX  = 'S' where XPARAM like '%<THMAU_FLEX_TPM>%';
update T020_ORARI set XPARAM = replace(XPARAM,'<THMAU_FLEX_TPM>','');

alter table T275_CAUPRESENZE add TIPO_RICHIESTA_WEB varchar2(1) default 'N';
comment on column T275_CAUPRESENZE.TIPO_RICHIESTA_WEB is 'Destinazione della richiesta straordinario su web: P=Pagamento, R=Recupero, N=Nessuno';

alter table T275_CAUPRESENZE add CONSIDERA_SCELTA_ORARIO varchar2(1) default 'S';
comment on column T275_CAUPRESENZE.CONSIDERA_SCELTA_ORARIO is 'S=le timbrature con questa causale vengono considerate nella scelta dell''orario, N=le timbrature con questa causale non vengono considerate nella scelta dell''orario';
update T275_CAUPRESENZE set CONSIDERA_SCELTA_ORARIO = decode(ORENORMALI,'A','N','S');

alter table T277_CAUFASCEABILITATE add FASCE_PN varchar2(1) default 'N';
comment on column T277_CAUFASCEABILITATE.FASCE_PN is 'S=l''utilizzo della causale è consentito all''interno dei punti nominali dell''orario, N=l''utilizzo della causale è consentito nella fascia Dalle..Alle specificata';

update T275_CAUPRESENZE set CONSIDERA_SCELTA_ORARIO = 'S' where exists (select 'x' from T020_ORARI where XPARAM like '%EMPOLI_ASL11%') and CODICE in ('FILME','FILMU','FILM');
update T277_CAUFASCEABILITATE set FASCE_PN = 'S' where exists (select 'x' from T020_ORARI where XPARAM like '%EMPOLI_ASL11%') and CODICE in ('FILME','FILMU','FILM');
update T020_ORARI set XPARAM = replace(XPARAM,'<EMPOLI_ASL11>','');

create index I005_MASCHERA on I005_MSGINFO(MASCHERA) tablespace INDICI;

INSERT INTO T480_COMUNI SELECT '015250', 'BARANZATE', '20021', 'MI', 'A618' FROM DUAL
  WHERE NOT EXISTS (SELECT 'X' FROM T480_COMUNI T480 WHERE T480.CODICE = '015250');

UPDATE P010_BANCHE SET COD_COMUNE = '110001' WHERE COD_COMUNE = '072005';
UPDATE P010_BANCHE SET COD_COMUNE = '110002' WHERE COD_COMUNE = '072007';
UPDATE P010_BANCHE SET COD_COMUNE = '110003' WHERE COD_COMUNE = '072009';
UPDATE P010_BANCHE SET COD_COMUNE = '110004' WHERE COD_COMUNE = '072013';
UPDATE P010_BANCHE SET COD_COMUNE = '110005' WHERE COD_COMUNE = '071030';
UPDATE P010_BANCHE SET COD_COMUNE = '110006' WHERE COD_COMUNE = '072026';
UPDATE P010_BANCHE SET COD_COMUNE = '110007' WHERE COD_COMUNE = '071045';
UPDATE P010_BANCHE SET COD_COMUNE = '110008' WHERE COD_COMUNE = '072042';
UPDATE P010_BANCHE SET COD_COMUNE = '110009' WHERE COD_COMUNE = '072045';
UPDATE P010_BANCHE SET COD_COMUNE = '110010' WHERE COD_COMUNE = '071057';
UPDATE P010_BANCHE SET COD_COMUNE = '109001' WHERE COD_COMUNE = '044003';
UPDATE P010_BANCHE SET COD_COMUNE = '109002' WHERE COD_COMUNE = '044004';
UPDATE P010_BANCHE SET COD_COMUNE = '109003' WHERE COD_COMUNE = '044008';
UPDATE P010_BANCHE SET COD_COMUNE = '109004' WHERE COD_COMUNE = '044009';
UPDATE P010_BANCHE SET COD_COMUNE = '109005' WHERE COD_COMUNE = '044018';
UPDATE P010_BANCHE SET COD_COMUNE = '109006' WHERE COD_COMUNE = '044019';
UPDATE P010_BANCHE SET COD_COMUNE = '109007' WHERE COD_COMUNE = '044022';
UPDATE P010_BANCHE SET COD_COMUNE = '109008' WHERE COD_COMUNE = '044024';
UPDATE P010_BANCHE SET COD_COMUNE = '109009' WHERE COD_COMUNE = '044025';
UPDATE P010_BANCHE SET COD_COMUNE = '109010' WHERE COD_COMUNE = '044026';
UPDATE P010_BANCHE SET COD_COMUNE = '109011' WHERE COD_COMUNE = '044028';
UPDATE P010_BANCHE SET COD_COMUNE = '109012' WHERE COD_COMUNE = '044030';
UPDATE P010_BANCHE SET COD_COMUNE = '109013' WHERE COD_COMUNE = '044033';
UPDATE P010_BANCHE SET COD_COMUNE = '109014' WHERE COD_COMUNE = '044035';
UPDATE P010_BANCHE SET COD_COMUNE = '109015' WHERE COD_COMUNE = '044037';
UPDATE P010_BANCHE SET COD_COMUNE = '109016' WHERE COD_COMUNE = '044039';
UPDATE P010_BANCHE SET COD_COMUNE = '109017' WHERE COD_COMUNE = '044040';
UPDATE P010_BANCHE SET COD_COMUNE = '109018' WHERE COD_COMUNE = '044041';
UPDATE P010_BANCHE SET COD_COMUNE = '109019' WHERE COD_COMUNE = '044042';
UPDATE P010_BANCHE SET COD_COMUNE = '109020' WHERE COD_COMUNE = '044043';
UPDATE P010_BANCHE SET COD_COMUNE = '109021' WHERE COD_COMUNE = '044046';
UPDATE P010_BANCHE SET COD_COMUNE = '109022' WHERE COD_COMUNE = '044047';
UPDATE P010_BANCHE SET COD_COMUNE = '109023' WHERE COD_COMUNE = '044048';
UPDATE P010_BANCHE SET COD_COMUNE = '109024' WHERE COD_COMUNE = '044049';
UPDATE P010_BANCHE SET COD_COMUNE = '109025' WHERE COD_COMUNE = '044050';
UPDATE P010_BANCHE SET COD_COMUNE = '109026' WHERE COD_COMUNE = '044051';
UPDATE P010_BANCHE SET COD_COMUNE = '109027' WHERE COD_COMUNE = '044052';
UPDATE P010_BANCHE SET COD_COMUNE = '109028' WHERE COD_COMUNE = '044053';
UPDATE P010_BANCHE SET COD_COMUNE = '109029' WHERE COD_COMUNE = '044055';
UPDATE P010_BANCHE SET COD_COMUNE = '109030' WHERE COD_COMUNE = '044057';
UPDATE P010_BANCHE SET COD_COMUNE = '109031' WHERE COD_COMUNE = '044058';
UPDATE P010_BANCHE SET COD_COMUNE = '109032' WHERE COD_COMUNE = '044059';
UPDATE P010_BANCHE SET COD_COMUNE = '109033' WHERE COD_COMUNE = '044060';
UPDATE P010_BANCHE SET COD_COMUNE = '109034' WHERE COD_COMUNE = '044061';
UPDATE P010_BANCHE SET COD_COMUNE = '109035' WHERE COD_COMUNE = '044062';
UPDATE P010_BANCHE SET COD_COMUNE = '109036' WHERE COD_COMUNE = '044067';
UPDATE P010_BANCHE SET COD_COMUNE = '109037' WHERE COD_COMUNE = '044068';
UPDATE P010_BANCHE SET COD_COMUNE = '109038' WHERE COD_COMUNE = '044069';
UPDATE P010_BANCHE SET COD_COMUNE = '109039' WHERE COD_COMUNE = '044070';
UPDATE P010_BANCHE SET COD_COMUNE = '109040' WHERE COD_COMUNE = '044072';
UPDATE P010_BANCHE SET COD_COMUNE = '108001' WHERE COD_COMUNE = '015003';
UPDATE P010_BANCHE SET COD_COMUNE = '108002' WHERE COD_COMUNE = '015004';
UPDATE P010_BANCHE SET COD_COMUNE = '108003' WHERE COD_COMUNE = '015006';
UPDATE P010_BANCHE SET COD_COMUNE = '108004' WHERE COD_COMUNE = '015008';
UPDATE P010_BANCHE SET COD_COMUNE = '108005' WHERE COD_COMUNE = '015013';
UPDATE P010_BANCHE SET COD_COMUNE = '108006' WHERE COD_COMUNE = '015017';
UPDATE P010_BANCHE SET COD_COMUNE = '108007' WHERE COD_COMUNE = '015018';
UPDATE P010_BANCHE SET COD_COMUNE = '108008' WHERE COD_COMUNE = '015021';
UPDATE P010_BANCHE SET COD_COMUNE = '108009' WHERE COD_COMUNE = '015023';
UPDATE P010_BANCHE SET COD_COMUNE = '108010' WHERE COD_COMUNE = '015030';
UPDATE P010_BANCHE SET COD_COMUNE = '108011' WHERE COD_COMUNE = '015033';
UPDATE P010_BANCHE SET COD_COMUNE = '108012' WHERE COD_COMUNE = '015034';
UPDATE P010_BANCHE SET COD_COMUNE = '108013' WHERE COD_COMUNE = '015037';
UPDATE P010_BANCHE SET COD_COMUNE = '108014' WHERE COD_COMUNE = '015045';
UPDATE P010_BANCHE SET COD_COMUNE = '108015' WHERE COD_COMUNE = '015048';
UPDATE P010_BANCHE SET COD_COMUNE = '108016' WHERE COD_COMUNE = '015049';
UPDATE P010_BANCHE SET COD_COMUNE = '108017' WHERE COD_COMUNE = '015068';
UPDATE P010_BANCHE SET COD_COMUNE = '108018' WHERE COD_COMUNE = '015069';
UPDATE P010_BANCHE SET COD_COMUNE = '108019' WHERE COD_COMUNE = '015075';
UPDATE P010_BANCHE SET COD_COMUNE = '108020' WHERE COD_COMUNE = '015080';
UPDATE P010_BANCHE SET COD_COMUNE = '108021' WHERE COD_COMUNE = '015084';
UPDATE P010_BANCHE SET COD_COMUNE = '108022' WHERE COD_COMUNE = '015092';
UPDATE P010_BANCHE SET COD_COMUNE = '108023' WHERE COD_COMUNE = '015100';
UPDATE P010_BANCHE SET COD_COMUNE = '108024' WHERE COD_COMUNE = '015107';
UPDATE P010_BANCHE SET COD_COMUNE = '108025' WHERE COD_COMUNE = '015117';
UPDATE P010_BANCHE SET COD_COMUNE = '108026' WHERE COD_COMUNE = '015120';
UPDATE P010_BANCHE SET COD_COMUNE = '108027' WHERE COD_COMUNE = '015121';
UPDATE P010_BANCHE SET COD_COMUNE = '108028' WHERE COD_COMUNE = '015123';
UPDATE P010_BANCHE SET COD_COMUNE = '108029' WHERE COD_COMUNE = '015129';
UPDATE P010_BANCHE SET COD_COMUNE = '108030' WHERE COD_COMUNE = '015138';
UPDATE P010_BANCHE SET COD_COMUNE = '108031' WHERE COD_COMUNE = '015145';
UPDATE P010_BANCHE SET COD_COMUNE = '108032' WHERE COD_COMUNE = '015147';
UPDATE P010_BANCHE SET COD_COMUNE = '108033' WHERE COD_COMUNE = '015149';
UPDATE P010_BANCHE SET COD_COMUNE = '108034' WHERE COD_COMUNE = '015152';
UPDATE P010_BANCHE SET COD_COMUNE = '108035' WHERE COD_COMUNE = '015156';
UPDATE P010_BANCHE SET COD_COMUNE = '108036' WHERE COD_COMUNE = '015161';
UPDATE P010_BANCHE SET COD_COMUNE = '108037' WHERE COD_COMUNE = '015180';
UPDATE P010_BANCHE SET COD_COMUNE = '108038' WHERE COD_COMUNE = '015187';
UPDATE P010_BANCHE SET COD_COMUNE = '108039' WHERE COD_COMUNE = '015208';
UPDATE P010_BANCHE SET COD_COMUNE = '108040' WHERE COD_COMUNE = '015212';
UPDATE P010_BANCHE SET COD_COMUNE = '108041' WHERE COD_COMUNE = '015216';
UPDATE P010_BANCHE SET COD_COMUNE = '108042' WHERE COD_COMUNE = '015217';
UPDATE P010_BANCHE SET COD_COMUNE = '108043' WHERE COD_COMUNE = '015223';
UPDATE P010_BANCHE SET COD_COMUNE = '108044' WHERE COD_COMUNE = '015227';
UPDATE P010_BANCHE SET COD_COMUNE = '108045' WHERE COD_COMUNE = '015231';
UPDATE P010_BANCHE SET COD_COMUNE = '108046' WHERE COD_COMUNE = '015232';
UPDATE P010_BANCHE SET COD_COMUNE = '108047' WHERE COD_COMUNE = '015233';
UPDATE P010_BANCHE SET COD_COMUNE = '108048' WHERE COD_COMUNE = '015234';
UPDATE P010_BANCHE SET COD_COMUNE = '108049' WHERE COD_COMUNE = '015239';
UPDATE P010_BANCHE SET COD_COMUNE = '108050' WHERE COD_COMUNE = '015241';
UPDATE P010_BANCHE SET COD_COMUNE = '108051' WHERE COD_COMUNE = '015039';
UPDATE P010_BANCHE SET COD_COMUNE = '108052' WHERE COD_COMUNE = '015047';
UPDATE P010_BANCHE SET COD_COMUNE = '108053' WHERE COD_COMUNE = '015088';
UPDATE P010_BANCHE SET COD_COMUNE = '108054' WHERE COD_COMUNE = '015119';
UPDATE P010_BANCHE SET COD_COMUNE = '108055' WHERE COD_COMUNE = '015186';

ALTER TABLE T770_QUOTE MODIFY CAUSALE DEFAULT ' ';

alter table T162_INDENNITA modify ASSENZE_ABILITATE varchar2(1000);
alter table T162_INDENNITA modify ASSENZE varchar2(1000);

alter table MONDOEDP.I090_ENTI add DOMINIO_USR_TIPO varchar2(5) default 'NTLM';
comment on column MONDOEDP.I090_ENTI.DOMINIO_USR_TIPO is 'valori ammessi: NTLM, AD';
alter table MONDOEDP.I090_ENTI add DOMINIO_DIP_TIPO varchar2(5) default 'NTLM';
comment on column MONDOEDP.I090_ENTI.DOMINIO_DIP_TIPO is 'valori ammessi: NTLM, AD';

alter table T275_CAUPRESENZE add FLEX_TIMBR_CAUS varchar2(1) default 'N';
comment on column T275_CAUPRESENZE.FLEX_TIMBR_CAUS is 'N=I minuti causalizzati non impattano sulla flessibilità, A=Le timbrature causalizzate aumentano la flessibilità solo se <= SOGLIA_FASCE_OBBLFAC, B=Le timbrature causalizzate aumentano la flessibilità fino al massimo a SOGLIA_FASCE_OBBLFAC' ;
update T275_CAUPRESENZE set FLEX_TIMBR_CAUS = 'A' where TIPOCONTEGGIO in ('A','E') and ORENORMALI = 'A' and ESCLUSIONE_FASCIA_OBB = 'N' and nvl(SOGLIA_FASCE_OBBLFAC,0) > 0;

update T275_CAUPRESENZE set FLEX_TIMBR_CAUS = 'B' where exists (select 'x' from T020_ORARI where XPARAM like '%FIRENZE_COMUNE%') and CODICE in ('10');
update T020_ORARI set XPARAM = replace(XPARAM,'<FIRENZE_COMUNE>','') ;

INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','DC_OREDEBITO',4,'2','DECODE(NVL(GGlavorativo,''*''),''*'',0, Debitocartellino) ','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA) 
SELECT 
'_ASSPRES','DC_OREDEBITO','DC_OREDEBITO','D','N',0,1320,80,16,'','N','N','N' FROM T910_RIEPILOGO WHERE CODICE = '_ASSPRES';
ALTER TABLE T920ASSPRES ADD DC_OREDEBITO NUMBER/*--NOLOG--*/;
UPDATE T920ASSPRES SET DC_OREDEBITO = 0/*--NOLOG--*/;

INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA) 
SELECT 
'_ASSPRES','Assenza:data familiare','Assenza:data familiare','D','N',0,1420,80,16,'','N','N','N' FROM T910_RIEPILOGO WHERE CODICE = '_ASSPRES';
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO, POS, DATO, TOTALE) 
SELECT 
'_ASSPRES',4, 2,'Assenza:data familiare','N' FROM T910_RIEPILOGO WHERE CODICE = '_ASSPRES';
ALTER TABLE T920ASSPRES ADD ASSENZADATAFAMILIARE DATE/*--NOLOG--*/;

INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA) 
SELECT 
'_ASSPRES','Assenza:U.M.Fruizione','Assenza:U.M.Fruizione','D','N',0,1520,80,16,'','N','N','N' FROM T910_RIEPILOGO WHERE CODICE = '_ASSPRES';
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO, POS, DATO, TOTALE) 
SELECT 
'_ASSPRES',4, 3,'Assenza:U.M.Fruizione','N' FROM T910_RIEPILOGO WHERE CODICE = '_ASSPRES';
ALTER TABLE T920ASSPRES ADD ASSENZAUMFRUIZIONE VARCHAR2(1)/*--NOLOG--*/;
UPDATE T920ASSPRES SET ASSENZAUMFRUIZIONE = 'I'/*--NOLOG--*/;

ALTER TABLE T151_ASSENTEISMO ADD ASS_FAMILIARI VARCHAR2(50); 
comment on column T151_ASSENTEISMO.ASS_FAMILIARI is 'Familiari di riferimento'; 
ALTER TABLE T151_ASSENTEISMO ADD ASS_FRUIZIONE_GG VARCHAR2(1) DEFAULT 'S'; 
ALTER TABLE T151_ASSENTEISMO ADD ASS_FRUIZIONE_MG VARCHAR2(1) DEFAULT 'S'; 
ALTER TABLE T151_ASSENTEISMO ADD ASS_FRUIZIONE_HH VARCHAR2(1) DEFAULT 'S'; 
ALTER TABLE T151_ASSENTEISMO ADD ASS_FRUIZIONE_DH VARCHAR2(1) DEFAULT 'S'; 
comment on column T151_ASSENTEISMO.ASS_FRUIZIONE_GG is 'Considera fruizione a giornate'; 
comment on column T151_ASSENTEISMO.ASS_FRUIZIONE_MG is 'Considera fruizione a mezze giornate'; 
comment on column T151_ASSENTEISMO.ASS_FRUIZIONE_HH is 'Considera fruizione a ore'; 
comment on column T151_ASSENTEISMO.ASS_FRUIZIONE_DH is 'Considera fruizione da ore a ore'; 
ALTER TABLE T151_ASSENTEISMO ADD ASS_MAXPERIODO_GG NUMBER(4) DEFAULT 9999; 
comment on column T151_ASSENTEISMO.ASS_MAXPERIODO_GG is 'Periodo massimo da considerare in giorni'; 
ALTER TABLE T151_ASSENTEISMO ADD ASS_DEBITO_GGINT VARCHAR2(1) DEFAULT 'C'; 
comment on column T151_ASSENTEISMO.ASS_DEBITO_GGINT is 'Debito di riferimento per la giornata intera'; 
ALTER TABLE T151_ASSENTEISMO ADD TOTALE_GENERALE VARCHAR2(1) DEFAULT 'N'; 
comment on column T151_ASSENTEISMO.TOTALE_GENERALE is 'Totale generale di tutte le colonne'; 

UPDATE MONDOEDP.I073_FILTROFUNZIONI
SET APPLICAZIONE = 'RILPRE'
WHERE GRUPPO = 'Funzioni WEB'
AND FUNZIONE = 'OpenW023PianifOrari'
AND APPLICAZIONE = 'FUNWEB';

ALTER TABLE SG711_VALUTAZIONI_DIPENDENTE 
ADD DESC_VALUTAZIONE_AGG VARCHAR2(500);

ALTER TABLE SG740_REGOLE_VALUTAZIONI 
ADD ELEMENTI_PERSONALIZZATI NUMBER(3);

CREATE TABLE SG735_PUNTEGGIFASCE_INCENTIVI
(DECORRENZA DATE NOT NULL,
DECORRENZA_FINE DATE,
PUNTEGGIO_DA NUMBER NOT NULL,
PUNTEGGIO_A NUMBER NOT NULL,
PERC NUMBER NOT NULL)
tablespace LAVORO storage (initial 256K next 256K pctincrease 0);
alter table SG735_PUNTEGGIFASCE_INCENTIVI
add constraint SG735_PK primary key (DECORRENZA, PUNTEGGIO_DA, PUNTEGGIO_A)
using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);

ALTER TABLE T275_CAUPRESENZE
ADD INCLUSIONE_SALDI_CAUSALI VARCHAR2(1) DEFAULT 'N';

alter table P590_CONTABREGOLE modify FILTRO_DIPENDENTI VARCHAR2(500);
alter table P590_CONTABREGOLE modify CODICI_ACCORPAMENTOVOCI VARCHAR2(300);

ALTER TABLE T950_STAMPACARTELLINO ADD CAUPRES VARCHAR2(1000);
COMMENT ON COLUMN T950_STAMPACARTELLINO.CAUPRES IS 'Elenco delle causali di presenza da visualizzare sul cartellino';

update p552_contoannregole t 
set t.regola_calcolo_manuale=replace(t.regola_calcolo_manuale,
    'AND TO_DATE(''3112''||:AnnoElaborazione,''DDMMYYYY'') BETWEEN T430A.INIZIO',
    'AND TO_DATE(''0101''||:AnnoElaborazione,''DDMMYYYY'') BETWEEN T430A.INIZIO')
where t.anno>=2009 and t.cod_tabella='T04' and t.riga=0 and t.colonna>0;


update  p260_mod730tipoimporti t set t.int_rate=0.33
where t.anno=2010 and t.int_rate is not null;

alter table T910_RIEPILOGO modify INTESTAZIONE_COLONNE default 'S';

alter table T911_DATIRIEPILOGO add RIPETUTO varchar2(1) default 'N';
comment on column T911_DATIRIEPILOGO.RIPETUTO is 'S=I dati anagrafici sono ripetuti su ogni riga di dettaglio, N=I dati anagrafici sono riportati solo sulla prima riga del dettaglio';

alter table T275_CAUPRESENZE add FORZA_NOTTE_SPEZZATA varchar2(1) default 'N';
comment on column T275_CAUPRESENZE.FORZA_NOTTE_SPEZZATA is 'S=il conteggio delle ore con questa causale avviene sempre spezzando la notte a mezzanotte, anche se il modello orario prevede il conteggio del turno notturno sull''entrata.';

ALTER TABLE T770_QUOTE ADD PENALIZZAZIONE NUMBER DEFAULT 0;
RENAME T772_PENALIZZINCENTIVI TO T772_OLD;
comment on column T770_QUOTE.PENALIZZAZIONE 
  is 'Percentuale di penalizzazione';
ALTER TABLE T775_QUOTEINDIVIDUALI MODIFY PENALIZZAZIONE DEFAULT 0;
create table T773_PESATUREGRUPPO
( DECORRENZA       DATE not null,
  CODGRUPPO     VARCHAR2(5) not null,
  DESCRIZIONE     VARCHAR2(100),
  FILTRO_ANAGRAFE VARCHAR2(4000),
  CODTIPOQUOTA  VARCHAR2(5) not null,
  PESO_TOTALE NUMBER,
  PESO_IND_MIN NUMBER default 1,
  PESO_IND_MAX NUMBER,
  QUOTA_TOTALE NUMBER)
tablespace LAVORO storage (initial 256K next 256K pctincrease 0);
alter table T773_PESATUREGRUPPO
  add constraint T773_PK primary key (DECORRENZA, CODGRUPPO, CODTIPOQUOTA)
  using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);
create table T774_PESATUREINDIVIDUALI
( DECORRENZA       DATE not null,
  CODGRUPPO     VARCHAR2(5) not null,
  CODTIPOQUOTA     VARCHAR2(5) not null,
  PROGRESSIVO      NUMBER(8) not null,
  PESO_INDIVIDUALE NUMBER default 1,
  PESO_CALCOLATO NUMBER,
  QUOTA_INDIVIDUALE  NUMBER,
  QUOTA_CALCOLATA NUMBER)
tablespace LAVORO storage (initial 256K next 256K pctincrease 0);
alter table T774_PESATUREINDIVIDUALI
  add constraint T774_PK primary key (DECORRENZA, CODGRUPPO, CODTIPOQUOTA, PROGRESSIVO)
  using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);
comment on column T773_PESATUREGRUPPO.DECORRENZA
  is 'Decorrenza';
comment on column T773_PESATUREGRUPPO.CODGRUPPO
  is 'Codice identificativo del gruppo di appartenenza';
comment on column T773_PESATUREGRUPPO.CODTIPOQUOTA
  is 'Codice identificativo del tipo quota';
comment on column T773_PESATUREGRUPPO.FILTRO_ANAGRAFE
  is 'Filtro anagrafico che identifica i dipendenti del gruppo';
comment on column T773_PESATUREGRUPPO.PESO_TOTALE
  is 'Punteggio di pesatura massimo totale del gruppo';
comment on column T773_PESATUREGRUPPO.PESO_IND_MIN
  is 'Punteggio di pesatura minimo individuale';
comment on column T773_PESATUREGRUPPO.PESO_IND_MAX
  is 'Punteggio di pesatura massimo individuale';
comment on column T773_PESATUREGRUPPO.QUOTA_TOTALE
  is 'Importo massimo della quota totale del gruppo';
comment on column T774_PESATUREINDIVIDUALI.DECORRENZA
  is 'Decorrenza';
comment on column T774_PESATUREINDIVIDUALI.CODGRUPPO
  is 'Codice identificativo del gruppo di appartenenza';
comment on column T774_PESATUREINDIVIDUALI.CODTIPOQUOTA
  is 'Codice identificativo del tipo quota';
comment on column T774_PESATUREINDIVIDUALI.PROGRESSIVO
  is 'Progressivo del dipendente';
comment on column T774_PESATUREINDIVIDUALI.PESO_INDIVIDUALE
  is 'Punteggio di pesatura individuale impostato da utente';
comment on column T774_PESATUREINDIVIDUALI.QUOTA_INDIVIDUALE  
  is 'Importo della quota individuale impostato da utente';   
comment on column T774_PESATUREINDIVIDUALI.PESO_CALCOLATO
  is 'Punteggio di pesatura individuale calcolato automaticamente (proporzionato su gg.servizio, part-time, assenze)';
comment on column T774_PESATUREINDIVIDUALI.QUOTA_CALCOLATA
  is 'Importo della quota individuale calcolato automaticamente (proporzionato su gg.servizio, part-time, assenze)';
CREATE TABLE AGG78_T770 AS SELECT * FROM T770_QUOTE;
UPDATE T770_QUOTE SET PERC_INDIVIDUALE = 100 WHERE PERC_INDIVIDUALE = 0;
UPDATE T770_QUOTE SET PERC_STRUTTURALE = 0 WHERE PERC_STRUTTURALE = 100;
ALTER TABLE T770_QUOTE ADD VALUT_STRUTTURALE NUMBER DEFAULT 100;
comment on column T770_QUOTE.VALUT_STRUTTURALE 
  is 'Percentuale di valutazione strutturale';
comment on column T775_QUOTEINDIVIDUALI.PERC_STRUTTURALE 
  is 'Percentuale di valutazione della quota strutturale';
comment on column T775_QUOTEINDIVIDUALI.PERC_INDIVIDUALE 
  is 'Percentuale di valutazione della quota individuale';
ALTER TABLE T769_INCENTIVIASSENZE ADD PROPORZIONE_FRANCHIGIA VARCHAR2(1) DEFAULT 'N';
comment on column T769_INCENTIVIASSENZE.PROPORZIONE_FRANCHIGIA
  is 'Proporzionamento dei giorni di franchigia sui giorni di servizio del dipendente';

ALTER TABLE SG101_FAMILIARI ADD NOME_PA VARCHAR2(100);
ALTER TABLE SG101_FAMILIARI ADD INDIRIZZO VARCHAR2(40);
ALTER TABLE SG101_FAMILIARI ADD COMUNE VARCHAR2(6);
ALTER TABLE SG101_FAMILIARI ADD CAP VARCHAR2(5);
ALTER TABLE SG101_FAMILIARI ADD TELEFONO VARCHAR2(15);
ALTER TABLE SG101_FAMILIARI ADD CAPNAS VARCHAR2(5);
comment on column SG101_FAMILIARI.NOME_PA is 'Denominazione pubblica amministrazione dove il familiare lavora';
comment on column SG101_FAMILIARI.INDIRIZZO is 'Indirizzo di residenza del familiare';
comment on column SG101_FAMILIARI.COMUNE is 'Comune di residenza del familiare';
comment on column SG101_FAMILIARI.CAP is 'CAP del comune di residenza del familiare';
comment on column SG101_FAMILIARI.TELEFONO is 'Telefono del familiare';
comment on column SG101_FAMILIARI.CAPNAS is 'CAP del comune di nascita del familiare';

alter table T265_CAUASSENZE add CUMULA_RICHIESTE_WEB varchar2(1) default 'N';
comment on column T265_CAUASSENZE.CUMULA_RICHIESTE_WEB is 'N=Non considera le richieste da IrisWEB, R=Considera le richieste da IrisWEB, A=Considera le richieste da IrisWEB solo se autorizzate';

alter table T265_CAUASSENZE add NO_SUPERO_COMPETENZE_WEB varchar2(1) default 'N';
comment on column T265_CAUASSENZE.NO_SUPERO_COMPETENZE_WEB is 'N=Consente di superare le competenze in IrisWEB, S=Non consente di superare le competenze in IrisWEB';
update T265_CAUASSENZE set NO_SUPERO_COMPETENZE_WEB = NO_SUPERO_COMPETENZE;

alter table T105_RICHIESTETIMBRATURE add MOTIVAZIONE varchar2(5);

create table T106_MOTIVAZIONIRICHIESTE (
  TIPO varchar2(5),
  CODICE varchar2(5),
  DESCRIZIONE varchar2(40),
  CODICE_DEFAULT varchar2(1)
) tablespace LAVORO storage (initial 256K next 256K pctincrease 0);

alter table T106_MOTIVAZIONIRICHIESTE add constraint T106_PK primary key (TIPO,CODICE) using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);

alter table T106_MOTIVAZIONIRICHIESTE modify CODICE_DEFAULT default 'N';
alter table T106_MOTIVAZIONIRICHIESTE modify TIPO default 'T';
comment on column T106_MOTIVAZIONIRICHIESTE.TIPO is 'A=Assenze, T=Timbrature';
comment on column T106_MOTIVAZIONIRICHIESTE.CODICE_DEFAULT is 'S=motivazione proposta per default in fase di nuova richiesta';

alter table T910_RIEPILOGO modify TABELLA_GENERATA varchar2(200);

alter table T910_RIEPILOGO add STAMPA_BLOCCATA varchar2(1) default 'N';
comment on column T910_RIEPILOGO.STAMPA_BLOCCATA is 'N=Stampa modificabile dagli utenti, S=Stampa modificabile solo da MONDOEDP';

alter table T910_RIEPILOGO add DATA_ACCESSO date;
comment on column T910_RIEPILOGO.DATA_ACCESSO is 'Data e ora dell''ultimo utilizzo della stampa';

alter table T910_RIEPILOGO add UTENTE_ACCESSO varchar2(30);
comment on column T910_RIEPILOGO.UTENTE_ACCESSO is 'Ultimo utente che ha utilizzato la stampa';

alter table MONDOEDP.I071_PERMESSI add MODIFICA_DATI_PROTETTI varchar2(1) default 'N';

alter table P240_TIPIASSOGGETTAMENTI add (TFR VARCHAR2(1) default 'N');
comment on column P240_TIPIASSOGGETTAMENTI.TFR is 'Regime TFR (S/N)';

alter table T350_REGREPERIB add PIANIF_MAX_MESE number(2);
comment on column T350_REGREPERIB.PIANIF_MAX_MESE is 'massimo numero di turni pianificabili nel mese per dipendente';
alter table T350_REGREPERIB add PIANIF_MAX_MESE_TURNI_INTERI varchar2(1);
comment on column T350_REGREPERIB.PIANIF_MAX_MESE_TURNI_INTERI is 'S=il massimo di turni nel mese si riferisce alla durata dei turni interi, N=il massimo di turni nel mese si riferisce al numero di turni pianificati';
alter table T350_REGREPERIB add ORE_MIN_INDENNITA varchar2(5);
comment on column T350_REGREPERIB.ORE_MIN_INDENNITA is 'ore minime che devono essere riconosciute sul turno affinché si possa maturare l''indennità';

alter table T265_CAUASSENZE add UM_SCARICOPAGHE varchar2(1) default 'F';
comment on column T265_CAUASSENZE.UM_SCARICOPAGHE is 'unità di misura con cui scaricare le assenze fruite alle paghe: F=Fruizione, C=Competenze, G=Giorni, O=Ore';

update T265_CAUASSENZE set UM_SCARICOPAGHE = decode(SCARICOPAGHE_UM_PROP,'S','C','F');

update p260_mod730tipoimporti t 
set t.descrizione=replace(t.descrizione,'lavoro straor.','incr. produtt.')
where t.anno=2010 and t.cod_tipoimporto in ('TSC','TSD');

UPDATE p240_tipiassoggettamenti t SET T.TFR='S' 
WHERE T.COD_CONTRATTO='EDP' AND EXISTS
(SELECT 'X' FROM P242_TIPIASSOGGETTAMENTIVOCI V WHERE T.ID_TIPOASSOGGETTAMENTO=V.ID_TIPOASSOGGETTAMENTO
AND V.COD_VOCE IN('10070','10075'));

UPDATE P502_CUDREGOLE SET REGOLA_CALCOLO_MANUALE =
'SELECT DECODE(INSTR(P094.COD_GESTASSIC,''6''),0,DECODE(INSTR(P094.COD_GESTASSIC,''7''),0,'''',''7''),''6'') 
       || DECODE(NVL(P240.TFR,''N''),''S'',''001'',''003'') DATO
FROM P430_ANAGRAFICO P430, P094_INQUADRINPDAP P094, P240_TIPIASSOGGETTAMENTI P240 
WHERE P430.COD_INQUADRINPDAP = P094.COD_INQUADRINPDAP
AND P430.PROGRESSIVO = :Progressivo
AND TO_DATE(''3112''||:AA_Inpdap,''DDMMYYYY'') BETWEEN P430.DECORRENZA AND P430.DECORRENZA_FINE
AND TO_DATE(''3112''||:AA_Inpdap,''DDMMYYYY'') BETWEEN P094.DECORRENZA AND P094.DECORRENZA_FINE
AND P430.COD_TIPOASSOGGETTAMENTO = P240.COD_TIPOASSOGGETTAMENTO(+)
AND TO_DATE(''3112''||:AA_Inpdap,''DDMMYYYY'') BETWEEN P240.DECORRENZA(+) AND P240.DECORRENZA_FINE(+)'
WHERE ANNO = 2009 AND PARTE = 'C21' AND NUMERO = '022';

UPDATE P502_CUDREGOLE SET REGOLA_CALCOLO_AUTOMATICA = REGOLA_CALCOLO_MANUALE  WHERE ANNO = 2009 AND PARTE = 'C21' AND NUMERO = '022';

UPDATE P660_FLUSSIREGOLE SET REGOLA_CALCOLO_MANUALE =
'SELECT  SUM(P272.IMPORTO * P201.ASSOGGETTAMENTO / 100) DATO FROM P272_RETRIBUZIONE_CONTRATTUALE P272, P201_ASSOGGETTAMENTI P201
WHERE P272.PROGRESSIVO = :Progressivo 
AND :DataElaborazione BETWEEN P272.DECORRENZA_INIZIO AND P272.DECORRENZA_FINE
AND P272.COD_CONTRATTO = P201.COD_CONTRATTO AND P272.COD_VOCE = P201.COD_VOCE_PADRE
AND P272.COD_VOCE_SPECIALE = P201.COD_VOCE_SPECIALE_PADRE AND P201.DECORRENZA =
(SELECT MAX(DECORRENZA) FROM P201_ASSOGGETTAMENTI WHERE COD_CONTRATTO = P201.COD_CONTRATTO 
 AND COD_VOCE_PADRE = P201.COD_VOCE_PADRE AND COD_VOCE_SPECIALE_PADRE = P201.COD_VOCE_SPECIALE_PADRE
 AND COD_VOCE_FIGLIO = P201.COD_VOCE_FIGLIO AND COD_VOCE_SPECIALE_FIGLIO = P201.COD_VOCE_SPECIALE_FIGLIO
 AND DECORRENZA <= :DataElaborazione)
AND RPAD(P201.COD_VOCE_FIGLIO,6,'' '')||P201.COD_VOCE_SPECIALE_FIGLIO IN (''14120 BASE'')
AND EXISTS (SELECT ''*'' FROM P430_ANAGRAFICO P430, P240_TIPIASSOGGETTAMENTI P240
            WHERE P430.PROGRESSIVO = P272.PROGRESSIVO
            AND P430.COD_TIPOASSOGGETTAMENTO = P240.COD_TIPOASSOGGETTAMENTO
            AND :DataElaborazione BETWEEN P240.DECORRENZA AND P240.DECORRENZA_FINE
            AND :DataElaborazione BETWEEN P430.DECORRENZA AND P430.DECORRENZA_FINE
            AND P240.TFR = ''S'') '
WHERE NOME_FLUSSO = 'DMA' AND PARTE = 'V1' AND NUMERO = '043';

UPDATE P660_FLUSSIREGOLE SET REGOLA_CALCOLO_AUTOMATICA = REGOLA_CALCOLO_MANUALE WHERE NOME_FLUSSO = 'DMA' AND PARTE = 'V1' AND NUMERO = '043';

alter table P430_ANAGRAFICO drop column TFR;

insert into P001_TABP430 (COLONNA_P430, TABELLA, COLONNA_TABELLA)
values ('COD_TIPOASSOGGETTAMENTO', 'P240_TIPIASSOGGETTAMENTI', 'COD_TIPOASSOGGETTAMENTO');

update t265_cauassenze set CQ_GGNONLAV = 'F' where CQ_FESTIVI = 'S'
  and CQ_GGNONLAV = 'S';

UPDATE P430_ANAGRAFICO T SET T.COD_NAZIONALITA='000' WHERE T.TIPO_DIPENDENTE='IN' AND T.COD_NAZIONALITA IS NULL;

UPDATE P602_770REGOLE t SET T.NUMERICO='S' WHERE T.ANNO=2009 AND T.PARTE='D' AND T.NUMERO='123';

UPDATE P602_770REGOLE t SET T.NUMERICO='N' WHERE T.ANNO=2009 AND T.PARTE='B' AND T.NUMERO IN('285B','292B');

UPDATE P602_770REGOLE T 
SET T.REGOLA_CALCOLO_MANUALE=REPLACE(T.REGOLA_CALCOLO_MANUALE,'SELECT T480.PROVINCIA DATO','SELECT RTRIM(T480.PROVINCIA) DATO')
WHERE T.ANNO=2009 AND T.PARTE='A' AND T.NUMERO='007';

UPDATE P220_LIVELLI T SET T.DESCRIZIONE='Specialisti ambulatoriali titolari A.C.N.'
WHERE T.COD_CONTRATTO='EDPSC' AND T.COD_POSIZIONE_ECONOMICA='MA130';

UPDATE P220_LIVELLI T SET T.DESCRIZIONE='Specialisti ambulatoriali non titolari A.C.N.'
WHERE T.COD_CONTRATTO='EDPSC' AND T.COD_POSIZIONE_ECONOMICA='MA132';

UPDATE P220_LIVELLI T SET T.DESCRIZIONE='Professionisti ambulatoriali titolari A.C.N.'
WHERE T.COD_CONTRATTO='EDPSC' AND T.COD_POSIZIONE_ECONOMICA='MA135';

UPDATE P220_LIVELLI T SET T.DESCRIZIONE='Professionisti ambulatoriali non titolari A.C.N.'
WHERE T.COD_CONTRATTO='EDPSC' AND T.COD_POSIZIONE_ECONOMICA='MA137';

ALTER TABLE T774_PESATUREINDIVIDUALI ADD GG_SERVIZIO NUMBER;
ALTER TABLE T774_PESATUREINDIVIDUALI ADD DATAINIZIO DATE;
ALTER TABLE T774_PESATUREINDIVIDUALI ADD DATAFINE DATE;
ALTER TABLE T773_PESATUREGRUPPO MODIFY CODGRUPPO VARCHAR2(10);
ALTER TABLE T774_PESATUREINDIVIDUALI MODIFY CODGRUPPO VARCHAR2(10);
ALTER TABLE T773_PESATUREGRUPPO ADD DATARIF DATE;
ALTER TABLE T773_PESATUREGRUPPO ADD ANNO NUMBER;
ALTER TABLE T774_PESATUREINDIVIDUALI ADD ANNO NUMBER;
alter table T773_PESATUREGRUPPO drop primary key;
drop index T773_PK;
alter table T773_PESATUREGRUPPO
  add constraint T773_PK primary key (ANNO, CODGRUPPO, CODTIPOQUOTA)
  using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);
alter table T774_PESATUREINDIVIDUALI drop primary key;
drop index T774_PK;
alter table T774_PESATUREINDIVIDUALI
  add constraint T774_PK primary key (ANNO, CODGRUPPO, CODTIPOQUOTA, PROGRESSIVO)
  using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);
ALTER TABLE T773_PESATUREGRUPPO DROP COLUMN DECORRENZA;
ALTER TABLE T774_PESATUREINDIVIDUALI DROP COLUMN DECORRENZA;

update T914_SERBATOIFILTRO set FILTRO = 
replace(FILTRO,
        'CONTROLLO_RIPOSI(PROGRESSIVO4,Dataconteggio,'' '') <= ''11.00''',
        'CONTROLLO_RIPOSI(PROGRESSIVO4,Dataconteggio,'' '') <= 660')
where upper(FILTRO) like '%CONTROLLO_RIPOSI(%';

update T914_SERBATOIFILTRO set FILTRO = 
replace(FILTRO,
        'OREMINUTI(CONTROLLO_RIPOSI(PROGRESSIVO4,Dataconteggio,'' '')) <= OREMINUTI(''11.00'')',
        'CONTROLLO_RIPOSI(PROGRESSIVO4,Dataconteggio,'' '') <= 660')
where upper(FILTRO) like '%CONTROLLO_RIPOSI(%';