ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD PATH_ISTRUZIONI VARCHAR2(1000);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD FIRME_VALUTATORI NUMBER(1) DEFAULT 1;
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD DATO_VARIAZIONE_VALUTATORE VARCHAR2(30);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD FIRMA_AGGIUNTIVA VARCHAR2(50);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD COD_DATO_FIRMA_AGGIUNTIVA VARCHAR2(400);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD COD_DATO_VALUT_COMPLESSIVE VARCHAR2(400);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD COD_DATO_OBIETTIVI_PIANIFICATI VARCHAR2(400);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD COD_DATO_PROPOSTE_FORMATIVE VARCHAR2(400);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD TESTO_VALUTAZIONI_COMPLESSIVE VARCHAR2(500);
ALTER TABLE SG740_REGOLE_VALUTAZIONI ADD ABILITA_COMMENTI_VALUTATO VARCHAR2(1) DEFAULT '1';

UPDATE SG740_REGOLE_VALUTAZIONI 
SET FIRME_VALUTATORI = 4
WHERE FIRME_VALUTATORI IS NULL;

ALTER TABLE SG730_PUNTEGGI MODIFY PUNTEGGIO NULL;

UPDATE SG730_PUNTEGGI
SET PUNTEGGIO = NULL
WHERE CALCOLO_PFP = 'N';

alter table T260_RAGGRASSENZE add RAGGR_RESIDUO_PREC varchar2(5);
comment on column T260_RAGGRASSENZE.RAGGR_RESIDUO_PREC is 'Raggruppamento su cui residuare i residui dell''anno precedente a quello in cui vengono calcolati';

alter table T275_CAUPRESENZE add PERIODICITA_ABBATTIMENTO number(2) default -1;
comment on column T275_CAUPRESENZE.PERIODICITA_ABBATTIMENTO is 'Numero di mesi entro cui disporre delle ore ai fini di recuperi/liquidazioni';

alter table P258_ADDIZIONALIIRPEF add ATTIVA VARCHAR2(1) default 'S' not null;
comment on column P258_ADDIZIONALIIRPEF.ATTIVA is 'Attiva (S/N) indica se l''addizionale deve entrare nel conteggio del mese';

ALTER TABLE T768_INCQUANTINDIVIDUALI MODIFY COD_PROFILO VARCHAR2(20);