CREATE TABLE T350_REGREPERIB (
 CODICE VARCHAR2(5) NOT NULL,
 DESCRIZIONE VARCHAR2(40),
 ORAINIZIO DATE NOT NULL,
 ORAFINE DATE NOT NULL,
 TIPOORE VARCHAR2(1),
 ORENORMALI DATE,
 ORECOMPRESENZA DATE,
 TIPOTURNO VARCHAR2(1),
 RAGGRUPPAMENTO VARCHAR(20),
 PRIMARY KEY (CODICE) USING INDEX  TABLESPACE INDICI
)
TABLESPACE LAVORO

CREATE TABLE MONDOEDP.T380_PIANIFREPERIB (
  DATA DATE NOT NULL,
  PROGRESSIVO NUMBER(38,2) NOT NULL,
  BADGE NUMBER(38, 2),
  NOME VARCHAR2(60),
  TURNO1 VARCHAR2(5),
  TURNO2 VARCHAR2(5),
  PRIMARY KEY (DATA,PROGRESSIVO) USING INDEX TABLESPACE INDICI
)
  TABLESPACE LAVORO

