UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.5.4' WHERE AZIENDA = :AZIENDA;

UPDATE I073_FILTROFUNZIONI SET DESCRIZIONE = 'Parametri avanzati voci paghe' WHERE TAG = 162;
RENAME T193_VOCIPAGHENEGATIVE TO T193_VOCIPAGHE_PARAMETRI;
ALTER TABLE T193_VOCIPAGHE_PARAMETRI ADD DESCRIZIONE VARCHAR2(40);
ALTER TABLE T193_VOCIPAGHE_PARAMETRI ADD DAL DATE;
ALTER TABLE T193_VOCIPAGHE_PARAMETRI ADD AL DATE;
ALTER TABLE T193_VOCIPAGHE_PARAMETRI ADD AUTOINC_DAL VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T193_VOCIPAGHE_PARAMETRI ADD AUTOINC_AL VARCHAR2(1) DEFAULT 'S';

ALTER TABLE T248_PERMESSISINDACALI DROP CONSTRAINT T248_PK;

ALTER TABLE T248_PERMESSISINDACALI ADD CONSTRAINT T248_PK PRIMARY KEY 
 (PROGRESSIVO,DATA,ABBATTE_COMPETENZE,COD_SINDACATO,COD_ORGANISMO,STATO);

ALTER TABLE T240_ORGANIZZAZIONISINDACALI ADD VOCEPAGHE VARCHAR2(6);

CREATE TABLE T435_BADGESERVIZIO (
  PROGRESSIVO NUMBER(8),
  DECORRENZA DATE,
  SCADENZA DATE,
  BADGESERV NUMBER(8),
  CONSTRAINT T435_PK PRIMARY KEY (BADGESERV,DECORRENZA)
  USING INDEX STORAGE (pctincrease 0 initial 16K next 32K)
  TABLESPACE INDICI pctfree 10
)
STORAGE (pctincrease 0 initial 16K next 32K)
TABLESPACE LAVORO pctfree 10 pctused 40;

COMMENT ON COLUMN T435_BADGESERVIZIO.DECORRENZA IS
  'Data ed ora di inizio validita'' dell''abbinamento del badge di servizio al dipendente';
COMMENT ON COLUMN T435_BADGESERVIZIO.SCADENZA IS
  'Data ed ora di fine validita'' dell''abbinamento del badge di servizio al dipendente';

ALTER TABLE T020_ORARI ADD REGOLE_PROFILO VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T240_ORGANIZZAZIONISINDACALI ADD CAUSALE_COMPETENZE VARCHAR2(5);
ALTER TABLE T240_ORGANIZZAZIONISINDACALI ADD CAUSALE_COMPETENZE_NO VARCHAR2(5);

ALTER TABLE MONDOEDP.I071_PERMESSI ADD C700_SALVASELEZIONI VARCHAR2(1) DEFAULT 'S';

CREATE TABLE T180_DATIBLOCCATI (
  PROGRESSIVO NUMBER(8),
  DATA DATE,
  RIEPILOGO VARCHAR2(5),
  STATO VARCHAR2(1) DEFAULT 'C'
) 
  NOPARALLEL TABLESPACE LAVORO
  STORAGE (PCTINCREASE 0 INITIAL 32K NEXT 1M);

ALTER TABLE T180_DATIBLOCCATI ADD CONSTRAINT T180_PK PRIMARY KEY (PROGRESSIVO,DATA,RIEPILOGO,STATO)
USING INDEX TABLESPACE INDICI STORAGE (PCTINCREASE 0 INITIAL 32K NEXT 1M);

COMMENT ON COLUMN T180_DATIBLOCCATI.RIEPILOGO IS
  'T040=Giustificativi, T070=Scheda riepilogativa, T071A=Assestamento T071S=Straordinario, T074=Liquidazione presenze, T134=Liquidazione ore anni prec., T080=Pianificazione, T100=Timbrature, T340=Reperibilita, T410=Accessi mensa, T680=Buoni pasto, T690=Acquisto buoni, T762=Incentivi, T130=Residui saldi, T131=Residui presenze, T264=Residui assenze, T692=Residuo buoni';
COMMENT ON COLUMN T180_DATIBLOCCATI.STATO IS
  'C=Chiuso, A=Aperto';

CREATE TABLE T199_DATACASSA (
  DATA_CASSA DATE
)
  NOPARALLEL TABLESPACE LAVORO
  STORAGE (PCTINCREASE 0 INITIAL 16K NEXT 16K);
