UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.5.4' WHERE AZIENDA = :AZIENDA;

-- PIANTA ORGANICA
ALTER TABLE SG506_PIANTADISTRIBUZIONE DROP CONSTRAINT SG506_FK_SG506;
ALTER TABLE SG509_DETTAGLIOSTAMPA DROP CONSTRAINT SG509_PK CASCADE;
ALTER TABLE SG509_DETTAGLIOSTAMPA ADD CONSTRAINT SG509_PK PRIMARY KEY (CODICE_STAMPA,TIPO_CAMPO,LIVELLO) USING INDEX TABLESPACE INDICI;

-- LOGIN DIPENDENTE
CREATE TABLE MONDOEDP.I060_LOGIN_DIPENDENTE 
(
 AZIENDA VARCHAR2(30),
 MATRICOLA VARCHAR2(8),
 NOME_UTENTE VARCHAR2(30),
 PASSWORD VARCHAR2(20),
 FILTRO_FUNZIONI VARCHAR2(20),
 FILTRO_ANAGRAFE VARCHAR2(20)
)
tablespace LAVORO 
pctfree 10 pctused 40 initrans 1 maxtrans 255 noparallel
storage (initial 32K next 2M minextents 1 pctincrease 0);
ALTER TABLE MONDOEDP.I060_LOGIN_DIPENDENTE 
  ADD CONSTRAINT I060_PK PRIMARY KEY (AZIENDA,MATRICOLA)
  using index tablespace INDICI pctfree 10 initrans 2 maxtrans 255
  storage (initial 32K next 2M minextents 1 pctincrease 0);

-- BADGE DI SERVIZIO
ALTER TABLE MONDOEDP.I101_TIMBIRREGOLARI MODIFY BADGE NUMBER(15);
ALTER TABLE T435_BADGESERVIZIO MODIFY BADGESERV NUMBER(15);

-- PIANIFICAZIONE TURNI
ALTER TABLE T080_PIANIFORARI MODIFY TURNO1 VARCHAR2(2);
ALTER TABLE T080_PIANIFORARI MODIFY TURNO2 VARCHAR2(2);
ALTER TABLE T081_PROVVISORIO MODIFY TURNO1 VARCHAR2(2);
ALTER TABLE T081_PROVVISORIO MODIFY TURNO2 VARCHAR2(2);
ALTER TABLE T611_CICLIGIORNALIERI MODIFY TURNO1 VARCHAR2(2);
ALTER TABLE T611_CICLIGIORNALIERI MODIFY TURNO2 VARCHAR2(2);
ALTER TABLE T630_SPOSTSQUADRA MODIFY TURNO1 VARCHAR2(2);
ALTER TABLE T630_SPOSTSQUADRA MODIFY TURNO2 VARCHAR2(2);
UPDATE T080_PIANIFORARI SET TURNO1 = DECODE(TURNO1,'9','0','5','M','6','A',TURNO1) WHERE TURNO1 IN ('9','5','6');
UPDATE T080_PIANIFORARI SET TURNO2 = DECODE(TURNO2,'9','0','5','M','6','A',TURNO2) WHERE TURNO2 IN ('9','5','6');
UPDATE T081_PROVVISORIO SET TURNO1 = DECODE(TURNO1,'9','0','5','M','6','A',TURNO1) WHERE TURNO1 IN ('9','5','6');
UPDATE T081_PROVVISORIO SET TURNO2 = DECODE(TURNO2,'9','0','5','M','6','A',TURNO2) WHERE TURNO2 IN ('9','5','6');
UPDATE T611_CICLIGIORNALIERI SET TURNO1 = DECODE(TURNO1,'9','0','5','M','6','A',TURNO1) WHERE TURNO1 IN ('9','5','6');
UPDATE T611_CICLIGIORNALIERI SET TURNO2 = DECODE(TURNO2,'9','0','5','M','6','A',TURNO2) WHERE TURNO2 IN ('9','5','6');
UPDATE T630_SPOSTSQUADRA SET TURNO1 = DECODE(TURNO1,'9','0','5','M','6','A',TURNO1) WHERE TURNO1 IN ('9','5','6');
UPDATE T630_SPOSTSQUADRA SET TURNO2 = DECODE(TURNO2,'9','0','5','M','6','A',TURNO2) WHERE TURNO2 IN ('9','5','6');
