CREATE OR REPLACE FUNCTION T100F_GETTIMBRATURELORDE(P_PROG IN INTEGER, P_DATA IN DATE, P_DALLE IN INTEGER, P_ALLE IN INTEGER) 
RETURN INTEGER AS
  CURSOR C1 IS
    SELECT * FROM T100_TIMBRATURE
    WHERE PROGRESSIVO = P_PROG
    AND DATA BETWEEN P_DATA AND P_DATA + 1
    AND FLAG IN ('O','I')
    ORDER BY DATA,ORA;
  RESULT INTEGER;
  TIMB_E INTEGER;
  TIMB_U INTEGER;
BEGIN
  TIMB_E:=-1;
  RESULT:=0;
  FOR T1 IN C1 LOOP
    IF T1.VERSO = 'U' THEN
      IF TIMB_E < 0 THEN
        TIMB_E:=0;
      END IF;
      TIMB_U:=OREMINUTI(TO_CHAR(T1.ORA,'HH24.MI'));
      IF T1.DATA > P_DATA THEN
        TIMB_U:=TIMB_U + 1440;
      END IF;  
      TIMB_E:=GREATEST(TIMB_E,P_DALLE);
      TIMB_U:=LEAST(TIMB_U,P_ALLE);
      RESULT:=RESULT + GREATEST(0,TIMB_U - TIMB_E);
    ELSIF T1.VERSO = 'E' AND T1.DATA = P_DATA THEN
      TIMB_E:=OREMINUTI(TO_CHAR(T1.ORA,'HH24.MI'));
    ELSIF T1.DATA > P_DATA THEN
      EXIT;
    END IF;
  END LOOP;
  RETURN(RESULT);
END T100F_GETTIMBRATURELORDE;
/