CREATE OR REPLACE PROCEDURE ALLINEA_PER_JOB AS
CURSOR CI020_T430 IS
  SELECT TABELLA, COLONNA, VALORE
  FROM   I020_DATI_ALLINEAMENTO
  WHERE  TIPO = 'D'
  AND    TABELLA = 'T430_STORICO'
  ORDER BY TABELLA DESC;
CURSOR CI020_P430 IS
  SELECT TABELLA, COLONNA, VALORE
  FROM   I020_DATI_ALLINEAMENTO
  WHERE  TIPO = 'D'
  AND    TABELLA = 'P430_ANAGRAFICO'
  ORDER BY TABELLA DESC;
CURSORE_DINAMICO_I030       INTEGER;
CURS_I030                   INTEGER;
WDECORRENZE   VARCHAR2(32767);
WCAMPINOTNULL VARCHAR2(32767);
WESPCURREL    VARCHAR2(32767);
WCAMPI_SEL    VARCHAR2(32767);
WTAB_FROM     VARCHAR2(32767);
WCOND_WHERE   VARCHAR2(32767);
ERRORE        VARCHAR2(100);
ORA_JOB       VARCHAR2(5);
--
N_STO_REL     NUMBER;
N_STO_DAT     NUMBER;
ESPRESSIONE   VARCHAR2(32767);
WAND          VARCHAR2(32767);
PROG          NUMBER;
--
MESS          VARCHAR2(4000);
BEGIN
  INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO)
  VALUES (SYSDATE,'INIZIO JOB',T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
  COMMIT;
  BEGIN
    SELECT VALORE
    INTO   ORA_JOB
    FROM   T001_PARAMETRIFUNZIONI
    WHERE  PROGOPERATORE = -1
    AND    PROG = 'A044'
    AND    NOME = 'ORA_JOB';
  EXCEPTION
    WHEN OTHERS THEN
      ORA_JOB:='00.00';
  END;
  -- IL JOB NON VIENE ESEGUITO SE LA DIFFERENZA DI ORARIO CON L'ORA PIANIFICATA È MAGGIORE DI MEZZ'ORA (IN AVANTI O A RITROSO)
  IF ABS(TRUNC(TO_CHAR(SYSDATE,'SSSSS')/60) - OREMINUTI(ORA_JOB)) <= 30 THEN
    -- GESTIONE ANAGRAFICHE T430
    SELECT COUNT(*)
    INTO   N_STO_REL
    FROM   I020_DATI_ALLINEAMENTO   I020,
           I030_RELAZIONI_ANAGRAFE  I030
    WHERE  I020.TIPO = 'R'
    AND    I030.TABELLA = I020.TABELLA
    AND    I030.COLONNA = I020.COLONNA
    AND    I020.TABELLA = 'T430_STORICO';
    SELECT COUNT(*)
    INTO   N_STO_DAT
    FROM   I020_DATI_ALLINEAMENTO
    WHERE  TIPO = 'D'
    AND    TABELLA = 'T430_STORICO';
    INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO)
    VALUES (SYSDATE,'PRESENZE - N_STO_REL: '||N_STO_REL||', N_STO_DAT: '||N_STO_DAT,T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
    COMMIT;
    IF N_STO_REL > 0 OR N_STO_DAT > 0 THEN
      PRE_ALLINEA_PERIODI_STORICI(WCAMPINOTNULL,WESPCURREL,WDECORRENZE,WCAMPI_SEL,WTAB_FROM,WCOND_WHERE);
      INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO)
      VALUES (SYSDATE,'PRESENZE - WESPCURREL: '||SUBSTR(WESPCURREL,1,3900),T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
      COMMIT;
      IF N_STO_REL > 0 THEN
        ESPRESSIONE:='SELECT T030.PROGRESSIVO FROM T030_ANAGRAFICO T030, T430_STORICO T430 WHERE T030.PROGRESSIVO = T430.PROGRESSIVO '||
                     'GROUP BY T030.PROGRESSIVO HAVING MAX(NVL(T430.FINE,TO_DATE(''31123999'',''DDMMYYYY''))) > ADD_MONTHS(TRUNC(SYSDATE),-12)';
      ELSE
        WAND:='';
        FOR RI020_T430 IN CI020_T430 LOOP
          IF RI020_T430.VALORE IS NULL THEN
            WAND:=WAND || SUBSTR(RI020_T430.TABELLA,1,4) || '.' || RI020_T430.COLONNA || ' IS NULL OR ';
          ELSE
            WAND:=WAND || SUBSTR(RI020_T430.TABELLA,1,4) || '.' || RI020_T430.COLONNA || ' = ''' || RI020_T430.VALORE || ''' OR ';
          END IF;
        END LOOP;
        WAND:=RTRIM(LTRIM(SUBSTR(WAND,1,LENGTH(WAND)-3)));
        ESPRESSIONE:='SELECT T030.PROGRESSIVO FROM T030_ANAGRAFICO T030, T430_STORICO T430 WHERE T030.PROGRESSIVO = T430.PROGRESSIVO '||
                     'AND (' || WAND || ') GROUP BY T030.PROGRESSIVO HAVING MAX(NVL(T430.FINE,TO_DATE(''31123999'',''DDMMYYYY''))) > ADD_MONTHS(TRUNC(SYSDATE),-12)';
      END IF;
      MESS:=SUBSTR(ESPRESSIONE,1,3900);
      INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO)
      VALUES (SYSDATE,'PRESENZE - '||MESS,T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
      COMMIT;
      CURSORE_DINAMICO_I030:=DBMS_SQL.OPEN_CURSOR;
      DBMS_SQL.PARSE(CURSORE_DINAMICO_I030,ESPRESSIONE,DBMS_SQL.NATIVE);
      DBMS_SQL.DEFINE_COLUMN(CURSORE_DINAMICO_I030,1,PROG);
      CURS_I030:=DBMS_SQL.EXECUTE(CURSORE_DINAMICO_I030);
      LOOP
        IF DBMS_SQL.FETCH_ROWS(CURSORE_DINAMICO_I030)>0 THEN
          DBMS_SQL.COLUMN_VALUE(CURSORE_DINAMICO_I030, 1, PROG);
          ERRORE:=NULL;
          ALLINEA_PERIODI_STORICI(PROG,1,ERRORE,'N','N','S',WCAMPINOTNULL,WESPCURREL,WDECORRENZE,WCAMPI_SEL,WTAB_FROM,WCOND_WHERE);
        ELSE
          EXIT;
        END IF;
      END LOOP; -- FINE CURSORE_DINAMICO_I030 --
      DBMS_SQL.CLOSE_CURSOR(CURSORE_DINAMICO_I030);
    END IF;
    -- GESTIONE ANAGRAFICHE P430
    SELECT COUNT(*)
    INTO   N_STO_REL
    FROM   I020_DATI_ALLINEAMENTO   I020,
           I030_RELAZIONI_ANAGRAFE  I030
    WHERE  I020.TIPO = 'R'
    AND    I030.TABELLA = I020.TABELLA
    AND    I030.COLONNA = I020.COLONNA
    AND    I020.TABELLA = 'P430_ANAGRAFICO';
    SELECT COUNT(*)
    INTO   N_STO_DAT
    FROM   I020_DATI_ALLINEAMENTO
    WHERE  TIPO = 'D'
    AND    TABELLA = 'P430_ANAGRAFICO';
    INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO) 
    VALUES (SYSDATE,'STIPENDI - N_STO_REL: '||N_STO_REL||', N_STO_DAT: '||N_STO_DAT,T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
    COMMIT;
    IF N_STO_REL > 0 OR N_STO_DAT > 0 THEN
      PRE_ALLINEA_PERIODI_STIPENDI(WCAMPINOTNULL,WESPCURREL,WDECORRENZE,WCAMPI_SEL,WTAB_FROM,WCOND_WHERE);
      INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO)
      VALUES (SYSDATE,'STIPENDI - WESPCURREL: '||SUBSTR(WESPCURREL,1,3900),T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
      COMMIT;
      IF N_STO_REL > 0 THEN
        ESPRESSIONE:='SELECT T030.PROGRESSIVO FROM T030_ANAGRAFICO T030, T430_STORICO T430 WHERE T030.PROGRESSIVO = T430.PROGRESSIVO '||
                     'GROUP BY T030.PROGRESSIVO HAVING MAX(NVL(T430.FINE,TO_DATE(''31123999'',''DDMMYYYY''))) > ADD_MONTHS(TRUNC(SYSDATE),-12)';
      ELSE
        WAND:='';
        FOR RI020_P430 IN CI020_P430 LOOP
          IF RI020_P430.VALORE IS NULL THEN
            WAND:=WAND || SUBSTR(RI020_P430.TABELLA,1,4) || '.' || RI020_P430.COLONNA || ' IS NULL OR ';
          ELSE
            WAND:=WAND || SUBSTR(RI020_P430.TABELLA,1,4) || '.' || RI020_P430.COLONNA || ' = ''' || RI020_P430.VALORE || ''' OR ';
          END IF;
        END LOOP;
        WAND:=RTRIM(LTRIM(SUBSTR(WAND,1,LENGTH(WAND)-3)));
        ESPRESSIONE:='SELECT T030.PROGRESSIVO FROM T030_ANAGRAFICO T030, T430_STORICO T430, P430_ANAGRAFICO P430 WHERE T030.PROGRESSIVO = T430.PROGRESSIVO '||
                     'AND T030.PROGRESSIVO = P430.PROGRESSIVO (+) AND (' || WAND || ') GROUP BY T030.PROGRESSIVO HAVING MAX(NVL(T430.FINE,TO_DATE(''31123999'',''DDMMYYYY''))) > ADD_MONTHS(TRUNC(SYSDATE),-12)';
      END IF;
      MESS:=SUBSTR(ESPRESSIONE,1,3900);
      INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO)
      VALUES (SYSDATE,'STIPENDI - '||MESS,T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
      COMMIT;
      CURSORE_DINAMICO_I030:=DBMS_SQL.OPEN_CURSOR;
      DBMS_SQL.PARSE(CURSORE_DINAMICO_I030,ESPRESSIONE,DBMS_SQL.NATIVE);
      DBMS_SQL.DEFINE_COLUMN(CURSORE_DINAMICO_I030,1,PROG);
      CURS_I030:=DBMS_SQL.EXECUTE(CURSORE_DINAMICO_I030);
      LOOP
        IF DBMS_SQL.FETCH_ROWS(CURSORE_DINAMICO_I030)>0 THEN
          DBMS_SQL.COLUMN_VALUE(CURSORE_DINAMICO_I030, 1, PROG);
          ERRORE:=NULL;
          ALLINEA_PERIODI_STIPENDI(PROG,ERRORE,'N','N','S',WCAMPINOTNULL,WESPCURREL,WDECORRENZE,WCAMPI_SEL,WTAB_FROM,WCOND_WHERE);
        ELSE
          EXIT;
        END IF;
      END LOOP; -- FINE CURSORE_DINAMICO_I030 --
      DBMS_SQL.CLOSE_CURSOR(CURSORE_DINAMICO_I030);
    END IF;
    --
    BEGIN
      DELETE I020_DATI_ALLINEAMENTO
      WHERE TIPO IN ('D','R');
      COMMIT;
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
    END;
  END IF;
  INSERT INTO MONDOEDP.I021_LOG_JOB(DATAORA,MESSAGGIO,AZIENDA,TIPO) 
  VALUES (SYSDATE,'FINE JOB',T000F_GETAZIENDACORRENTE,'ALLINEA_PER_JOB');
  COMMIT;
END;
/

