DECLARE
  CURSOR C1 IS SELECT CODICE,FILTRO,ASSENZE FROM T910_OLD;
  A VARCHAR2(300);
  B VARCHAR2(10);
BEGIN
  FOR T1 IN C1 LOOP
    IF RTRIM(LTRIM(T1.FILTRO)) IS NOT NULL THEN
      INSERT INTO T914_SERBATOIFILTRO 
        (CODICE,ID_SERBATOIO,ESCLUSIVO,FILTRO) 
        VALUES
        (T1.CODICE,0,'N',T1.FILTRO);
      INSERT INTO T914_SERBATOIFILTRO 
        (CODICE,ID_SERBATOIO,ESCLUSIVO,FILTRO) 
        VALUES
        (T1.CODICE,1,'N',T1.FILTRO);
      INSERT INTO T914_SERBATOIFILTRO 
        (CODICE,ID_SERBATOIO,ESCLUSIVO,FILTRO) 
        VALUES
        (T1.CODICE,2,'N',T1.FILTRO);
      INSERT INTO T914_SERBATOIFILTRO 
        (CODICE,ID_SERBATOIO,ESCLUSIVO,FILTRO) 
        VALUES
        (T1.CODICE,3,'N',T1.FILTRO);
      INSERT INTO T914_SERBATOIFILTRO 
        (CODICE,ID_SERBATOIO,ESCLUSIVO,FILTRO) 
        VALUES
        (T1.CODICE,4,'N',T1.FILTRO);
      INSERT INTO T914_SERBATOIFILTRO 
        (CODICE,ID_SERBATOIO,ESCLUSIVO,FILTRO) 
        VALUES
        (T1.CODICE,5,'N',T1.FILTRO);
    END IF;
    A:=T1.ASSENZE;
    WHILE LENGTH(A) > 0 LOOP
      IF INSTR(A,',') > 0 THEN
        B:=SUBSTR(A,1,INSTR(A,',') - 1);
        A:=SUBSTR(A,INSTR(A,',') + 1,300);
      ELSE
        B:=A;
        A:='';
      END IF;
      INSERT INTO T915_CODICISELEZIONATI 
        (CODICE,ID_SERBATOIO,DATO)
        VALUES
        (T1.CODICE,3,B);
    END LOOP;
    COMMIT;
  END LOOP;  
END;
/