SELECT A.ID, A.TIPOGIUST, A.DAL, A.AL, A.NUMEROORE, A.AORE,
       B.ELABORATO, B.TIPOGIUST, B.DAL, B.AL, B.NUMEROORE, B.AORE
FROM T050_RICHIESTEASSENZA A, T050_RICHIESTEASSENZA B
WHERE A.TIPO_RICHIESTA = 'D' 
AND   A.ID_REVOCA IS NOT NULL
AND   B.ID = A.ID_REVOCA
ORDER BY A.ID;

SELECT A.ID, A.TIPOGIUST, A.DAL, A.AL, A.NUMEROORE, A.AORE,
       B.ID, B.ELABORATO, B.TIPOGIUST, B.DAL, B.AL, B.NUMEROORE, B.AORE
FROM T050_RICHIESTEASSENZA A, T050_RICHIESTEASSENZA B
WHERE A.TIPO_RICHIESTA = 'D' 
AND   A.ID_REVOCA IS NOT NULL
AND   B.ID = A.ID_REVOCA
AND   B.ELABORATO = 'E'
AND   A.DAL = B.DAL
AND   A.AL = B.AL
AND   NVL(A.NUMEROORE,'00.00') = NVL(B.NUMEROORE,'00.00')
AND   NVL(A.AORE,'00.00') = NVL(B.AORE,'00.00')
ORDER BY B.ID;

SELECT * FROM T280_MESSAGGIWEB 
WHERE TITOLO = '<A004> ESITO NEGATIVO - Caricamento assenze richieste e autorizzate'
AND   LOG LIKE 'Revoca richiesta causale%'
AND   LOG LIKE '%Giustificativo da cancellare non trovato.';






SELECT COUNT(*) FROM T050_RICHIESTEASSENZA 
WHERE TIPO_RICHIESTA = 'R' AND ELABORATO = 'N'




