ALTER TABLE T070_SCHEDARIEPIL ADD SCOSTNEG VARCHAR2(7);
ALTER TABLE T070_SCHEDARIEPIL ADD RIPCOM VARCHAR2(7);
ALTER TABLE T070_SCHEDARIEPIL ADD ABBRIPCOM VARCHAR2(6);
ALTER TABLE T130_RESIDANNOPREC MODIFY CAUSASSENZACOMP VARCHAR2(7);

CREATE TABLE T025_CONTMENSILI (
  CODICE VARCHAR2(5) NOT NULL,
  DESCRIZIONE VARCHAR2(40),
  CARTELLINO VARCHAR2(1),
  ISTITUTI VARCHAR2(1),
  NOTTEENTRATA VARCHAR2(1),
  CONTEGGIO NUMBER(2),
  SCOSTSETT VARCHAR2(6),
  CONSTRAINT T025_PK PRIMARY KEY (CODICE) USING INDEX TABLESPACE INDICI
)
TABLESPACE LAVORO;

INSERT INTO T025_CONTMENSILI
(CODICE,DESCRIZIONE,CARTELLINO,ISTITUTI,NOTTEENTRATA,CONTEGGIO)
VALUES
('A','STANDARD','M','M','N',4);

ALTER TABLE T430_STORICO ADD TIPORAPPORTO VARCHAR2(5);
ALTER TABLE T430_STORICO ADD PARTTIME VARCHAR2(5);
UPDATE T430_STORICO SET PERSELASTICO = 'A';

UPDATE I500_DATILIBERI SET PROGRESSIVO = PROGRESSIVO + 2;
DELETE FROM T431_DATISTORICI WHERE CODICE >= 40;
INSERT INTO T431_DATISTORICI VALUES (40,'Tipo rapporto');
INSERT INTO T431_DATISTORICI VALUES (41,'Part time');

DELETE FROM T033_LAYOUT WHERE NUMCOMP <=49;
UPDATE T033_LAYOUT SET NUMCOMP = NUMCOMP + 2;

CREATE TABLE T450_TIPORAPPORTO (
  CODICE VARCHAR2(5) NOT NULL,
  DESCRIZIONE VARCHAR2(40),
  TIPO VARCHAR2(1),
  CONSTRAINT T450_PK PRIMARY KEY (CODICE) USING INDEX TABLESPACE INDICI
) 
  TABLESPACE LAVORO;

CREATE TABLE T460_PARTTIME (
  CODICE VARCHAR2(5) NOT NULL,
  DESCRIZIONE VARCHAR2(40),
  TIPO VARCHAR2(1),
  PIANTA NUMBER,
  CONSTRAINT T460_PK PRIMARY KEY (CODICE) USING INDEX TABLESPACE INDICI
) 
  TABLESPACE LAVORO;