ALTER TABLE T262_PROFASSANN ADD PROPORZIONE VARCHAR2(1);
ALTER TABLE T262_PROFASSANN ADD SOMMA VARCHAR2(1);
ALTER TABLE T262_PROFASSANN ADD MG VARCHAR2(1);
ALTER TABLE T262_PROFASSANN ADD ARRFAV VARCHAR2(1);
ALTER TABLE T262_PROFASSANN ADD DATARES DATE;
UPDATE T262_PROFASSANN SET
  PROPORZIONE = '1',
  SOMMA = 'S',
  MG = 'S',
  ARRFAV = 'F';

ALTER TABLE T263_PROFASSIND ADD DATARES DATE;
