ALTER TABLE T020_ORARI ADD INTERSEZIONEMENSA VARCHAR2(1);
UPDATE T020_ORARI SET INTERSEZIONEMENSA  = 'N';

ALTER TABLE T073_SCHEDACAUSPRES ADD COMPENSABILE VARCHAR2(7);
ALTER TABLE T074_CAUSPRESFASCE ADD LIQUIDATO VARCHAR2(7);

ALTER TABLE T220_PROFILIORARI ADD TIMBNONAPPOGGIATE VARCHAR2(1);
UPDATE T220_PROFILIORARI SET TIMBNONAPPOGGIATE  = 'N';

ALTER TABLE T275_CAUPRESENZE ADD VOCEPAGHELIQ1 VARCHAR2(6);
ALTER TABLE T275_CAUPRESENZE ADD VOCEPAGHELIQ2 VARCHAR2(6);
ALTER TABLE T275_CAUPRESENZE ADD VOCEPAGHELIQ3 VARCHAR2(6);
ALTER TABLE T275_CAUPRESENZE ADD VOCEPAGHELIQ4 VARCHAR2(6);

UPDATE T190_INTPAGHE SET F160 = 'N';

ALTER TABLE T265_CAUASSENZE ADD TIPORECUPERO VARCHAR2(2);
UPDATE T265_CAUASSENZE SET TIPORECUPERO = DECODE(INFLUCONT,'F','PC','E','AC','0');
UPDATE T265_CAUASSENZE SET INFLUCONT = 'A' WHERE INFLUCONT IN ('E','F');
ALTER TABLE T070_SCHEDARIEPIL ADD RECLIQCORR VARCHAR2(6);
ALTER TABLE T070_SCHEDARIEPIL ADD RECLIQPREC VARCHAR2(6);

ALTER TABLE T025_CONTMENSILI ADD LIQUIDDISTRIBUITA VARCHAR2(1);
UPDATE T025_CONTMENSILI SET LIQUIDDISTRIBUITA = 'S';
UPDATE T025_CONTMENSILI SET LIQUIDDISTRIBUITA = 'N' WHERE MESISALDOPREC > 0;

