ALTER TABLE T195_VOCIVARIABILI ADD DAL DATE;
ALTER TABLE T195_VOCIVARIABILI ADD AL DATE;
ALTER TABLE T195_VOCIVARIABILI ADD OPERAZIONE VARCHAR2(1) DEFAULT 'I';
ALTER TABLE T195_VOCIVARIABILI DROP CONSTRAINT T195_PK;
UPDATE T195_VOCIVARIABILI SET DAL = DATARIF;
alter table T195_VOCIVARIABILI
  add constraint T195_PK primary key (PROGRESSIVO,DATARIF,VOCEPAGHE,DAL,OPERAZIONE)
  using index 
  tablespace INDICI
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 2M
    next 2M
    minextents 1
    pctincrease 0
  );
  
ALTER TABLE T195_BACKUP ADD DAL DATE;
ALTER TABLE T195_BACKUP ADD AL DATE;
ALTER TABLE T195_BACKUP ADD OPERAZIONE VARCHAR2(1) DEFAULT 'I';

ALTER TABLE T191_PARPAGHE ADD SALVATAGGIO_AUTOMATICO VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T670_REGOLEBUONI ADD INTERVALLOMIN VARCHAR2(5) DEFAULT '00.00';
ALTER TABLE T670_REGOLEBUONI ADD INTERVALLOMAX VARCHAR2(5) DEFAULT '23.59';

ALTER TABLE T375_ACCESSIMENSA ADD RILEVATORE VARCHAR2(2);
