ALTER TABLE T262_PROFASSANN ADD PROPGGMM VARCHAR2(1) DEFAULT 'G';
ALTER TABLE T030_ANAGRAFICO ADD RAPPORTI_UNITI VARCHAR2(1) DEFAULT 'N';
UPDATE T030_ANAGRAFICO SET RAPPORTI_UNITI = 'S';

ALTER TABLE T740_LIQUIDAZIONEPROP ADD ARROTONDAMENTO NUMBER(3);
ALTER TABLE T800_CAMPILIMITI ADD TRONCA_ECCEDENZE VARCHAR2(1) DEFAULT 'S';