update Mondoedp.I090_ENTI set VERSIONEDB = '8.2',PATCHDB = 0 where UTENTE = (select UTENTE from MONDOEDP.I090_ENTI where AZIENDA = :AZIENDA);

ALTER TABLE SG735_PUNTEGGIFASCE_INCENTIVI ADD TIPOLOGIA VARCHAR2(1) DEFAULT 'V';
comment on column SG735_PUNTEGGIFASCE_INCENTIVI.TIPOLOGIA is 'Tipo di gestione (V=valutazioni, I=incentivi)';
ALTER TABLE SG735_PUNTEGGIFASCE_INCENTIVI ADD CODQUOTA VARCHAR2(5);
comment on column SG735_PUNTEGGIFASCE_INCENTIVI.CODQUOTA is 'Codice quota incentivi di riferimento';
ALTER TABLE SG735_PUNTEGGIFASCE_INCENTIVI ADD FLESSIBILITA VARCHAR2(1) DEFAULT '*';
comment on column SG735_PUNTEGGIFASCE_INCENTIVI.FLESSIBILITA is 'Tipo di flessibilità (S=flessibile, N=non flessibile, *=entrambi)';
alter table SG735_PUNTEGGIFASCE_INCENTIVI drop constraint SG735_PK;
drop index SG735_PK/*--NOLOG--*/;
UPDATE SG735_PUNTEGGIFASCE_INCENTIVI SET TIPOLOGIA = 'V';
UPDATE SG735_PUNTEGGIFASCE_INCENTIVI SET FLESSIBILITA = '*';
UPDATE SG735_PUNTEGGIFASCE_INCENTIVI SET CODQUOTA = (SELECT CODICE FROM T765_TIPOQUOTE
WHERE TIPOQUOTA IN ('I','V','C') AND ROWNUM = 1);
alter table SG735_PUNTEGGIFASCE_INCENTIVI
  add constraint SG735_PK primary key (TIPOLOGIA, CODQUOTA, FLESSIBILITA, DECORRENZA, PUNTEGGIO_DA, PUNTEGGIO_A)
  using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);

UPDATE t480_comuni t SET T.CITTA='LONATO DEL GARDA', T.CODCATASTALE='M312'
WHERE T.CODICE='017092';
UPDATE p258_addizionaliirpef t SET T.COD_ENTE='M312' WHERE T.TIPO_ADDIZIONALE='C' AND T.COD_ENTE='E667';
UPDATE t480_comuni t SET T.CITTA='CANOSSA' WHERE T.CODICE='035018';

declare
  i integer;
begin
  select COUNT(*) into i from P441_CEDOLINO;
  if i > 0 then
    select COUNT(*) into i from P250_VOCIAGGIUNTIVE t where T.COD_CONTRATTO ='EDP' AND T.NOME_VOCEAGGIUNTIVA = 'INCARICO';
    if i > 0 then

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR015-006-2006'',''Dirigente ruolo sanitario incarico lett. c) con struttura complessa (dec. 2006)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR015-006-2006'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'DR015-006-2006',
             DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2005',TO_DATE('01012006','DDMMYYYY'),DECORRENZA),
             'Dir. ruolo sanitario lett. c) con S.C. (dec. 2006)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',574.43,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2006',1.81,'2007',67.04,'2009',89.12)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2005' AND (TO_CHAR(P252.DECORRENZA,'YYYY')>'2005' OR P252.COD_VOCE='00212')
      AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='DR015-006-2006');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR070-074-2007'',''Dirigente ruolo tecnico equiparato con struttura complessa (dec. 2007)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR070-074-2007'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'DR070-074-2007', DECORRENZA, 'Dir. ruolo tecnico equiparato con S.C. (dec. 2007)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',850.38,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2007',70.40,'2009',130.80)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-006-2007' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='DR070-074-2007');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR020-006-2005'',''Dirigente ruolo sanitario equiparato con struttura complessa (dec. 2005)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR020-006-2005'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'DR020-006-2005', DECORRENZA, 'Dir. ruolo sanitario equiparato con S.C. (dec. 2005)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',550.87,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2005',70.11,'2006',71.03,'2007',136.26,'2009',159.91)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2005' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='DR020-006-2005');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV025-016-2008'',''Dirigente medico incarico lett. c) con struttura complessa area territorio (dec. 2008)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV025-016-2008'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV025-016-2008', DECORRENZA, 'Dir. medico lett. c) con S.C. territorio (dec. 2008)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',601.09,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2009',40.94)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2008' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV025-016-2008');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV025-011-2004'',''Dirigente medico incarico lett. c) con struttura complessa area chirurgica (dec. 2004)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV025-011-2004'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV025-011-2004', DECORRENZA, 'Dir. medico lett. c) con S.C. chirurgica (dec. 2004)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',485.18,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2004',47.00,'2005',105.14,'2006',115.60,'2007',290.70,'2009',331.64)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV020-006-2004' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV025-011-2004');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-016-2010'',''Dirigente medico equiparato con struttura complessa area territorio (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-016-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV030-016-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico equiparato con S.C. territorio (dec. 2010-2012)'',
        ''00212'', ''BASE'', 736.05, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV030-016-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-025-2010'',''Dirigente medico equiparato con incarico lett. c) (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-025-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV030-025-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico equiparato con lett. c) (dec. 2010-2012)'',
        ''00212'', ''BASE'', 94.02, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV030-025-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV120-106-2005'',''Dirigente veterinario equiparato con struttura complessa (dec. 2005)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV120-106-2005'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV120-106-2005', DECORRENZA, 'Dir. veterinario equiparato con S.C. (dec. 2005)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',417.63,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2005',82.77,'2006',97.67,'2007',272.77,'2009',318.41)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2005' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV120-106-2005');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV020-011-2005'',''Dirigente medico ex modulo con struttura complessa area chirurgica (dec. 2005)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV020-011-2005'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV020-011-2005', DECORRENZA, 'Dir. medico ex modulo con S.C. chirurgica (dec. 2005)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',252.09,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2005',58.14,'2006',68.60,'2007',155.60,'2009',177.12)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2005' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV020-011-2005');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-025-2010'',''Dirigente medico equiparato con incarico lett. c) (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-025-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV030-025-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico equiparato con lett. c) (dec. 2010-2012)'',
        ''00212'', ''BASE'', 94.02, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV030-025-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-025-2008'',''Dirigente medico equiparato con incarico lett. c) (dec. 2008)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-025-2008'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV030-025-2008', DECORRENZA, 'Dir. medico equiparato con lett. c) (dec. 2008)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',89.31,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2009',4.71)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2008' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV030-025-2008');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR072-073-2010'',''Dirigente ruolo tecnico incarico lett. c) con struttura semplice (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR072-073-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''DR072-073-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. ruolo tecnico lett. c) con S.S. (dec. 2010-2012)'',
        ''00212'', ''BASE'', 254.52, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''DR072-073-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR065-050-2005'',''Dirigente ruolo amministrativo equiparato con struttura complessa (dec. 2005)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR065-050-2005'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'DR065-050-2005', DECORRENZA, 'Dir. ruolo amministr. equiparato con S.C. (dec. 2005)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',752.88,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2005',33.50,'2006',39.85,'2007',109.04,'2009',162.48)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2005' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='DR065-050-2005');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR020-010-2005'',''Dirigente ruolo sanitario equiparato con struttura semplice (dec. 2005)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR020-010-2005'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'DR020-010-2005', DECORRENZA, 'Dir. ruolo sanitario equiparato con S.S. (dec. 2005)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',222.08,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2005',24.68,'2006',23.79,'2007',46.46,'2009',55.71)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2005' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='DR020-010-2005');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-016-2010-S2002'',''Dirigente medico equiparato con struttura complessa area territorio (dec. 2010-2012) - semplice (dec. 2002)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-016-2010-S2002'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV030-016-2010-S2002', DECORRENZA, 'Dir. medico equiparato con S.C. territorio (dec. 2010-2012) - S.S. (dec. 2002)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',482.30,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2010',253.75)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-011-2010-S2002' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV030-016-2010-S2002');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV020-011-2010'',''Dirigente medico ex modulo con struttura complessa area chirurgica (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV020-011-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV020-011-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico ex modulo con S.C. chirurgica (dec. 2010-2012)'',
        ''00212'', ''BASE'', 429.21, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV020-011-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV025-006-2008'',''Dirigente medico incarico lett. c) con struttura complessa area medicina (dec. 2008)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV025-006-2008'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV025-006-2008', DECORRENZA, 'Dir. medico lett. c) con S.C. medicina (dec. 2008)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',658.83,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2009',40.94)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2008' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV025-006-2008');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-011-2010'',''Dirigente medico equiparato con struttura complessa area chirurgica (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-011-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV030-011-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico equiparato con S.C. chirurgica (dec. 2010-2012)'',
        ''00212'', ''BASE'', 910.84, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV030-011-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV115-106-2010'',''Dirigente veterinario incarico lett. c) con struttura complessa (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV115-106-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV115-106-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. veterinario lett. c) con S.C. (dec. 2010-2012)'',
        ''00212'', ''BASE'', 642.02, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV115-106-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''DR070-073-2010'',''Dirigente ruolo tecnico equiparato con struttura semplice (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''DR070-073-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''DR070-073-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. ruolo tecnico equiparato con S.S. (dec. 2010-2012)'',
        ''00212'', ''BASE'', 296.22, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''DR070-073-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV120-106-2008'',''Dirigente veterinario equiparato con struttura complessa (dec. 2008)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV120-106-2008'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV120-106-2008', DECORRENZA, 'Dir. veterinario equiparato con S.C. (dec. 2008)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',690.4,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2009',45.64)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2008' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV120-106-2008');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV120-106-2007'',''Dirigente veterinario equiparato con struttura complessa (dec. 2007)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV120-106-2007'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV120-106-2007', DECORRENZA, 'Dir. veterinario equiparato con S.C. (dec. 2007)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',515.3,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2007',175.1,'2009',220.74)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-006-2007' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV120-106-2007');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV030-016-2007'',''Dirigente medico equiparato con struttura complessa area territorio (dec. 2007)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV030-016-2007'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV030-016-2007', DECORRENZA, 'Dir. medico equiparato con S.C. territorio (dec. 2007)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',515.3,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2007',175.1,'2009',220.75)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-006-2007' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV030-016-2007');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV025-006-2005'',''Dirigente medico incarico lett. c) con struttura complessa area medicina (dec. 2005)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV025-006-2005'')';
      INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI
      SELECT COD_CONTRATTO, NOME_VOCEAGGIUNTIVA, 'MV025-006-2005', DECORRENZA, 'Dir. medico lett. c) con S.C. medicina (dec. 2005)', COD_VOCE, COD_VOCE_SPECIALE,
             DECODE(P252.COD_VOCE,'00212',431.17,
                    DECODE(TO_CHAR(P252.DECORRENZA,'YYYY'),'2005',44.55,'2006',52.57,'2007',227.66,'2009',268.6)) IMPORTO,
             EROGAZIONE_MESI, DECORRENZA_FINE, COD_VALUTA_INIZ
      FROM P252_VOCIAGGIUNTIVEIMPORTI P252
      WHERE P252.COD_CONTRATTO='EDP' AND P252.NOME_VOCEAGGIUNTIVA='INCARICO'
      AND P252.CODICE='MV030-020-2005' AND NOT EXISTS
                  (SELECT 'X' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO='EDP'
                  AND T.NOME_VOCEAGGIUNTIVA='INCARICO' AND T.CODICE='MV025-006-2005');

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV025-006-2010'',''Dirigente medico incarico lett. c) con struttura complessa area medicina (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV025-006-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV025-006-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico lett. c) con S.C. medicina (dec. 2010-2012)'',
        ''00212'', ''BASE'', 699.77, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV025-006-2010'')';

      EXECUTE IMMEDIATE 'INSERT INTO I501INCARICO SELECT ''MV025-011-2010'',''Dirigente medico incarico lett. c) con struttura complessa area chirurgica (dec. 2010-2012)'' FROM DUAL WHERE NOT EXISTS (SELECT ''X'' FROM I501INCARICO T WHERE T.CODICE=''MV025-011-2010'')';
      EXECUTE IMMEDIATE 'INSERT INTO P252_VOCIAGGIUNTIVEIMPORTI SELECT ''EDP'', ''INCARICO'', ''MV025-011-2010'', TO_DATE(''01012010'',''DDMMYYYY''),
        ''Dir. medico lett. c) con S.C. chirurgica (dec. 2010-2012)'',
        ''00212'', ''BASE'', 816.82, ''SSSSSSSSSSSS'', TO_DATE(''31123999'',''DDMMYYYY''), ''''
           FROM DUAL WHERE NOT EXISTS
            (SELECT ''X'' FROM P252_VOCIAGGIUNTIVEIMPORTI T WHERE T.COD_CONTRATTO=''EDP''
            AND T.NOME_VOCEAGGIUNTIVA=''INCARICO'' AND T.CODICE=''MV025-011-2010'')';

    end if;
  end if;
end;
/

alter table T255_TIPOACCORPCAUSALI add TIPO varchar2(5) DEFAULT 'ALTRO';
comment on column T255_TIPOACCORPCAUSALI.TIPO is 'WEB=usato in richieste assenze';

alter table MONDOEDP.I005_MSGINFO add HOSTNAME varchar2(24);
alter table MONDOEDP.I005_MSGINFO add HOSTIPADDRESS varchar2(39);

comment on column MONDOEDP.I005_MSGINFO.HOSTNAME 
  is 'Hostname della macchina che ha eseguito l''elaborazione';
comment on column MONDOEDP.I005_MSGINFO.HOSTIPADDRESS 
  is 'Indirizzo IP della macchina che ha eseguito l''elaborazione';  

update T260_RAGGRASSENZE T260 set CONTASOLARE = 'N' where not exists (select 'X' from T265_CAUASSENZE where CODRAGGR = T260.CODICE and TIPOCUMULO = 'A') and CONTASOLARE = 'S';

alter table T263_PROFASSIND add DAL date;
alter table T263_PROFASSIND add AL date;
delete from T263_PROFASSIND where ANNO < 1 or ANNO > 9999;
update T263_PROFASSIND set DAL = to_date('0101'||lpad(substr(ANNO,1,4),4,'0'),'ddmmyyyy');
update T263_PROFASSIND set AL = to_date('3112'||lpad(substr(ANNO,1,4),4,'0'),'ddmmyyyy');
alter table T263_PROFASSIND drop primary key;
drop index T263_PK;
alter table T263_PROFASSIND add constraint T263_PK primary key (PROGRESSIVO,DAL, CODRAGGR) using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);
alter table T263_PROFASSIND modify ANNO null;


UPDATE t480_comuni t SET T.CITTA='GAMBASSI TERME' WHERE T.CODCATASTALE='D895';
UPDATE t480_comuni t SET T.CITTA='POJANA MAGGIORE' WHERE T.CODCATASTALE='G776';

ALTER TABLE T047_VISITEFISCALI ADD TIPO_ESENZIONE VARCHAR2(50);
ALTER TABLE T047_VISITEFISCALI ADD DATA_ESENZIONE DATE;
ALTER TABLE T047_VISITEFISCALI ADD OPERATORE VARCHAR2(20);
comment on column T047_VISITEFISCALI.TIPO_ESENZIONE is 'Tipo di esenzione applicata';
comment on column T047_VISITEFISCALI.DATA_ESENZIONE is 'Data in cui è stata applicata l''esenzione';
comment on column T047_VISITEFISCALI.OPERATORE is 'Operatore che ha applicato l''esenzione';

alter table T050_RICHIESTEASSENZA add AUTORIZZ_AUTOMATICA varchar2(1);
comment on column T050_RICHIESTEASSENZA.AUTORIZZ_AUTOMATICA is 'S=la richiesta è stata autorizzata automaticamente';
alter table T105_RICHIESTETIMBRATURE add AUTORIZZ_AUTOMATICA varchar2(1);
comment on column T105_RICHIESTETIMBRATURE.AUTORIZZ_AUTOMATICA is 'S=la richiesta è stata autorizzata automaticamente';

alter table T265_CAUASSENZE add AUTORIZZ_AUTOMATICA_WEB varchar2(1) default 'N';
comment on column T265_CAUASSENZE.AUTORIZZ_AUTOMATICA_WEB is 'S=la richiesta viene automaticamente autorizzata sulla T050';
alter table T275_CAUPRESENZE add AUTORIZZ_AUTOMATICA_WEB varchar2(1) default 'N';
comment on column T275_CAUPRESENZE.AUTORIZZ_AUTOMATICA_WEB is 'S=la richiesta viene automaticamente autorizzata sulla T105';

alter table P500_CUDSETUP add CODICE_COMPARTO_DMA VARCHAR2(2);
alter table P500_CUDSETUP add CODICE_SOTTOCOMPARTO_DMA VARCHAR2(4);
comment on column P500_CUDSETUP.CODICE_COMPARTO_DMA
  is 'Codice comparto dei dipendenti per modello D.M.A.';
comment on column P500_CUDSETUP.CODICE_SOTTOCOMPARTO_DMA
  is 'Codice sottocomparto dei dipendenti per modello D.M.A.';
update P500_CUDSETUP set CODICE_COMPARTO_DMA = '01';
update P500_CUDSETUP set CODICE_SOTTOCOMPARTO_DMA = '00';

--
-- Nuova tabella fondi previdenza complementare
--
create table P026_FONDIPREVCOMPL
(
  COD_FPC                      VARCHAR2(10) not null,
  DECORRENZA                   DATE not null,
  DECORRENZA_FINE              DATE,
  DESCRIZIONE                  VARCHAR2(100),
  COD_INPDAP_FPC               VARCHAR2(5) not null,
  COD_INPDAPREGIMEFINESERV     VARCHAR2(1) not null,
  PERC_DIPENDENTE              NUMBER default 1 not null,
  PERC_ENTE                    NUMBER default 1 not null,
  PERC_TFR_FPC                 NUMBER not null,
  PERC_MAX_DIP_DEDUZ_IRPEF     NUMBER,
  IMPORTO_MAX_ANNO_DEDUZ_IRPEF NUMBER,
  PERC_MAX_REDDITO_DEDUZ_IRPEF NUMBER
)
tablespace LAVORO storage (initial 256K next 256K pctincrease 0);

comment on column P026_FONDIPREVCOMPL.COD_FPC
  is 'Codice interno fondo previdenza complementare';
comment on column P026_FONDIPREVCOMPL.COD_INPDAP_FPC
  is 'Codice fondo previdenza complementare per flusso DMA';
comment on column P026_FONDIPREVCOMPL.COD_INPDAPREGIMEFINESERV
  is 'Codice regime fine servizio per flusso DMA';
comment on column P026_FONDIPREVCOMPL.PERC_DIPENDENTE
  is 'Percentuale base carico dipendente contribuzione al fondo previdenza complementare';
comment on column P026_FONDIPREVCOMPL.PERC_ENTE
  is 'Percentuale carico ente contribuzione al fondo previdenza complementare';
comment on column P026_FONDIPREVCOMPL.PERC_TFR_FPC
  is 'Percentuale TFR destinato al fondo previdenza complementare';
comment on column P026_FONDIPREVCOMPL.PERC_MAX_DIP_DEDUZ_IRPEF
  is 'Percentuale massima carico dipendente deducibile dall''imponibile IRPEF (se vuota nessun limite percentuale)';
comment on column P026_FONDIPREVCOMPL.IMPORTO_MAX_ANNO_DEDUZ_IRPEF
  is 'Importo massimo annuo deducibile dall''imponibile IRPEF (se vuoto nessun limite massimo)';
comment on column P026_FONDIPREVCOMPL.PERC_MAX_REDDITO_DEDUZ_IRPEF
  is 'Percentuale massima reddito complessivo deducibile dall''imponibile IRPEF (se vuota nessun limite percentuale)';
-- Create/Recreate primary, unique and foreign key constraints 
alter table P026_FONDIPREVCOMPL
  add constraint P026_PK primary key (COD_FPC, DECORRENZA)
  using index 
  tablespace INDICI storage (initial 256K next 256K pctincrease 0);

--
-- Popolamento tabella fondi previdenza complementare
--
insert into P026_FONDIPREVCOMPL (COD_FPC, DECORRENZA, DECORRENZA_FINE, DESCRIZIONE, COD_INPDAP_FPC, COD_INPDAPREGIMEFINESERV, PERC_DIPENDENTE, PERC_ENTE, PERC_TFR_FPC, PERC_MAX_DIP_DEDUZ_IRPEF, IMPORTO_MAX_ANNO_DEDUZ_IRPEF, PERC_MAX_REDDITO_DEDUZ_IRPEF)
values ('2142OPT', to_date('01-01-1900', 'dd-mm-yyyy'), to_date('31-12-3999', 'dd-mm-yyyy'), 'Fopadiva dipendenti optanti (ex TFS)', '2142', '2', 1, 1, 2, 3, 5164.57, 12);
insert into P026_FONDIPREVCOMPL (COD_FPC, DECORRENZA, DECORRENZA_FINE, DESCRIZIONE, COD_INPDAP_FPC, COD_INPDAPREGIMEFINESERV, PERC_DIPENDENTE, PERC_ENTE, PERC_TFR_FPC, PERC_MAX_DIP_DEDUZ_IRPEF, IMPORTO_MAX_ANNO_DEDUZ_IRPEF, PERC_MAX_REDDITO_DEDUZ_IRPEF)
values ('2142TFR', to_date('01-01-1900', 'dd-mm-yyyy'), to_date('31-12-3999', 'dd-mm-yyyy'), 'Fopadiva dipendenti TFR', '2142', '1', 1, 1, 6.91, null, 5164.57, 12);
insert into P026_FONDIPREVCOMPL (COD_FPC, DECORRENZA, DECORRENZA_FINE, DESCRIZIONE, COD_INPDAP_FPC, COD_INPDAPREGIMEFINESERV, PERC_DIPENDENTE, PERC_ENTE, PERC_TFR_FPC, PERC_MAX_DIP_DEDUZ_IRPEF, IMPORTO_MAX_ANNO_DEDUZ_IRPEF, PERC_MAX_REDDITO_DEDUZ_IRPEF)
values ('2142TFS', to_date('01-01-1900', 'dd-mm-yyyy'), to_date('31-12-3999', 'dd-mm-yyyy'), 'Fopadiva dipendenti TFS (lavoratori della Regione Valle d’Aosta ex Fondo cessazione servizio)', '2142', '3', 1, 1, 0, null, 5164.57, 12);

--
-- Nuove colonne anagrafica stipendiale
--
alter table P430_ANAGRAFICO add COD_FPC VARCHAR2(10);
alter table P430_ANAGRAFICO add DATA_DOMANDA_FPC DATE;
alter table P430_ANAGRAFICO add PERC_TOT_DIP_FPC NUMBER;
alter table P430_ANAGRAFICO add DATA_SOSP_CESS_FPC DATE;
alter table P430_ANAGRAFICO add COD_INPDAPMOTIVOSOSP_FPC VARCHAR2(5);
alter table P430_ANAGRAFICO add COD_INPDAPTIPOCESS_FPC VARCHAR2(5);
comment on column P430_ANAGRAFICO.COD_FPC
  is 'Codice fondo previdenza complementare';
comment on column P430_ANAGRAFICO.DATA_DOMANDA_FPC
  is 'Data sottoscrizione domanda al fondo previdenza complementare';
comment on column P430_ANAGRAFICO.PERC_TOT_DIP_FPC
  is 'Percentuale totale carico dipendente contribuzione al fondo previdenza complementare';
comment on column P430_ANAGRAFICO.DATA_SOSP_CESS_FPC
  is 'Data sospensione o cessazione della contribuzione al fondo previdenza complementare';
comment on column P430_ANAGRAFICO.COD_INPDAPMOTIVOSOSP_FPC
  is 'Codice motivo sospensione della contribuzione al fondo previdenza complementare per flusso DMA';
comment on column P430_ANAGRAFICO.COD_INPDAPTIPOCESS_FPC
  is 'Codice tipo cessazione della contribuzione al fondo previdenza complementare per flusso DMA';

--
-- Nuovi codici per INPDAP D.M.A. quadro E1
--
DELETE P002_TABANNUALI T WHERE T.COD_TABANNUALE IN ('IPMSOSPFPC','IPCCESSFPC');

insert into p002_tabannuali
  (cod_tabannuale, descrizione, modificabile)
values
  ('IPMSOSPFPC', 'Motivo sospensione della contribuzione al fondo previdenza complementare INPDAP D.M.A.', 'N');

insert into p002_tabannuali
  (cod_tabannuale, descrizione, modificabile)
values
  ('IPCCESSFPC', 'Motivo cessazione della contribuzione al fondo previdenza complementare INPDAP D.M.A.', 'N');

DELETE P004_CODICITABANNUALI T WHERE T.COD_TABANNUALE IN ('IPMSOSPFPC','IPCCESSFPC');

INSERT INTO P004_CODICITABANNUALI
select 'IPMSOSPFPC', '1', anno, 'Per sospensione del rapporto di lavoro senza diritto alla corresponsione della retribuzione'
from p004_codicitabannuali t 
where t.cod_tabannuale='IPCAUSCESS' and t.cod_codicitabannuali='1';
INSERT INTO P004_CODICITABANNUALI
select 'IPMSOSPFPC', '2', anno, 'Per richiesta del lavoratore, quando la contribuzione spetterebbe anche in caso di mancata prestazione di lavoro dovuta a malattia, infortunio, assenza obbligatoria o facoltativa per maternita'''
from p004_codicitabannuali t 
where t.cod_tabannuale='IPCAUSCESS' and t.cod_codicitabannuali='1';
INSERT INTO P004_CODICITABANNUALI
select 'IPMSOSPFPC', '3', anno, 'Per richiesta, senza causale specifica'
from p004_codicitabannuali t 
where t.cod_tabannuale='IPCAUSCESS' and t.cod_codicitabannuali='1';
INSERT INTO P004_CODICITABANNUALI
select 'IPCCESSFPC', '1', anno, 'Per trasferimento ad altro fondo'
from p004_codicitabannuali t 
where t.cod_tabannuale='IPCAUSCESS' and t.cod_codicitabannuali='1';
INSERT INTO P004_CODICITABANNUALI
select 'IPCCESSFPC', '2', anno, 'Per cessazione del servizio'
from p004_codicitabannuali t 
where t.cod_tabannuale='IPCAUSCESS' and t.cod_codicitabannuali='1';

alter table T767_INCQUANTGRUPPO modify PAG1_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG2_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG3_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG4_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG5_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG6_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG7_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG8_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG9_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG10_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG11_PERC default 0;
alter table T767_INCQUANTGRUPPO modify PAG12_PERC default 0;

alter table T825_LIQUIDINDANNUO add LIQUIDABILE_TEORICO varchar2(7);
comment on column T025_CONTMENSILI.ITER_AUTORIZZATIVO_STR is '0=No, 1=Banca ore, 2=Straordinario annuo';

insert into MONDOEDP.I091_DATIENTE select AZIENDA,'C90_T050REVOCHE', 'N' from MONDOEDP.I090_ENTI/*--NOLOG--*/;

create table SG095_PROVVEDIMENTODETT
( PROGRESSIVO NUMBER(38,2) not null,
  NOMECAMPO   VARCHAR2(20) not null,
  DATADECOR   DATE not null,
  DATAREGISTR DATE not null,
  NUMERO      VARCHAR2(4) not null,
  VALORE_PREC VARCHAR2(50),
  VALORE_SUCC VARCHAR2(50))
tablespace LAVORO storage (initial 256K next 256K pctincrease 0);

comment on column SG095_PROVVEDIMENTODETT.NUMERO
  is 'Codice interno del dato da dettagliare';
comment on column SG095_PROVVEDIMENTODETT.VALORE_PREC
  is 'Valore del dato da dettagliare il giorno prima della decorrenza';
comment on column SG095_PROVVEDIMENTODETT.VALORE_SUCC
  is 'Valore del dato da dettagliare il giorno della decorrenza';

alter table SG095_PROVVEDIMENTODETT
  add constraint SG095_PK primary key (PROGRESSIVO, NOMECAMPO, DATADECOR, DATAREGISTR, NUMERO)
  using index 
tablespace INDICI storage (initial 256K next 256K pctincrease 0);

alter table SG104_TIPOMOTIVAZIONI add DESCRIZIONE_AGG VARCHAR2(200);
alter table SG104_TIPOMOTIVAZIONI add STAMPA_FAMILIARI VARCHAR2(1) default 'S' not null;
alter table SG104_TIPOMOTIVAZIONI add ELENCO_NUMERI_PREC VARCHAR2(500);
alter table SG104_TIPOMOTIVAZIONI add ELENCO_NUMERI_SUCC VARCHAR2(500);

comment on column SG104_TIPOMOTIVAZIONI.DESCRIZIONE_AGG
  is 'Descrizione aggiuntiva';
comment on column SG104_TIPOMOTIVAZIONI.STAMPA_FAMILIARI
  is 'Stampa dei familiari (S/N)';
comment on column SG104_TIPOMOTIVAZIONI.ELENCO_NUMERI_PREC
  is 'Elenco codici interni dei dati da dettagliare nella colonna ''precedente'' del provvedimento';
comment on column SG104_TIPOMOTIVAZIONI.ELENCO_NUMERI_SUCC
  is 'Elenco codici interni dei dati da dettagliare nella colonna ''successivo'' del provvedimento';

omment on column T326_RICHIESTESTR_SPEZ.TIPO
  is 'Tipologia dello spezzone: E = Entrata, U = Uscita, T = generico';

alter table T326_RICHIESTESTR_SPEZ drop constraint T326_PK CASCADE;
drop index T326_PK;

alter table T326_RICHIESTESTR_SPEZ
  add constraint T326_PK primary key (ID, TIPO, SPEZ)
  using index tablespace INDICI storage (initial 256K next 256K pctincrease 0);

create index T326_IDRICH
  on T326_RICHIESTESTR_SPEZ (ID) 
  tablespace INDICI storage (initial 256K next 256K pctincrease 0);

create index T326_ID_TIPO
  on T326_RICHIESTESTR_SPEZ (ID,TIPO) 
  tablespace INDICI storage (initial 256K next 256K pctincrease 0);

alter table T325_RICHIESTESTR_GG add ID_RETTIFICA number(38);
comment on column T325_RICHIESTESTR_GG .ID_RETTIFICA 
  is 'ID della richiesta che rettifica la presente';

create index T325_ID_RETTIFICA on T325_RICHIESTESTR_GG (ID_RETTIFICA) 
  tablespace INDICI storage (initial 256K next 256K pctincrease 0);

UPDATE T480_COMUNI
SET CITTA = 'SCALETTA ZANCLEA'
WHERE CODCATASTALE = 'I492';

create table MONDOEDP.I093_ITER_AUT(
  AZIENDA varchar2(30),
  ITER varchar2(10),
  COD_ITER varchar2(20),
  FILTRO_RICHIESTA varchar2(2000),
  CONDIZ_AUTORIZZ_AUTOMATICA varchar2(2000),
  MAX_LIV_AUTORIZZ_AUTOMATICA number(2) default -1
) tablespace LAVORO storage (initial 256K next 256K pctincrease 0)/*--NOLOG--*/;

comment on column MONDOEDP.I093_ITER_AUT.ITER is 'Identificativo dell''iter di cui si vogliono definire i possibili percorsi autorizzativi';
comment on column MONDOEDP.I093_ITER_AUT.COD_ITER is 'Codice dell''iter di cui esprimere le caratteristiche';
comment on column MONDOEDP.I093_ITER_AUT.FILTRO_RICHIESTA is 'Espressione SQL che attiva questo COD_ITER se verificata dai dati della richiesta';
comment on column MONDOEDP.I093_ITER_AUT.CONDIZ_AUTORIZZ_AUTOMATICA is 'Espressione SQL che attiva l''autorizzazione automatica se verificata';
comment on column MONDOEDP.I093_ITER_AUT.MAX_LIV_AUTORIZZ_AUTOMATICA is 'Massimo livello che può essere autorizzato automaticamente';

alter table MONDOEDP.I093_ITER_AUT add constraint I093_PK primary key (AZIENDA,ITER,COD_ITER) using index tablespace INDICI storage (initial 256K next 256K pctincrease 0)/*--NOLOG--*/;

create table MONDOEDP.I094_LIVELLI_ITER_AUT(
AZIENDA varchar2(30),
ITER varchar2(10),
COD_ITER varchar2(20),
LIVELLO number(2),
OBBLIGATORIO varchar2(1),
AVVISO varchar2(1),
VALORI_POSSIBILI varchar2(100),
AUTORIZZ_INTERMEDIA varchar2(1),
DATI_MODIFICABILI varchar2(1) default 'N',
INVIO_EMAIL varchar2(1) default 'N'
) tablespace LAVORO storage (initial 256K next 256K pctincrease 0)/*--NOLOG--*/;

alter table MONDOEDP.I094_LIVELLI_ITER_AUT add constraint I094_PK primary key (AZIENDA,ITER,COD_ITER,LIVELLO) using index tablespace INDICI/*--NOLOG--*/;
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.ITER is 'Identificativo dell''iter di cui si vuole definire i livelli di autorizzazione';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.COD_ITER is 'Codice dell''iter di cui si vuole definire i livelli di autorizzazione';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.LIVELLO is 'Numero di livello di autorizzazione = 1..9';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.OBBLIGATORIO is 'S=autorizzazione obbligatoria, N=autorizzazione facoltativa';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.AVVISO is 'S=dare l''avviso al livello successivo che manca autorizzazione se non obbligatoria, N=non viene dato alcun avviso al livello successivo';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.VALORI_POSSIBILI is 'Elenco valori disponibili in fase di autorizzazione. per esempio S,N';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.AUTORIZZ_INTERMEDIA is 'Valore che indica un''autorizzazione intermedia, da completare successivamente dall''applicativo specifico. Non ancora visibile dal livello successivo';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.DATI_MODIFICABILI is 'S=chi ha accesso a questo livello di autorizzazione può modificare i dati, se previsti, nella tabella T851';
comment on column MONDOEDP.I094_LIVELLI_ITER_AUT.INVIO_EMAIL is 'N=disattivo, R=solo verso Richiedente, A=solo verso autorizzatore, E=verso Richiedente e Autorizzatore';

alter table MONDOEDP.I094_LIVELLI_ITER_AUT
  add constraint I094_FK_I093 foreign key (AZIENDA, ITER, COD_ITER)
  references MONDOEDP.I093_ITER_AUT (AZIENDA, ITER, COD_ITER) on delete cascade/*--NOLOG--*/;

create table MONDOEDP.I075_ITER_AUTORIZZATIVI (
AZIENDA varchar2(30),
PROFILO varchar2(20),
ITER varchar2(10),
COD_ITER varchar2(20),
LIVELLO number(2),
ACCESSO varchar2(1) DEFAULT 'F'
) tablespace LAVORO storage (initial 256K next 256K pctincrease 0)/*--NOLOG--*/;

alter table MONDOEDP.I075_ITER_AUTORIZZATIVI add constraint I075_PK primary key (AZIENDA,PROFILO,ITER,COD_ITER,LIVELLO) using index tablespace INDICI storage (initial 256K next 256K pctincrease 0)/*--NOLOG--*/;
comment on column MONDOEDP.I075_ITER_AUTORIZZATIVI.ITER is 'Identificativo dell''iter di cui si vuole specificare i livelli accessibili';
comment on column MONDOEDP.I075_ITER_AUTORIZZATIVI.COD_ITER is 'Codice dell''iter di cui si vuole specificare i livelli accessibili';
comment on column MONDOEDP.I075_ITER_AUTORIZZATIVI.LIVELLO is 'Livello con cui è possibile fare l''accesso visualizzando le richieste già autorizzate dei livelli precedenti';
comment on column MONDOEDP.I075_ITER_AUTORIZZATIVI.ACCESSO is 'F=da filtro funzioni, R=sola lettura';

alter table MONDOEDP.I061_PROFILI_DIPENDENTE add ITER_AUTORIZZATIVI varchar2(20)/*--NOLOG--*/;

