CREATE OR REPLACE procedure timb_trigger_before
(TABELLA IN VARCHAR2, P_PROGRESSIVO IN INTEGER, P_DATA IN DATE, P_ORA IN DATE, P_VERSO IN OUT VARCHAR2, P_FLAG IN VARCHAR2, P_RILEVATORE IN VARCHAR2, P_CAUSALE IN VARCHAR2, P_VALIDA IN OUT VARCHAR2) AS
BEGIN
END;
/

