ALTER TABLE I100_PARSCARICO ADD TIPOSCARICO VARCHAR2(1);

CREATE TABLE I101_TIMBIRREGOLARI
  (DATA DATE,
   BADGE NUMBER(8),
   EDBADGE VARCHAR2(2),
   ORA DATE,
   VERSO VARCHAR2(1),
   RILEV VARCHAR2(2),
   CAUSALE VARCHAR2(5))
TABLESPACE LAVORO;
