ALTER TABLE T430_STORICO MODIFY ABCAUSALE1 VARCHAR2(200);
ALTER TABLE T430_STORICO MODIFY ABPRESENZA1 VARCHAR2(200);
UPDATE T430_STORICO SET ABCAUSALE1 = ABCAUSALE1 || ',' || ABCAUSALE2 
  WHERE ABCAUSALE2 IS NOT NULL;
UPDATE T430_STORICO SET ABCAUSALE1 = ABCAUSALE1 || ',' || ABCAUSALE3 
  WHERE ABCAUSALE3 IS NOT NULL;
UPDATE T430_STORICO SET ABCAUSALE1 = ABCAUSALE1 || ',' || ABCAUSALE4
  WHERE ABCAUSALE4 IS NOT NULL;
UPDATE T430_STORICO SET ABCAUSALE1 = ABCAUSALE1 || ',' || ABCAUSALE5 
  WHERE ABCAUSALE5 IS NOT NULL;
UPDATE T430_STORICO SET ABCAUSALE1 = ABCAUSALE1 || ',' || ABCAUSALE6
  WHERE ABCAUSALE6 IS NOT NULL;
UPDATE T430_STORICO SET ABCAUSALE1 = SUBSTR(ABCAUSALE1,2,200) 
  WHERE SUBSTR(ABCAUSALE1,1,1) = ',';
  
UPDATE T430_STORICO SET ABPRESENZA1 = ABPRESENZA1 || ',' || ABPRESENZA2 
  WHERE ABPRESENZA2 IS NOT NULL;
UPDATE T430_STORICO SET ABPRESENZA1 = ABPRESENZA1 || ',' || ABPRESENZA3 
  WHERE ABPRESENZA3 IS NOT NULL;
UPDATE T430_STORICO SET ABPRESENZA1 = ABPRESENZA1 || ',' || ABPRESENZA4
  WHERE ABPRESENZA4 IS NOT NULL;
UPDATE T430_STORICO SET ABPRESENZA1 = ABPRESENZA1 || ',' || ABPRESENZA5 
  WHERE ABPRESENZA5 IS NOT NULL;
UPDATE T430_STORICO SET ABPRESENZA1 = ABPRESENZA1 || ',' || ABPRESENZA6
  WHERE ABPRESENZA6 IS NOT NULL;
UPDATE T430_STORICO SET ABPRESENZA1 = ABPRESENZA1 || ',' || ABPRESENZA7
  WHERE ABPRESENZA7 IS NOT NULL;
UPDATE T430_STORICO SET ABPRESENZA1 = ABPRESENZA1 || ',' || ABPRESENZA8
  WHERE ABPRESENZA8 IS NOT NULL;
UPDATE T430_STORICO SET ABPRESENZA1 = SUBSTR(ABPRESENZA1,2,200) 
  WHERE SUBSTR(ABPRESENZA1,1,1) = ',';
  
UPDATE T033_LAYOUT SET CAPTION = 'Assenze abilitate' WHERE CAMPODB = 'ABCAUSALE1';
UPDATE T033_LAYOUT SET CAPTION = 'Presenze abilitate' WHERE CAMPODB = 'ABPRESENZA1';
UPDATE I500_DATILIBERI SET PROGRESSIVO =PROGRESSIVO - 12;

DELETE FROM I010_CAMPIANAGRAFICI WHERE NOME_CAMPO IN
  ('T430ABCAUSALE2','T430ABCAUSALE3','T430ABCAUSALE4','T430ABCAUSALE5','T430ABCAUSALE6',
   'T430ABPRESENZA2','T430ABPRESENZA3','T430ABPRESENZA4','T430ABPRESENZA5','T430ABPRESENZA6','T430ABPRESENZA7','T430ABPRESENZA8',
   'T430D_ABCAUSALE1','T430D_ABCAUSALE2','T430D_ABCAUSALE3','T430D_ABCAUSALE4','T430D_ABCAUSALE5','T430D_ABCAUSALE6',
   'T430D_ABPRESENZA1','T430D_ABPRESENZA2','T430D_ABPRESENZA3','T430D_ABPRESENZA4','T430D_ABPRESENZA5','T430D_ABPRESENZA6','T430D_ABPRESENZA7','T430D_ABPRESENZA8');
UPDATE I010_CAMPIANAGRAFICI SET NOME_LOGICO = 'Assenze abilitate' WHERE NOME_CAMPO = 'T430ABCAUSALE1';
UPDATE I010_CAMPIANAGRAFICI SET NOME_LOGICO = 'Presenze abilitate' WHERE NOME_CAMPO = 'T430ABPRESENZA1';

DELETE FROM T033_LAYOUT WHERE CAMPODB IN
  ('ABCAUSALE2','ABCAUSALE3','ABCAUSALE4','ABCAUSALE5','ABCAUSALE6',
   'ABPRESENZA2','ABPRESENZA3','ABPRESENZA4','ABPRESENZA5','ABPRESENZA6','ABPRESENZA7','ABPRESENZA8');

RENAME I070_OPERATORI TO I070_OLD;
CREATE TABLE I070_OPERATORI AS SELECT * FROM I070_OLD;
DROP TABLE I070_OLD;
ALTER TABLE I070_OPERATORI ADD CONSTRAINT I070_PK 
  PRIMARY KEY (AZIENDA,UTENTE) USING INDEX TABLESPACE INDICI STORAGE(INITIAL 128K NEXT 128K PCTINCREASE 0);
  
ALTER TABLE T361_OROLOGI ADD VERSO VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T025_CONTMENSILI ADD TIPOLIMITECOMPA VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T025_CONTMENSILI ADD LIMITECOMPA VARCHAR2(6);

ALTER TABLE T430_STORICO MODIFY TERMINALI VARCHAR2(300);