ALTER TABLE T265_CAUASSENZE ADD ESCLUSIONE VARCHAR2(1);
UPDATE T265_CAUASSENZE SET ESCLUSIONE = 'N';

ALTER TABLE T360_TERMENSA ADD INTERVALLO VARCHAR2(5);
ALTER TABLE T360_TERMENSA ADD PAUSAMENSAGESTITA VARCHAR2(1);
ALTER TABLE T360_TERMENSA ADD PRESENZAMINIMA VARCHAR2(1);
ALTER TABLE T360_TERMENSA ADD VOCEPAGHE1 VARCHAR2(6);
ALTER TABLE T360_TERMENSA ADD VOCEPAGHE2 VARCHAR2(6);
ALTER TABLE T360_TERMENSA ADD ORARIOSPEZZATO VARCHAR2(1);
UPDATE T360_TERMENSA SET VOCEPAGHE1 = (SELECT MIN(P100) FROM T190_INTPAGHE WHERE P100 IS NOT NULL);
UPDATE T360_TERMENSA SET PAUSAMENSAGESTITA = 'N';
UPDATE T360_TERMENSA SET PRESENZAMINIMA = 'N';
UPDATE T360_TERMENSA SET ORARIOSPEZZATO = 'N';
UPDATE T360_TERMENSA SET INTERVALLO = '00.00';
ALTER TABLE T410_PASTI ADD PASTI2 NUMBER(8);

