CREATE TABLE T913_SERBATOIKEY (
  CODICE VARCHAR2(10),
  ID_SERBATOIO NUMBER(3),
  POS NUMBER(3),
  DATO VARCHAR2(40),
  TOTALE VARCHAR2(1)
)
TABLESPACE LAVORO STORAGE (INITIAL 32K NEXT 128K PCTINCREASE 0);

ALTER TABLE T913_SERBATOIKEY ADD CONSTRAINT T913_PK PRIMARY KEY (CODICE,ID_SERBATOIO,POS) 
USING INDEX TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 128K PCTINCREASE 0);

CREATE TABLE T914_SERBATOIFILTRO (
  CODICE VARCHAR2(10),
  ID_SERBATOIO NUMBER(3),
  ESCLUSIVO VARCHAR2(1) DEFAULT 'N',
  FILTRO VARCHAR2(300)
)
TABLESPACE LAVORO STORAGE (INITIAL 32K NEXT 128K PCTINCREASE 0);

ALTER TABLE T914_SERBATOIFILTRO ADD CONSTRAINT T914_PK PRIMARY KEY (CODICE,ID_SERBATOIO) 
USING INDEX TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 256K PCTINCREASE 0);

CREATE TABLE T915_CODICISELEZIONATI (
  CODICE VARCHAR2(10),
  ID_SERBATOIO NUMBER(3),
  DATO VARCHAR2(40)
)
TABLESPACE LAVORO STORAGE (INITIAL 32K NEXT 256K PCTINCREASE 0);

ALTER TABLE T915_CODICISELEZIONATI ADD CONSTRAINT T915_PK PRIMARY KEY (CODICE,ID_SERBATOIO,DATO) 
USING INDEX TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 256K PCTINCREASE 0);

ALTER TABLE T910_RIEPILOGO ADD FILTROESCLUSIVO VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T910_RIEPILOGO ADD VALORENULLO VARCHAR2(1) DEFAULT 'S';
DROP TABLE T910_OLD;
RENAME T910_RIEPILOGO TO T910_OLD;
ALTER TABLE T910_OLD DROP CONSTRAINT T910_PK;
CREATE TABLE T910_RIEPILOGO STORAGE (PCTINCREASE 0 INITIAL 32K NEXT 256K) AS 
  SELECT CODICE,TITOLO,APPLICAZIONE,TIPO,SEPARAH,SEPARAV,FONTNAME,FONTSIZE,SALTOPAGINA,TOTALI,
         TOTPARZIALI,TOTGENERALI,CONTEGGIGIORNALIERI,FILTROESCLUSIVO,VALORENULLO,IMPOSTAZIONI FROM T910_OLD;
ALTER TABLE T910_RIEPILOGO MODIFY SEPARAH VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T910_RIEPILOGO MODIFY SEPARAV VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T910_RIEPILOGO MODIFY SALTOPAGINA VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T910_RIEPILOGO MODIFY TOTALI VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T910_RIEPILOGO MODIFY TOTPARZIALI VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T910_RIEPILOGO MODIFY TOTGENERALI VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T910_RIEPILOGO MODIFY CONTEGGIGIORNALIERI VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T910_RIEPILOGO MODIFY FILTROESCLUSIVO VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T910_RIEPILOGO MODIFY VALORENULLO VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T910_RIEPILOGO ADD CONSTRAINT T910_PK PRIMARY KEY (CODICE) 
USING INDEX TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 256K PCTINCREASE 0);

INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO,POS,DATO,TOTALE)
  SELECT CODICE,1,0,'Cod.Ind.presenza','S' FROM T910_RIEPILOGO WHERE APPLICAZIONE = 'RILPRE';
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO,POS,DATO,TOTALE)
  SELECT CODICE,2,0,'Codice presenze','S' FROM T910_RIEPILOGO WHERE APPLICAZIONE = 'RILPRE';
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO,POS,DATO,TOTALE)
  SELECT CODICE,3,0,'Codice assenze','S' FROM T910_RIEPILOGO WHERE APPLICAZIONE = 'RILPRE';
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO,POS,DATO,TOTALE)
  SELECT CODICE,4,0,'Data conteggio','S' FROM T910_OLD WHERE APPLICAZIONE = 'RILPRE' AND DETTAGLIOGIORNALIERO = 'S';

UPDATE T911_DATIRIEPILOGO A SET TOTALE = 'S' WHERE 
NOME IN ('Cod.Ind.presenza','Codice presenze','Codice assenze') AND
EXISTS (SELECT CODICE FROM T911_DATIRIEPILOGO WHERE CODICE = A.CODICE AND TOTALE = 'S' AND NOME NOT IN ('Cod.Ind.presenza','Codice presenze','Codice assenze'));

DELETE FROM T911_DATIRIEPILOGO T1 WHERE NOME = 'Data conteggio interna' AND EXISTS
  (SELECT CODICE FROM T911_DATIRIEPILOGO WHERE CODICE = T1.CODICE AND NOME = 'Data conteggio');
DELETE FROM T912_SORTRIEPILOGO T1 WHERE NOME = 'Data conteggio interna' AND EXISTS
  (SELECT CODICE FROM T912_SORTRIEPILOGO WHERE CODICE = T1.CODICE AND NOME = 'Data conteggio');
UPDATE T911_DATIRIEPILOGO SET NOME = 'Data conteggio' WHERE NOME = 'Data conteggio interna';
UPDATE T912_SORTRIEPILOGO SET NOME = 'Data conteggio' WHERE NOME = 'Data conteggio interna';

ALTER TABLE I010_CAMPIANAGRAFICI ADD VAL_DEFAULT VARCHAR2(5);
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = 'M' WHERE NOME_CAMPO = 'SESSO';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = 'S' WHERE NOME_CAMPO = 'RAPPORTI_UNITI';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = 'F' WHERE NOME_CAMPO = 'T430CAUSSTRAORD';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = '1' WHERE NOME_CAMPO = 'T430STRAORDE';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = '2' WHERE NOME_CAMPO = 'T430STRAORDU';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = '0' WHERE NOME_CAMPO = 'T430STRAORDEU';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = '0' WHERE NOME_CAMPO = 'T430STRAORDEU2';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = '0' WHERE NOME_CAMPO = 'T430HTEORICHE';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = '0' WHERE NOME_CAMPO = 'T430TGESTIONE';
UPDATE I010_CAMPIANAGRAFICI SET VAL_DEFAULT = 'A' WHERE NOME_CAMPO = 'T430PERSELASTICO';

ALTER TABLE T044_STORICOGIUSTIFICATIVI ADD DATANAS DATE;

create table I150_PARSCARICOGIUST
(
  CODICE VARCHAR2(20) not null,
  NOMEFILE VARCHAR2(100) not null,
  CORRENTE VARCHAR2(1) not null,
  MATRICOLA VARCHAR2(8),
  BADGE VARCHAR2(8),
  ANNODA VARCHAR2(8),
  MESEDA VARCHAR2(8),
  GIORNODA VARCHAR2(8),
  ANNOA VARCHAR2(8),
  MESEA VARCHAR2(8),
  GIORNOA VARCHAR2(8),
  ORADA VARCHAR2(8),
  MINDA VARCHAR2(8),
  ORAA VARCHAR2(8),
  MINA VARCHAR2(8),
  CAUSALE VARCHAR2(8) not null,
  TIPO VARCHAR2(8),
  CODICE_TIPOI VARCHAR2(5),
  CODICE_TIPOM VARCHAR2(5),
  CODICE_TIPOD VARCHAR2(5),
  CODICE_TIPON VARCHAR2(5)
)
  tablespace LAVORO pctfree 10 pctused 40 initrans 1 maxtrans 255
  storage (initial 32K next 32K minextents 1 pctincrease 0);

alter table I150_PARSCARICOGIUST add constraint I150_PK primary key (CODICE)
  using index tablespace INDICI pctfree 10 initrans 2 maxtrans 255
  storage (initial 32K next 32K minextents 1 pctincrease 0);

ALTER TABLE T161_INDGRUPPO
  ADD CONSTRAINT T161_PK PRIMARY KEY (DECORRENZA, CODICE, CODICE2)
  USING INDEX TABLESPACE INDICI PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE (INITIAL 128K NEXT 128K MINEXTENTS 1 PCTINCREASE 0);