declare
  i integer;
begin
  select COUNT(*) into i from P042_ENTIIRPEF;
  if i = 0 then
    insert into I050_SCRIPTSQL (NOME) values ('SQ120402_2P042.sql');
  end if;
exception
  when others then
    insert into I050_SCRIPTSQL (NOME) values ('SQ120402_2P042.sql');
end/*--NOLOG--*/;
/

UPDATE t480_comuni t SET T.CITTA='RIPALIMOSANI' WHERE T.CODCATASTALE='H313';
UPDATE t480_comuni t SET T.CITTA='GALZIGNANO TERME' WHERE T.CODCATASTALE='D889';
UPDATE t480_comuni t SET T.CITTA='ISOLA DEL GRAN SASSO D''ITALIA' WHERE T.CODCATASTALE='E343';

UPDATE P092_CODICIINAIL SET ORE_MESE = '' WHERE ORE_MESE = 0.00;

UPDATE P200_VOCI SET PROTETTA = 'S';

DELETE P201_ASSOGGETTAMENTI T
WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE_FIGLIO='14120' AND T.ASSOGGETTAMENTO=-100
AND T.COD_VOCE_PADRE IN ('15095') AND EXISTS
(SELECT 'X' FROM P200_VOCI V WHERE V.COD_CONTRATTO=T.COD_CONTRATTO AND V.COD_VOCE=T.COD_VOCE_PADRE
AND V.COD_VOCE_SPECIALE=T.COD_VOCE_SPECIALE_PADRE AND UPPER(V.DESCRIZIONE) LIKE '%PERMESSO NON RETRIBUITO%');

DELETE P201_ASSOGGETTAMENTI T
WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE_FIGLIO='14120' AND T.ASSOGGETTAMENTO=-100
AND T.COD_VOCE_PADRE IN ('15100','15102') AND EXISTS
(SELECT 'X' FROM P200_VOCI V WHERE V.COD_CONTRATTO=T.COD_CONTRATTO AND V.COD_VOCE=T.COD_VOCE_PADRE
AND V.COD_VOCE_SPECIALE=T.COD_VOCE_SPECIALE_PADRE AND UPPER(V.DESCRIZIONE) LIKE '%SCIOPERO%');

-- Creazione interrogazione di servizio PA_DMA_2_NonCorretti
declare
  i integer;
begin
  select COUNT(*) into i from P441_CEDOLINO;
  if i > 0 then
    select COUNT(*) into i from t002_querypersonalizzate t where t.nome = 'PA_DMA_2_NonCorretti';
    if i = 0 then
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', -2, 'Stringa,Data', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', -1, '"CPS","31/01/2012"', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 0, 'SELECT TIPO, T030.MATRICOLA, T030.COGNOME, T030.NOME, IMPORTO FROM (', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 1, '(SELECT ''CED'' TIPO, P441.PROGRESSIVO,TRUNC(SUM(P442.IMPORTO * P216.PERCENTUALE / 100)) IMPORTO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 2, 'FROM P441_CEDOLINO P441, P442_CEDOLINOVOCI P442, P216_ACCORPAMENTOVOCI P216', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 3, 'WHERE P441.ID_CEDOLINO = P442.ID_CEDOLINO ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 4, 'AND P441.DATA_CEDOLINO=:MeseCedolino AND P442.TIPO_RECORD = ''M''', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 5, 
        'AND P442.COD_CONTRATTO = P216.COD_CONTRATTO AND P442.COD_VOCE = P216.COD_VOCE AND P442.COD_VOCE_SPECIALE = P216.COD_VOCE_SPECIALE', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 6, 'AND P442.DATA_COMPETENZA_A BETWEEN P216.DECORRENZA AND P216.DECORRENZA_FINE', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 7, 'AND P216.COD_TIPOACCORPAMENTOVOCI=''DMA'' ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 8, 
        'AND P216.COD_CODICIACCORPAMENTOVOCI=DECODE(:Cassa,''CPDEL'',''0500'',''CPS'',''0510'',''TFS'',''0520'',''TFR'',''0530'')', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 9, 'GROUP BY P441.PROGRESSIVO ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 10, 'HAVING TRUNC(SUM(P442.IMPORTO * P216.PERCENTUALE / 100)) <> 0', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 11, 'MINUS', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 12, 
        'SELECT ''CED'', PROGRESSIVO,TRUNC(SUM(TO_NUMBER(P673.VALORE,''9999999999D9999'',''NLS_NUMERIC_CHARACTERS='''',.''''''))) IMPORTO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 13, 'FROM P672_XMLTESTATE P672, P673_XMLDATIINDIVIDUALI P673', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 14, 'WHERE P672.ID_FLUSSO=P673.ID_FLUSSO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 15, 'AND P672.DATA_FINE_PERIODO=:MeseCedolino AND P673.TIPO_RECORD = ''M'' ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 16, 'AND P673.NUMERO IN (DECODE(:Cassa,''CPDEL'',''F315'',''CPS'',''F315'',''TFS'',''F525'',''TFR'',''F515''),', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 17, '                    DECODE(:Cassa,''CPDEL'',''F320'',''CPS'',''F320'',''TFS'',''X'',''TFR'',''X''),', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 18, '                    DECODE(:Cassa,''CPDEL'',''H315'',''CPS'',''H315'',''TFS'',''H525'',''TFR'',''H515''),', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 19, '                    DECODE(:Cassa,''CPDEL'',''H320'',''CPS'',''H320'',''TFS'',''X'',''TFR'',''X'') )', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 20, 'AND EXISTS (SELECT ''X'' FROM P673_XMLDATIINDIVIDUALI P673A', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 21, '             WHERE P673A.ID_FLUSSO = P673.ID_FLUSSO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 22, '               AND P673A.PROGRESSIVO = P673.PROGRESSIVO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 23, '               AND P673A.PROGRESSIVO_NUMERO = P673.PROGRESSIVO_NUMERO AND P673A.TIPO_RECORD = P673.TIPO_RECORD', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 24, 
        '               AND P673A.NUMERO IN (DECODE(:Cassa,''CPDEL'',''F305'',''CPS'',''F305'',''TFS'',''F505'',''TFR'',''F505''), ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 25, 
        '                                    DECODE(:Cassa,''CPDEL'',''H305'',''CPS'',''H305'',''TFS'',''H505'',''TFR'',''H505''))', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 26, 
        '               AND P673A.VALORE = DECODE(:Cassa,''CPDEL'',''2'',''CPS'',''5'',''TFS'',''6'',''TFR'',''6'') ) ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 27, 'AND EXISTS (SELECT ''X'' FROM P673_XMLDATIINDIVIDUALI P673A', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 28, '             WHERE P673A.ID_FLUSSO = P673.ID_FLUSSO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 29, '               AND P673A.PROGRESSIVO = P673.PROGRESSIVO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 30, '               AND P673A.PROGRESSIVO_NUMERO = P673.PROGRESSIVO_NUMERO AND P673A.TIPO_RECORD = P673.TIPO_RECORD', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 31, 
        '               AND (P673A.NUMERO = ''E300'' OR (P673A.NUMERO = ''E600'' AND UPPER(P673A.ATTRIBUTO) IN(''CAUSALEVARIAZIONE=1'',''CAUSALEVARIAZIONE=7''))) )', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 32, 'GROUP BY PROGRESSIVO ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 33, 'HAVING TRUNC(SUM(TO_NUMBER(P673.VALORE,''9999999999D9999'',''NLS_NUMERIC_CHARACTERS='''',.''''''))) <> 0', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 34, ')', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 35, 'UNION ALL', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 36, 
        '(SELECT ''DMA2'' TIPO, PROGRESSIVO,TRUNC(SUM(TO_NUMBER(P673.VALORE,''9999999999D9999'',''NLS_NUMERIC_CHARACTERS='''',.''''''))) IMPORTO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 37, 'FROM P672_XMLTESTATE P672, P673_XMLDATIINDIVIDUALI P673', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 38, 'WHERE P672.ID_FLUSSO=P673.ID_FLUSSO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 39, 'AND P672.DATA_FINE_PERIODO=:MeseCedolino AND P673.TIPO_RECORD = ''M'' ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 40, 'AND P673.NUMERO IN (DECODE(:Cassa,''CPDEL'',''F315'',''CPS'',''F315'',''TFS'',''F525'',''TFR'',''F515''),', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 41, '                    DECODE(:Cassa,''CPDEL'',''F320'',''CPS'',''F320'',''TFS'',''X'',''TFR'',''X''),', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 42, '                    DECODE(:Cassa,''CPDEL'',''H315'',''CPS'',''H315'',''TFS'',''H525'',''TFR'',''H515''),', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 43, '                    DECODE(:Cassa,''CPDEL'',''H320'',''CPS'',''H320'',''TFS'',''X'',''TFR'',''X'') )', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 44, 'AND EXISTS (SELECT ''X'' FROM P673_XMLDATIINDIVIDUALI P673A', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 45, '             WHERE P673A.ID_FLUSSO = P673.ID_FLUSSO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 46, '               AND P673A.PROGRESSIVO = P673.PROGRESSIVO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 47, '               AND P673A.PROGRESSIVO_NUMERO = P673.PROGRESSIVO_NUMERO AND P673A.TIPO_RECORD = P673.TIPO_RECORD', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 48, 
        '               AND P673A.NUMERO IN (DECODE(:Cassa,''CPDEL'',''F305'',''CPS'',''F305'',''TFS'',''F505'',''TFR'',''F505''), ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 49, 
        '                                    DECODE(:Cassa,''CPDEL'',''H305'',''CPS'',''H305'',''TFS'',''H505'',''TFR'',''H505''))', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 50, '               AND P673A.VALORE = DECODE(:Cassa,''CPDEL'',''2'',''CPS'',''5'',''TFS'',''6'',''TFR'',''6'') ) ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 51, 'AND EXISTS (SELECT ''X'' FROM P673_XMLDATIINDIVIDUALI P673A', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 52, '             WHERE P673A.ID_FLUSSO = P673.ID_FLUSSO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 53, '               AND P673A.PROGRESSIVO = P673.PROGRESSIVO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 54, '               AND P673A.PROGRESSIVO_NUMERO = P673.PROGRESSIVO_NUMERO AND P673A.TIPO_RECORD = P673.TIPO_RECORD', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 55, 
       '               AND (P673A.NUMERO = ''E300'' OR (P673A.NUMERO = ''E600'' AND UPPER(P673A.ATTRIBUTO) IN (''CAUSALEVARIAZIONE=1'',''CAUSALEVARIAZIONE=7''))) )', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 56, 'GROUP BY PROGRESSIVO ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 57, 'HAVING TRUNC(SUM(TO_NUMBER(P673.VALORE,''9999999999D9999'',''NLS_NUMERIC_CHARACTERS='''',.''''''))) <> 0', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 58, 'MINUS', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 59, 'SELECT ''DMA2'', P441.PROGRESSIVO,TRUNC(SUM(P442.IMPORTO * P216.PERCENTUALE / 100)) IMPORTO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 60, 'FROM P441_CEDOLINO P441, P442_CEDOLINOVOCI P442, P216_ACCORPAMENTOVOCI P216', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 61, 'WHERE P441.ID_CEDOLINO = P442.ID_CEDOLINO ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 62, 'AND P441.DATA_CEDOLINO=:MeseCedolino AND P442.TIPO_RECORD = ''M''', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 63, 
        'AND P442.COD_CONTRATTO = P216.COD_CONTRATTO AND P442.COD_VOCE = P216.COD_VOCE AND P442.COD_VOCE_SPECIALE = P216.COD_VOCE_SPECIALE ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 64, 'AND P442.DATA_COMPETENZA_A BETWEEN P216.DECORRENZA AND P216.DECORRENZA_FINE', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 65, 'AND P216.COD_TIPOACCORPAMENTOVOCI=''DMA'' ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 66, 
        'AND P216.COD_CODICIACCORPAMENTOVOCI=DECODE(:Cassa,''CPDEL'',''0500'',''CPS'',''0510'',''TFS'',''0520'',''TFR'',''0530'')', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 67, 'GROUP BY P441.PROGRESSIVO ', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) 
        values ('PA_DMA_2_NonCorretti', 68, 'HAVING TRUNC(SUM(P442.IMPORTO * P216.PERCENTUALE / 100)) <> 0)) A, T030_ANAGRAFICO T030', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 69, 'WHERE A.PROGRESSIVO = T030.PROGRESSIVO', 'PAGHE');
      insert into T002_QUERYPERSONALIZZATE (NOME, POSIZ, RIGA, APPLICAZIONE) values ('PA_DMA_2_NonCorretti', 70, 'ORDER BY COGNOME,NOME', 'PAGHE');

    end if;
  end if;
end;
/

alter table T910_RIEPILOGO add QUERY_INTESTAZIONE varchar2(30);
comment on column T910_RIEPILOGO.QUERY_INTESTAZIONE is 'Nome dell''interrogazione di servizio da visualizzare nell''intestazione di ogni pagina';

alter table T910_RIEPILOGO add QUERY_FINESTAMPA varchar2(30);
comment on column T910_RIEPILOGO.QUERY_FINESTAMPA is 'Nome dell''interrogazione di servizio da visualizzare alla fine della stampa';