CREATE TABLE T101_ANOMALIE (
  PROGRESSIVO NUMBER(38, 2) NOT NULL,
  DATA DATE NOT NULL,
  LIVELLO NUMBER(38, 2),
  NUMERO NUMBER(38, 2)
)
  TABLESPACE LAVORO;

CREATE  INDEX INDICE
  ON T101_ANOMALIE (PROGRESSIVO, DATA) TABLESPACE INDICI;

CREATE TABLE T360_TERMENSA (
  NUMTIMBPASTO VARCHAR2(1),
  DIFFTRA2TIMB DATE,
  TIMBDOPOUSCITA VARCHAR2(1),
  TIMBANTECENTRATA VARCHAR2(1),
  CONTROLLOPRESENZA VARCHAR2(1)
)
  TABLESPACE LAVORO;

CREATE TABLE T370_TIMBMENSA (
  PROGRESSIVO NUMBER(38, 2) NOT NULL,
  DATA DATE NOT NULL,
  ORA DATE NOT NULL,
  VERSO VARCHAR2(1) NOT NULL,
  FLAG VARCHAR2(1) NOT NULL,
  RILEVATORE VARCHAR2(2),
  CAUSALE VARCHAR2(5),
  PRIMARY KEY (PROGRESSIVO,DATA,ORA) USING INDEX TABLESPACE INDICI
)
  TABLESPACE LAVORO;

CREATE TABLE T410_PASTI (
  PROGRESSIVO NUMBER(38, 2) NOT NULL,
  ANNO NUMBER(38, 2) NOT NULL,
  MESE NUMBER(38, 2) NOT NULL,
  PASTI NUMBER(38, 2),
  PRIMARY KEY (PROGRESSIVO,ANNO,MESE) USING INDEX TABLESPACE INDICI
)
  TABLESPACE LAVORO;

ALTER TABLE I070_OPERATORI ADD FUNZIONE1 VARCHAR2(1);
