ALTER TABLE I090_ENTI ADD C2_FACOLTATIVO VARCHAR2(1);
UPDATE I090_ENTI SET C2_FACOLTATIVO = 'N';

ALTER TABLE T071_SCHEDAFASCE ADD OREREP_CORR VARCHAR2(6);
ALTER TABLE T071_SCHEDAFASCE ADD OREREP_PREC VARCHAR2(6);
ALTER TABLE T071_SCHEDAFASCE ADD OREREP_LIQ VARCHAR2(6);
