CREATE TABLE T276_VOCIPAGHEPRESENZA (
  CODICE VARCHAR2(5),
  TIPOGIORNO VARCHAR2(2),
  DALLE VARCHAR2(5),
  ALLE VARCHAR2(5),
  LIMITE VARCHAR2(5),
  VOCEPAGHE VARCHAR2(6),
  CONSTRAINT T276_PK PRIMARY KEY (CODICE,TIPOGIORNO,DALLE,LIMITE)
  USING INDEX TABLESPACE INDICI
)
TABLESPACE LAVORO;

CREATE TABLE T076_CAUSPRESPAGHE (
  PROGRESSIVO NUMBER(38),
  DATA DATE,
  VOCEPAGHE VARCHAR2(6),
  ORE VARCHAR2(7),
  CONSTRAINT T076_PK PRIMARY KEY (PROGRESSIVO,DATA,VOCEPAGHE)
  USING INDEX TABLESPACE INDICI
)
TABLESPACE LAVORO;

UPDATE T190_INTPAGHE SET F250 = 'N';
