ALTER TABLE T030_ANAGRAFICO MODIFY SESSO DEFAULT 'M';
ALTER TABLE T030_ANAGRAFICO MODIFY RAPPORTI_UNITI DEFAULT 'S';
ALTER TABLE T430_STORICO MODIFY CAUSSTRAORD DEFAULT 'F';
ALTER TABLE T430_STORICO MODIFY STRAORDE DEFAULT '0';
ALTER TABLE T430_STORICO MODIFY STRAORDU DEFAULT '0';
ALTER TABLE T430_STORICO MODIFY STRAORDEU DEFAULT '0';
ALTER TABLE T430_STORICO MODIFY STRAORDEU2 DEFAULT '0';
ALTER TABLE T430_STORICO MODIFY HTEORICHE DEFAULT '0';
ALTER TABLE T430_STORICO MODIFY TGESTIONE DEFAULT '0';
ALTER TABLE T430_STORICO MODIFY PERSELASTICO DEFAULT 'A';

ALTER TABLE T460_PARTTIME ADD ASSENZEGG NUMBER DEFAULT 100;
ALTER TABLE T460_PARTTIME ADD ASSENZEHH NUMBER DEFAULT 100;

ALTER TABLE T265_CAUASSENZE ADD PARTTIME VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T265_CAUASSENZE ADD TIPO_PROPORZIONE VARCHAR2(1) DEFAULT 'C';
ALTER TABLE T265_CAUASSENZE ADD PROPORZIONA_PERSERV VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T265_CAUASSENZE ADD TEMPO_DETERMINATO VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T265_CAUASSENZE MODIFY CODCAU1 VARCHAR2(100);
UPDATE T265_CAUASSENZE SET CODCAU1 = CODCAU1 || ',' || CODCAU2 
  WHERE CODCAU2 IS NOT NULL;
UPDATE T265_CAUASSENZE SET CODCAU1 = CODCAU1 || ',' || CODCAU3 
  WHERE CODCAU3 IS NOT NULL;
UPDATE T265_CAUASSENZE SET CODCAU1 = CODCAU1 || ',' || CODCAU4
  WHERE CODCAU4 IS NOT NULL;
UPDATE T265_CAUASSENZE SET CODCAU1 = CODCAU1 || ',' || CODCAU5 
  WHERE CODCAU5 IS NOT NULL;
UPDATE T265_CAUASSENZE SET CODCAU1 = CODCAU1 || ',' || CODCAU6
  WHERE CODCAU6 IS NOT NULL;
UPDATE T265_CAUASSENZE SET CODCAU1 = SUBSTR(CODCAU1,2,100) 
  WHERE SUBSTR(CODCAU1,1,1) = ',';
  
UPDATE T265_CAUASSENZE SET CUMULOGLOBALE = 'N' WHERE CUMULOGLOBALE IS NULL;
UPDATE T265_CAUASSENZE SET RICORSIONE = 'N' WHERE RICORSIONE IS NULL;

ALTER TABLE T070_SCHEDARIEPIL ADD LIQ_FUORI_BUDGET NUMBER;

ALTER TABLE T210_MAGGIORAZIONI ADD PIND_TUR VARCHAR2(6);

ALTER TABLE T190_INTPAGHE ADD F040 VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T190_INTPAGHE ADD F300 VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T190_INTPAGHE ADD F310 VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T190_INTPAGHE ADD F320 VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T190_INTPAGHE ADD F330 VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T190_INTPAGHE ADD P300 VARCHAR2(6);
ALTER TABLE T190_INTPAGHE ADD P310 VARCHAR2(6);
ALTER TABLE T190_INTPAGHE ADD P320 VARCHAR2(6);
ALTER TABLE T190_INTPAGHE ADD P330 VARCHAR2(6);

ALTER TABLE MONDOEDP.I070_OPERATORI ADD T100_ORA VARCHAR2(1) DEFAULT 'S';
ALTER TABLE MONDOEDP.I070_OPERATORI ADD T100_RILEVATORE VARCHAR2(1) DEFAULT 'S';
ALTER TABLE MONDOEDP.I070_OPERATORI ADD T100_CAUSALE VARCHAR2(1) DEFAULT 'S';

ALTER TABLE MONDOEDP.I090_ENTI ADD TIMBORIG_VERSO VARCHAR2(1) DEFAULT 'N';
ALTER TABLE MONDOEDP.I090_ENTI ADD TIMBORIG_CAUSALE VARCHAR2(1) DEFAULT 'N';

-- Create table 
create table T692_RESIDUOBUONI
(
  PROGRESSIVO NUMBER(8) not null,
  ANNO NUMBER(4) not null,
  TICKET NUMBER(8),
  BUONIPASTO NUMBER(8)
)
  tablespace LAVORO
  pctfree 10
  pctused 80
  initrans 1
  maxtrans 255
  storage
  (
    initial 256K
    next 256K
    minextents 1
    pctincrease 0
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table T692_RESIDUOBUONI
  add constraint T692_PK primary key (PROGRESSIVO,ANNO)
  using index 
  tablespace INDICI
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 256K
    next 256K
    minextents 1
    pctincrease 0
  );
