ALTER TABLE T020_ORARI ADD MATURA_RIPCOM VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T130_RESIDANNOPREC ADD RIPOSICOMP VARCHAR2(7);
ALTER TABLE T460_PARTTIME ADD INDFEST NUMBER DEFAULT 100;
ALTER TABLE T265_CAUASSENZE ADD ALLUNGA_PROVA VARCHAR2(1) DEFAULT 'N';
DELETE FROM MONDOEDP.I091_DATIENTE WHERE TIPO = 'C2_STR_REP';

ALTER TABLE T910_RIEPILOGO ADD TOTPARZIALI VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T910_RIEPILOGO ADD TOTGENERALI VARCHAR2(1) DEFAULT 'S';

ALTER TABLE T601_TIPIOPERATORE ADD OTTIMALE1FR NUMBER(3);
ALTER TABLE T601_TIPIOPERATORE ADD OTTIMALE1FS NUMBER(3);
ALTER TABLE T601_TIPIOPERATORE ADD OTTIMALE2FR NUMBER(3);
ALTER TABLE T601_TIPIOPERATORE ADD OTTIMALE2FS NUMBER(3);
ALTER TABLE T601_TIPIOPERATORE ADD OTTIMALE3FR NUMBER(3);
ALTER TABLE T601_TIPIOPERATORE ADD OTTIMALE3FS NUMBER(3);
ALTER TABLE T601_TIPIOPERATORE ADD OTTIMALE1FR NUMBER(3);
ALTER TABLE T601_TIPIOPERATORE ADD PROFILO VARCHAR2(5);

create table T602_PROFILITURNI
(
  CODICE VARCHAR2(5) not null,
  DESCRIZIONE VARCHAR2(40),
  NUMMAXGGCONSECUTIVIDILAVORO NUMBER not null,
  NUMMINNOTTIPERGRUPPODINOTTI NUMBER NOT NULL,
  NUMMAXNOTTIPERGRUPPODINOTTI NUMBER NOT NULL,
  NUMRIPOSIDOPOTURNODINOTTE NUMBER NOT NULL,
  NUMGGTRADUETURNIDINOTTE NUMBER NOT NULL,
  NUMOKNOTTIPERCICLOFERIALE NUMBER NOT NULL,
  NUMOKNOTTIPERCICLOFESTIVO NUMBER NOT NULL
)
  tablespace LAVORO
  pctfree 10 pctused 80
  initrans 1 maxtrans 255
  storage (initial 32K next 256K minextents 1 pctincrease 0);

alter table T602_PROFILITURNI add constraint T602_PK PRIMARY KEY (CODICE)
  using index tablespace INDICI storage (initial 32K next 128K minextents 1 pctincrease 0);