CREATE TABLE MONDOEDP.I102_SCARICOPIANIFICATO
  (ORA VARCHAR2(5))
TABLESPACE LAVORO STORAGE(PCTINCREASE 0 INITIAL 16K NEXT 16K);

ALTER TABLE T210_MAGGIORAZIONI ADD PORE_COMP VARCHAR2(6);

ALTER TABLE T070_SCHEDARIEPIL ADD ORECOMP_LIQUIDATE VARCHAR2(7);

create table T044_STORICOGIUSTIFICATIVI
(
  PROGRESSIVO NUMBER(8) not null,
  DATA DATE not null,
  CAUSALE VARCHAR2(5) not null,
  TIPOGIUST VARCHAR2(1) not null,
  DAORE DATE,
  AORE DATE,
  OPERAZIONE VARCHAR2(1) not null,
  FLAG VARCHAR2(1),
  DATA_AGG DATE
)
  tablespace LAVORO
  pctfree 10 pctused 80
  initrans 1 maxtrans 255
  storage (initial 32K next 5M minextents 1 pctincrease 0);

create index T044_PROGRESSIVODATA on T044_STORICOGIUSTIFICATIVI (PROGRESSIVO,DATA)
  tablespace INDICI
  pctfree 10 initrans 2
  maxtrans 255
  storage (initial 32K next 5M minextents 1 pctincrease 0);
  
ALTER TABLE T025_CONTMENSILI ADD BANCAORE VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T025_CONTMENSILI ADD ABBATTIMENTO_LIQUIDABILE VARCHAR2(1) DEFAULT '0';