UPDATE T911_DATIRIEPILOGO SET NOME = 'Debito contrattuale' WHERE NOME = 'Debito orario mese';
UPDATE T911_DATIRIEPILOGO SET NOME = 'Debito aggiuntivo' WHERE NOME = 'Debito P.O. mese';
UPDATE T911_DATIRIEPILOGO SET NOME = 'Debito mensile' WHERE NOME = 'Debito totale mese';

UPDATE T912_SORTRIEPILOGO SET NOME = 'Debito contrattuale' WHERE NOME = 'Debito orario mese';
UPDATE T912_SORTRIEPILOGO SET NOME = 'Debito aggiuntivo' WHERE NOME = 'Debito P.O. mese';
UPDATE T912_SORTRIEPILOGO SET NOME = 'Debito mensile' WHERE NOME = 'Debito totale mese';

UPDATE T914_SERBATOIFILTRO SET FILTRO = REPLACE(FILTRO,'Debitototalemese','Debitomensile');
UPDATE T914_SERBATOIFILTRO SET FILTRO = REPLACE(FILTRO,'DEBITOTOTALEMESE','Debitomensile');
UPDATE T914_SERBATOIFILTRO SET FILTRO = REPLACE(FILTRO,'DebitoTotaleMese','Debitomensile');
UPDATE T914_SERBATOIFILTRO SET FILTRO = REPLACE(FILTRO,'DebitoPOmese','Debitoaggiuntivo');
UPDATE T914_SERBATOIFILTRO SET FILTRO = REPLACE(FILTRO,'Debitoorariomese','Debitocontrattuale');

ALTER TABLE M020_TIPIRIMBORSI ADD FLAG_ANTICIPO VARCHAR2(1) DEFAULT 'N' NOT NULL;
ALTER TABLE M040_MISSIONI ADD NOTE_RIMBORSI VARCHAR2(240);

CREATE TABLE T045_ASSENZEAUTOMATICHE (
  CAUSALI VARCHAR2(300),
  DEBITO VARCHAR2(1) DEFAULT 'A',
  GIORNI_VUOTI VARCHAR2(1) DEFAULT 'N',
  ORE_MAX VARCHAR2(5) DEFAULT '23.59'
  )
TABLESPACE LAVORO
PCTFREE 10
PCTUSED 80
STORAGE (INITIAL 32K NEXT 32K PCTINCREASE 0);

comment on column T045_ASSENZEAUTOMATICHE.DEBITO
  is 'A=Debito giornaliero, B=Differenza tra U min e E max in flessibilita''';
comment on column T045_ASSENZEAUTOMATICHE.GIORNI_VUOTI
  is 'N=non vengono considerati i giorni senza timbrature';
comment on column T045_ASSENZEAUTOMATICHE.ORE_MAX
  is 'Ore massime che è possibile coprire automaticamente ogni giorno';
  
ALTER TABLE T275_CAUPRESENZE MODIFY TIPOCONTEGGIO DEFAULT 'A';
ALTER TABLE T275_CAUPRESENZE MODIFY ORENORMALI DEFAULT 'A';
ALTER TABLE T275_CAUPRESENZE MODIFY RIPFASCE DEFAULT 'A';
ALTER TABLE T275_CAUPRESENZE MODIFY STAMPE DEFAULT 'B';
ALTER TABLE T275_CAUPRESENZE MODIFY LIQUIDABILE DEFAULT 'A';
ALTER TABLE T275_CAUPRESENZE MODIFY RIPLIQ DEFAULT 'B';
ALTER TABLE T275_CAUPRESENZE MODIFY DETREPERIB DEFAULT 'S';
ALTER TABLE T275_CAUPRESENZE MODIFY PIANIFREP DEFAULT 'N';
ALTER TABLE T275_CAUPRESENZE MODIFY MATURAMENSA DEFAULT 'S';
ALTER TABLE T275_CAUPRESENZE MODIFY LFSCAVMEZ DEFAULT 'N';

ALTER TABLE T270_RAGGRPRESENZE MODIFY INDFESTIVA DEFAULT 'S';
ALTER TABLE T270_RAGGRPRESENZE MODIFY INDNOTTURNA DEFAULT 'S';
ALTER TABLE T270_RAGGRPRESENZE MODIFY INDPRESENZA DEFAULT 'S';
ALTER TABLE T270_RAGGRPRESENZE MODIFY CODINTERNO DEFAULT 'Z';

ALTER TABLE T220_PROFILIORARI MODIFY SCOSTENTRATA DEFAULT 'N';
ALTER TABLE T220_PROFILIORARI MODIFY PRITIMSC DEFAULT 'N';
ALTER TABLE T220_PROFILIORARI MODIFY TIMBNONAPPOGGIATE DEFAULT 'N';

ALTER TABLE T020_ORARI MODIFY TipoFle DEFAULT 'A';
ALTER TABLE T020_ORARI MODIFY FrazDeb DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY NotteEntrata DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY CompNot DEFAULT 'E';
ALTER TABLE T020_ORARI MODIFY FlagPres DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY FlagMPres DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY CompDetr DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY PausaMensa DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY DETRAUTCONT DEFAULT 'S';
ALTER TABLE T020_ORARI MODIFY Straordinario DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY IndFestiva DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY IndTurno DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY CauObFac DEFAULT 'F';
ALTER TABLE T020_ORARI MODIFY CompLiq DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY TuttoComp DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY CompFascia DEFAULT '1';
ALTER TABLE T020_ORARI MODIFY ObblFac1 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY ObblFac2 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY ObblFac3 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY ObblFac4 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY ObblFacU1 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY ObblFacU2 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY ObblFacU3 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY ObblFacU4 DEFAULT 'O';
ALTER TABLE T020_ORARI MODIFY NumTurno1 DEFAULT 1;
ALTER TABLE T020_ORARI MODIFY NumTurno2 DEFAULT 2;
ALTER TABLE T020_ORARI MODIFY NumTurno3 DEFAULT 3;
ALTER TABLE T020_ORARI MODIFY NumTurno4 DEFAULT 4;
ALTER TABLE T020_ORARI MODIFY CompFascia DEFAULT '1';
ALTER TABLE T020_ORARI MODIFY TuttoComp DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY IndFestStr DEFAULT '2';
ALTER TABLE T020_ORARI MODIFY IndNotStr DEFAULT '2';
ALTER TABLE T020_ORARI MODIFY IndPresStr DEFAULT '2';
ALTER TABLE T020_ORARI MODIFY TimbraturaMensa DEFAULT 'N';
ALTER TABLE T020_ORARI MODIFY IntersezioneMensa DEFAULT 'N';

create table T909_DATICALCOLATI
(
  APPLICAZIONE varchar2(6) not null,
  NOME         varchar2(40) not null,
  ID_SERBATOIO number(3) not null,
  TIPO         varchar2(1) not null,
  ESPRESSIONE  varchar2(500) not null
)
tablespace LAVORO
  pctfree 10 pctused 70
  storage (initial 32K next 128K minextents 1 pctincrease 0);

alter table T909_DATICALCOLATI
  add constraint T909_PK primary key (APPLICAZIONE,NOME)
  using index tablespace INDICI pctfree 10
  storage (initial 32K next 128K minextents 1 pctincrease 0);

alter table T162_INDENNITA add TURNO1 number(1) default 0;
alter table T162_INDENNITA add TURNO2 number(1) default 0;
alter table T162_INDENNITA add TURNO3 number(1) default 0;
alter table T162_INDENNITA add TURNO4 number(1) default 0;

alter table SG101_FAMILIARI add MATRICOLA varchar2(8);

CREATE TABLE T046_GIUSTIFICATIVIFAMILIARI (
  PROGRESSIVO NUMBER, 
  DATA DATE, 
  CAUSALE VARCHAR2(5),
  DATANAS DATE,
  TIPOGIUST VARCHAR2(1),
  DAORE VARCHAR2(5),
  AORE VARCHAR2(5))
TABLESPACE LAVORO PCTFREE 10 PCTUSED 80 
STORAGE (INITIAL 32K NEXT 128K PCTINCREASE 0);

ALTER TABLE T046_GIUSTIFICATIVIFAMILIARI ADD CONSTRAINT T046_PK
PRIMARY KEY (PROGRESSIVO,DATA,CAUSALE,TIPOGIUST) 
USING INDEX TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 128K PCTINCREASE 0);

ALTER TABLE MONDOEDP.I090_ENTI MODIFY DESCRIZIONE VARCHAR2(150);

ALTER TABLE T670_REGOLEBUONI ADD MISSIONI VARCHAR2(1) DEFAULT 'S';

CREATE TABLE T004_IMMAGINI (
  TIPO VARCHAR2(10),
  IMMAGINE LONG RAW)
TABLESPACE LAVORO PCTFREE 10 PCTUSED 80 
STORAGE (INITIAL 64K NEXT 256K PCTINCREASE 0);

ALTER TABLE T004_IMMAGINI ADD CONSTRAINT T004_PK
PRIMARY KEY (TIPO) 
USING INDEX TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 32K PCTINCREASE 0);

ALTER TABLE T950_STAMPACARTELLINO ADD RAGIONE_SOCIALE VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T950_STAMPACARTELLINO ADD DATA_STAMPA VARCHAR2(40) DEFAULT 'dd/mm/yyyy hh.nn';
ALTER TABLE T950_STAMPACARTELLINO ADD NUM_PAGINE VARCHAR2(1) DEFAULT 'S';
ALTER TABLE T950_STAMPACARTELLINO ADD MARGINE_SUP NUMBER(3) DEFAULT 5;
ALTER TABLE T950_STAMPACARTELLINO ADD LOGO_LARGHEZZA NUMBER(3) DEFAULT 0;
UPDATE T950_STAMPACARTELLINO  SET DATA_STAMPA = '"Stampa del" dd/mm/yyyy hh.nn.ss';
