ALTER TABLE I010_CAMPIANAGRAFICI ADD RICERCA NUMBER (3) DEFAULT 999;
UPDATE I010_CAMPIANAGRAFICI SET RICERCA = NULL WHERE NOME_CAMPO = 'T430PROGRESSIVO';
UPDATE I010_CAMPIANAGRAFICI SET RICERCA = 990 WHERE SUBSTR(NOME_CAMPO,1,4) <> 'T430';
UPDATE I010_CAMPIANAGRAFICI SET RICERCA = 995 WHERE SUBSTR(NOME_CAMPO,1,4) = 'T430' AND SUBSTR(NOME_CAMPO,5,40) IN (SELECT NOMECAMPO FROM I500_DATILIBERI);
UPDATE I010_CAMPIANAGRAFICI SET RICERCA = 995 WHERE SUBSTR(NOME_CAMPO,1,6) = 'T430D_' AND SUBSTR(NOME_CAMPO,7,40) IN (SELECT NOMECAMPO FROM I500_DATILIBERI);

UPDATE I010_CAMPIANAGRAFICI SET NOME_LOGICO = SUBSTR(NOME_LOGICO,5,40) WHERE 
  NOME_LOGICO = NOME_CAMPO AND
  NOME_CAMPO <> 'T430PROGRESSIVO' AND
  SUBSTR(NOME_LOGICO,1,4) = 'T430';
UPDATE I010_CAMPIANAGRAFICI SET NOME_LOGICO = SUBSTR(NOME_LOGICO,3,40) || ' desc' WHERE 
  SUBSTR(NOME_LOGICO,1,2) = 'D_';

INSERT INTO MONDOEDP.I091_DATIENTE (AZIENDA,TIPO,DATO) SELECT AZIENDA,'C9_SCARICOPAGHE','CONTRATTO' FROM MONDOEDP.I090_ENTI T1 WHERE NOT EXISTS (SELECT 'X' FROM MONDOEDP.I091_DATIENTE WHERE AZIENDA = T1.AZIENDA AND TIPO = 'C9_SCARICOPAGHE');
UPDATE MONDOEDP.I091_DATIENTE SET DATO = 'CONTRATTO' WHERE TIPO = 'C9_SCARICOPAGHE' AND DATO IS NULL;

UPDATE T192_PARPAGHEDATI SET DEF = '-DECODE' WHERE DEF IN ('-2/1','-2');

ALTER TABLE T195_VOCIVARIABILI ADD COD_INTERNO VARCHAR2(4);
ALTER TABLE T195_VOCIVARIABILI ADD DATA_CASSA DATE;
UPDATE T195_VOCIVARIABILI SET UM = 'N' WHERE UM = 'G';

UPDATE T195_VOCIVARIABILI SET COD_INTERNO = 
  (SELECT MIN(CODINTERNO) FROM T190_INTERFACCIAPAGHE WHERE VOCE_PAGHE = VOCEPAGHE) 
  WHERE EXISTS (SELECT 'X' FROM T190_INTERFACCIAPAGHE WHERE VOCE_PAGHE = VOCEPAGHE);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '030' WHERE VOCEPAGHE IN 
  (SELECT DISTINCT PORE_LAV FROM T210_MAGGIORAZIONI);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '040' WHERE VOCEPAGHE IN 
  (SELECT DISTINCT PIND_TUR FROM T210_MAGGIORAZIONI);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '060' WHERE VOCEPAGHE IN 
  (SELECT DISTINCT PSTR_NEL_MESE FROM T210_MAGGIORAZIONI);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '200' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE1 FROM T305_CAUGIUSTIF UNION 
   SELECT VOCEPAGHE2 FROM T305_CAUGIUSTIF UNION 
   SELECT VOCEPAGHE3 FROM T305_CAUGIUSTIF UNION 
   SELECT VOCEPAGHE4 FROM T305_CAUGIUSTIF);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '032' WHERE VOCEPAGHE IN 
  (SELECT DISTINCT PORE_COMP FROM T210_MAGGIORAZIONI);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '230' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE1 FROM T275_CAUPRESENZE UNION 
   SELECT VOCEPAGHE2 FROM T275_CAUPRESENZE UNION 
   SELECT VOCEPAGHE3 FROM T275_CAUPRESENZE UNION 
   SELECT VOCEPAGHE4 FROM T275_CAUPRESENZE);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '160' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHELIQ1 FROM T275_CAUPRESENZE UNION 
   SELECT VOCEPAGHELIQ2 FROM T275_CAUPRESENZE UNION 
   SELECT VOCEPAGHELIQ3 FROM T275_CAUPRESENZE UNION 
   SELECT VOCEPAGHELIQ4 FROM T275_CAUPRESENZE);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '250' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE FROM T276_VOCIPAGHEPRESENZA);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '170' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE FROM T265_CAUASSENZE) AND 
  EXISTS (SELECT 'X' FROM T190_INTERFACCIAPAGHE WHERE CODINTERNO = '170' AND FLAG = 'S');
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '180' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE FROM T265_CAUASSENZE) AND 
  EXISTS (SELECT 'X' FROM T190_INTERFACCIAPAGHE WHERE CODINTERNO = '180' AND FLAG = 'S');
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '150' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE FROM T162_INDENNITA);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '240' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE FROM T760_REGOLEINCENTIVI);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '100' WHERE VOCEPAGHE IN 
  (SELECT VOCEPAGHE1 FROM T360_TERMENSA UNION SELECT VOCEPAGHE2 FROM T360_TERMENSA);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '424' WHERE VOCEPAGHE IN 
  (SELECT CODICEVOCEPAGHE FROM M020_TIPIRIMBORSI);
UPDATE T195_VOCIVARIABILI SET COD_INTERNO = '426' WHERE VOCEPAGHE IN 
  (SELECT CODICEVOCEPAGHEINDENNITASUPPL FROM M020_TIPIRIMBORSI);
    
UPDATE T195_VOCIVARIABILI SET DATA_CASSA = DATARIF WHERE DATARIF <= TO_DATE('31121999','DDMMYYYY');
UPDATE T195_VOCIVARIABILI SET DATA_CASSA = DATARIF WHERE DATARIF BETWEEN TO_DATE('01012000','DDMMYYYY') AND TO_DATE('30062000','DDMMYYYY');
UPDATE T195_VOCIVARIABILI SET DATA_CASSA = DATARIF WHERE DATARIF BETWEEN TO_DATE('01072000','DDMMYYYY') AND TO_DATE('31122000','DDMMYYYY');
UPDATE T195_VOCIVARIABILI SET DATA_CASSA = DATARIF WHERE DATARIF BETWEEN TO_DATE('01012001','DDMMYYYY') AND TO_DATE('30062001','DDMMYYYY');
UPDATE T195_VOCIVARIABILI SET DATA_CASSA = DATARIF WHERE DATARIF BETWEEN TO_DATE('01072001','DDMMYYYY') AND TO_DATE('31122001','DDMMYYYY');
UPDATE T195_VOCIVARIABILI SET DATA_CASSA = DATARIF WHERE DATARIF >= TO_DATE('01012002','DDMMYYYY');
ALTER TABLE T195_VOCIVARIABILI STORAGE (NEXT 3M PCTINCREASE 0);
ALTER TABLE T195_VOCIVARIABILI DROP CONSTRAINT T195_PK;
ALTER TABLE T195_VOCIVARIABILI ADD CONSTRAINT T195_PK 
  PRIMARY KEY(PROGRESSIVO,DATARIF,VOCEPAGHE,DATA_CASSA,DAL,OPERAZIONE)
  USING INDEX TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 3M PCTINCREASE 0);

DROP TABLE T195_BACKUP;
CREATE TABLE T195_BACKUP STORAGE (INITIAL 32K NEXT 3M PCTINCREASE 0) AS SELECT * FROM T195_VOCIVARIABILI;

ALTER TABLE T762_INCENTIVIMATURATI ADD TIPO VARCHAR2(1);
UPDATE T762_INCENTIVIMATURATI SET TIPO = (SELECT MAX(TIPO) FROM T760_REGOLEINCENTIVI);

create table T193_VOCIPAGHENEGATIVE
(
  VOCE_PAGHE VARCHAR2(6),
  VOCE_PAGHE_NEGATIVA VARCHAR2(6)
)
  tablespace LAVORO pctfree 10 pctused 70 initrans 1 maxtrans 255
  storage (initial 32K next 32K minextents 1 pctincrease 0);

alter table T193_VOCIPAGHENEGATIVE
  add constraint T193_PK primary key (VOCE_PAGHE)
  using index tablespace INDICI pctfree 10 initrans 2 maxtrans 255
  storage (initial 32K next 32K minextents 1 pctincrease 0);

ALTER TABLE T670_REGOLEBUONI ADD CONGUAGLIO_MAX NUMBER(3);
ALTER TABLE T670_REGOLEBUONI ADD PERIODICITA_ACQUISTO VARCHAR2(12) DEFAULT 'SSSSSSSSSSSS';
ALTER TABLE T670_REGOLEBUONI ADD ACQUISTO_TEORICO VARCHAR2(1) DEFAULT 'A';
ALTER TABLE T670_REGOLEBUONI ADD HHMIN_ACQUISTO VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T670_REGOLEBUONI ADD ASSENZE_ACQUISTO VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T670_REGOLEBUONI ADD MEDIAMAX_ACQUISTO NUMBER(2) DEFAULT '2';
ALTER TABLE T670_REGOLEBUONI ADD MEDIAMIN_ACQUISTO NUMBER(2) DEFAULT '1';

ALTER TABLE T690_ACQUISTOBUONI ADD BUONI_AUTO NUMBER(3);
ALTER TABLE T690_ACQUISTOBUONI ADD TICKET_AUTO NUMBER(3);
ALTER TABLE T690_ACQUISTOBUONI ADD BUONI_RECUPERATI NUMBER(3);
ALTER TABLE T690_ACQUISTOBUONI ADD TICKET_RECUPERATI NUMBER(3);
ALTER TABLE T690_ACQUISTOBUONI ADD NOTE VARCHAR2(40);

UPDATE T911_DATIRIEPILOGO SET NOME = REPLACE(NOME,'Buoni mensa','Buoni pasto') WHERE INSTR(NOME,'Buoni mensa') > 0;
UPDATE T912_SORTRIEPILOGO SET NOME = REPLACE(NOME,'Buoni mensa','Buoni pasto') WHERE INSTR(NOME,'Buoni mensa') > 0;

ALTER TABLE T360_TERMENSA ADD ORE_MINIME VARCHAR2(5) DEFAULT '00.00';

alter table M010_PARAMETRICONTEGGIO add TIPO varchar2(1) default 'P' not null;
comment on column M010_PARAMETRICONTEGGIO.TIPO is 'Tipo di arrondamento per il campo ARROTONDAMENTOORE';

ALTER TABLE T025_CONTMENSILI ADD RECUPERODEBITO_MAX VARCHAR2(7) DEFAULT '9999.59';
