ALTER TABLE MONDOEDP.IA100_STRUTTUREDATI ADD LOG_MODIFICA VARCHAR2(1) DEFAULT 'N';
comment on column MONDOEDP.IA100_STRUTTUREDATI.LOG_MODIFICA  is 'Log integrazione modificabile';

ALTER TABLE T265_CAUASSENZE MODIFY VOCEPAGHE VARCHAR2(10);
ALTER TABLE T193_VOCIPAGHE_PARAMETRI MODIFY VOCE_PAGHE VARCHAR2(10);

