create table T269_RELAZIONI_ATTESTATIINPS
(
  codice            VARCHAR2(20) not null,
  filtro            VARCHAR2(2000),
  caus_inserimento  VARCHAR2(5),
  caus_provvisoria  VARCHAR2(5),
  caus_ricovero     VARCHAR2(5),
  caus_postricovero VARCHAR2(5),
  caus_salvavita    VARCHAR2(5),
  caus_servizio     VARCHAR2(5),
  postricovero_auto VARCHAR2(1) default 'N'  
)
tablespace LAVORO 
storage (initial 256K next 256K pctincrease 0);

comment on column T269_RELAZIONI_ATTESTATIINPS.POSTRICOVERO_AUTO is 'S=attivazione del riconoscimento automatico del post-ricovero o convalescenza se consecutivo a periodo di ricovero già esistente';

alter table T269_RELAZIONI_ATTESTATIINPS
  add constraint T269_PK primary key (CODICE)
  using index tablespace INDICI 
  storage (initial 256K next 256K pctincrease 0);
  
declare 
  cursor c1 is
    select 
      T001a.VALORE CAUSALE,T001b.VALORE CAUSALE_ALL,T001c.VALORE CAUSRICOVERO,T001d.VALORE CAUSSERVIZIO,T001e.VALORE POSTRICOVERO,T001f.VALORE TSALVAVITA
      from T001_PARAMETRIFUNZIONI T001a,T001_PARAMETRIFUNZIONI T001b,T001_PARAMETRIFUNZIONI T001c,T001_PARAMETRIFUNZIONI T001d,T001_PARAMETRIFUNZIONI T001e,T001_PARAMETRIFUNZIONI T001f
    where T001a.PROG = 'A087'
      and T001a.UTENTE is not null
      and T001a.NOME = 'DBCMBCAUSALE'
      and T001b.PROG(+) = T001a.PROG
      and T001b.UTENTE(+) = T001a.UTENTE
      and T001b.NOME(+) = 'DBCMBCAUSALE_ALL'
      and T001c.PROG(+) = T001a.PROG
      and T001c.UTENTE(+) = T001a.UTENTE
      and T001c.NOME(+) = 'DBCMBCAUSRICOVERO'
      and T001d.PROG(+) = T001a.PROG
      and T001d.UTENTE(+) = T001a.UTENTE
      and T001d.NOME(+) = 'DBCMBCAUSSERVIZIO'
      and T001e.PROG(+) = T001a.PROG
      and T001e.UTENTE(+) = T001a.UTENTE
      and T001e.NOME(+) = 'DBCMBPOSTRICOVERO'
      and T001f.PROG(+) = T001a.PROG
      and T001f.UTENTE(+) = T001a.UTENTE
      and T001f.NOME(+) = 'DBCMBTSALVAVITA' 
      and decode(T001a.VALORE,null,0,1) + decode(T001b.VALORE,null,0,1) + decode(T001c.VALORE,null,0,1) + decode(T001d.VALORE,null,0,1) + decode(T001e.VALORE,null,0,1) + decode(T001f.VALORE,null,0,1) > 0 
      and T001a.VALORE is not null
    group by 
      T001a.VALORE,T001b.VALORE,T001c.VALORE,T001d.VALORE,T001e.VALORE,T001f.VALORE,
      decode(T001a.VALORE,null,0,1) + decode(T001b.VALORE,null,0,1) + decode(T001c.VALORE,null,0,1) + decode(T001d.VALORE,null,0,1) + decode(T001e.VALORE,null,0,1) + decode(T001f.VALORE,null,0,1)
    order by 
       decode(T001a.VALORE,null,0,1) + decode(T001b.VALORE,null,0,1) + decode(T001c.VALORE,null,0,1) + decode(T001d.VALORE,null,0,1) + decode(T001e.VALORE,null,0,1) + decode(T001f.VALORE,null,0,1) desc, count(*) desc;

  wfiltro varchar2(100);
  wcodice varchar2(100);
begin
  wfiltro:='(1<>1)/*predefinito*/';
  for t1 in c1 loop
    select min(T001a.UTENTE) into wcodice 
    from T001_PARAMETRIFUNZIONI T001a,T001_PARAMETRIFUNZIONI T001b,T001_PARAMETRIFUNZIONI T001c,T001_PARAMETRIFUNZIONI T001d,T001_PARAMETRIFUNZIONI T001e,T001_PARAMETRIFUNZIONI T001f
    where T001a.PROG = 'A087'
      and T001a.UTENTE is not null
      and T001a.NOME = 'DBCMBCAUSALE'
      and T001b.PROG(+) = T001a.PROG
      and T001b.UTENTE(+) = T001a.UTENTE
      and T001b.NOME(+) = 'DBCMBCAUSALE_ALL'
      and T001c.PROG(+) = T001a.PROG
      and T001c.UTENTE(+) = T001a.UTENTE
      and T001c.NOME(+) = 'DBCMBCAUSRICOVERO'
      and T001d.PROG(+) = T001a.PROG
      and T001d.UTENTE(+) = T001a.UTENTE
      and T001d.NOME(+) = 'DBCMBCAUSSERVIZIO'
      and T001e.PROG(+) = T001a.PROG
      and T001e.UTENTE(+) = T001a.UTENTE
      and T001e.NOME(+) = 'DBCMBPOSTRICOVERO'
      and T001f.PROG(+) = T001a.PROG
      and T001f.UTENTE(+) = T001a.UTENTE
      and T001f.NOME(+) = 'DBCMBTSALVAVITA' 
      and nvl(T001a.VALORE,' ') = nvl(t1.CAUSALE,' ')
      and nvl(T001b.VALORE,' ') = nvl(t1.CAUSALE_ALL,' ')
      and nvl(T001c.VALORE,' ') = nvl(t1.CAUSRICOVERO,' ')
      and nvl(T001d.VALORE,' ') = nvl(t1.CAUSSERVIZIO,' ')
      and nvl(T001e.VALORE,' ') = nvl(t1.POSTRICOVERO,' ')
      and nvl(T001f.VALORE,' ') = nvl(t1.TSALVAVITA,' ');
    
    insert into T269_RELAZIONI_ATTESTATIINPS (CODICE,FILTRO,CAUS_INSERIMENTO,CAUS_PROVVISORIA,CAUS_RICOVERO,CAUS_POSTRICOVERO,CAUS_SALVAVITA,CAUS_SERVIZIO)
    values (wcodice,wfiltro,t1.causale,t1.causale_all,t1.causricovero,t1.postricovero,t1.tsalvavita,t1.causservizio);
    wfiltro:='(1<>1)';
  end loop;
end;
/  

-- Creazione stampa _ASSPRESL104
INSERT INTO T910_RIEPILOGO
(CODICE,TITOLO,APPLICAZIONE,TIPO,SEPARAH,SEPARAV,FONTNAME,FONTSIZE,SALTOPAGINA,TOTALI,TOTPARZIALI,TOTGENERALI,CONTEGGIGIORNALIERI,FILTROESCLUSIVO,VALORENULLO,IMPOSTAZIONI,STAMPA_TITOLO,STAMPA_AZIENDA,STAMPA_PERIODO,STAMPA_NUMPAG,STAMPA_DATA,FORMATO_PAGINA,ORIENTAMENTO_PAGINA,TABELLA_GENERATA,TOTRIEPILOGO,CDC_PERCENTUALIZZATI,INTESTAZIONE_COLONNE,FILTRO_INSERVIZIO,SALTOPAGINA_TOTALI,TABELLA_GENERATA_DROP,TABELLA_GENERATA_KEY,TABELLA_GENERATA_DELETE,STAMPA_BLOCCATA,DATA_ACCESSO,UTENTE_ACCESSO,QUERY_INTESTAZIONE,QUERY_FINESTAMPA)
VALUES
('_ASSPRESL104','Statistica assenteismo e utilizzo forza lavoro L.104/1992','RILPRE','C','N','N','Courier New',8,'N','N','S','S','N','N','S','REC_SINDACATO_11=,REC_SINDACATO_12=,REC_SINDACATO_13=','S','S','S','S','S','1','O','ASSPRESL104','S','N','N','1','N','S','','','N',TO_DATE('04/12/2013 14.21.49','DD/MM/YYYY HH24.MI.SS'),'SYSMAN','','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Assenza:U.M.Fruizione','U.M.','D','N',0,1292,40,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Assenza:causale','Causale','D','N',0,1020,50,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Assenza:data familiare','Familiare','D','N',0,1204,80,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Assenza:giornate','GG Ass.','D','N',0,1136,60,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Assenza:ore rese','HH Ass.','D','N',0,1072,60,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','DATANAS','DATANAS','D','N',0,72,80,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','DC_GGLAVORATIVO','LAVORATIVO','D','N',0,1432,80,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','DC_OREDEBITO','OREDEBITO','D','N',0,1512,80,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Data conteggio','Data','D','N',0,944,70,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Debito settimanale','Debito settimanale','D','N',0,1336,40,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','Giorni lavorativi','Giorni lavorativi','D','N',0,1384,40,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','MATRICOLA','MATR.','D','N',0,0,50,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','SESSO','SESSO','D','N',0,56,8,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430DC_COMUNENAS','COMUNENAS','D','N',0,160,80,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430DC_COMUNERES','COMUNERES','D','N',0,248,80,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430DC_DURATACONTR','DURATACONTR','D','N',0,528,60,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430DC_INQUADRAMENTO','INQUADRAMENTO','D','N',0,336,100,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430DC_PERCPT','PERCPT','D','N',0,728,60,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430DC_TIPOCONTR','TIPOCONTR','D','N',0,600,60,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430DC_TIPOPT','TIPOPT','D','N',0,664,60,16,'','N','N','N','');
INSERT INTO T911_DATIRIEPILOGO (CODICE,NOME,CAPTION,BANDA,TOTALE,POST,POSL,LUNG,ALT,FORMATO,CONTATORE,CDC_PERCENTUALIZZATI,CONV_VALUTA,RIPETUTO) VALUES
('_ASSPRESL104','T430INIZIO','ASSUNZIONE','D','N',0,444,80,16,'','N','N','N','');
INSERT INTO T912_SORTRIEPILOGO (CODICE,POS,NOME,TIPO,ROTTKEY) VALUES
('_ASSPRESL104',0,'MATRICOLA','C','N');
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO,POS,DATO,TOTALE) VALUES
('_ASSPRESL104',4,'0','Data conteggio','N');
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO,POS,DATO,TOTALE) VALUES
('_ASSPRESL104',4,'1','Assenza:causale','N');
INSERT INTO T913_SERBATOIKEY (CODICE,ID_SERBATOIO,POS,DATO,TOTALE) VALUES
('_ASSPRESL104',4,'2','Assenza:data familiare','N');
DELETE FROM T909_DATICALCOLATI WHERE APPLICAZIONE = 'RILPRE' AND NOME = 'T430DC_INQUADRAMENTO';
INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','T430DC_INQUADRAMENTO',0,'0','DECODE(T430CONTRATTO,''DIR1'',''1'',''DIR2'',''2'',''DIR'',''3'',''COMP'',''4'')','');
DELETE FROM T909_DATICALCOLATI WHERE APPLICAZIONE = 'RILPRE' AND NOME = 'T430DC_COMUNENAS';
INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','T430DC_COMUNENAS',0,'0','T480F_CODCATASTALE(COMUNENAS)','');
DELETE FROM T909_DATICALCOLATI WHERE APPLICAZIONE = 'RILPRE' AND NOME = 'T430DC_COMUNERES';
INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','T430DC_COMUNERES',0,'0','T480F_CODCATASTALE(T430COMUNE)','');
DELETE FROM T909_DATICALCOLATI WHERE APPLICAZIONE = 'RILPRE' AND NOME = 'T430DC_DURATACONTR';
INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','T430DC_DURATACONTR',0,'0','DECODE(GETTIPORAPPORTO(T430TIPORAPPORTO),''R'',''1'',''2'')','');
DELETE FROM T909_DATICALCOLATI WHERE APPLICAZIONE = 'RILPRE' AND NOME = 'T430DC_PERCPT';
INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','T430DC_PERCPT',0,'0','DECODE(NVL(T430PARTTIME,''X''),''X'','''', DECODE(GETPERCPART(T430PARTTIME,''PIANTA''),''100'','''',  GETPERCPART(T430PARTTIME,''PIANTA'')))','');
DELETE FROM T909_DATICALCOLATI WHERE APPLICAZIONE = 'RILPRE' AND NOME = 'T430DC_TIPOCONTR';
INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','T430DC_TIPOCONTR',0,'0','DECODE(NVL(T430PARTTIME,''X''),''X'',''1'',DECODE(GETPERCPART(T430PARTTIME,''PIANTA''),''100'',''1'',''2''))','');
DELETE FROM T909_DATICALCOLATI WHERE APPLICAZIONE = 'RILPRE' AND NOME = 'T430DC_TIPOPT';
INSERT INTO T909_DATICALCOLATI (APPLICAZIONE,NOME,ID_SERBATOIO,TIPO,ESPRESSIONE,CODICE_STAMPA) VALUES
('RILPRE','T430DC_TIPOPT',0,'0','DECODE(NVL(T430PARTTIME,''X''),''X'','''', DECODE(GETPERCPART(T430PARTTIME,''PIANTA''),''100'','''', DECODE(GETPERCPART(T430PARTTIME,''TIPO''),''O'',''1'',''V'',''2'',''3'')))','');
UPDATE T909_DATICALCOLATI SET CODICE_STAMPA='' WHERE APPLICAZIONE='RILPRE' AND NOME='DC_GGLAVORATIVO';
UPDATE T909_DATICALCOLATI SET CODICE_STAMPA='' WHERE APPLICAZIONE='RILPRE' AND NOME='DC_OREDEBITO';

CREATE OR REPLACE
function T480F_CODCATASTALE (PCodComune in varchar2) return varchar2 is
  CodCatastale varchar2(4);
begin
  select T480.CODCATASTALE into CodCatastale
    from T480_COMUNI T480
    where T480.CODICE=PCodComune;
  return CodCatastale;
exception
  when others then
    return '';
end;
/
CREATE OR REPLACE
function GetTipoRapporto(Cod in varchar2) return varchar2 is
  Result varchar2(1);
begin
  Result:='';
  select TIPO
    into Result
    from T450_TIPORAPPORTO
   where codice = cod;
  Return(Result);
end GetTipoRapporto;
/
CREATE OR REPLACE
function GetPercPart(Cod in varchar2, Dato in varchar2) return varchar2 is
  cursor c1 is
    select * from t460_parttime t460
    where codice = Cod;
begin
  for t1 in c1 loop
      if upper(Dato) = 'PIANTA' then
        return(t1.pianta);
      elsif upper(Dato) = 'INDPRES' then
        return(t1.indpres);
      elsif upper(Dato) = 'INCENTIVI' then
        return(t1.incentivi);
      elsif upper(Dato) = 'ASSENZEGG' then
        return(t1.assenzegg);
      elsif upper(Dato) = 'ASSENZEHH' then
        return(t1.assenzehh);
      elsif upper(Dato) = 'INDFEST' then
        return(t1.indfest);
      elsif upper(Dato) = 'TIPO' then
        return(t1.tipo);
      end if;
  end loop;
  return(Null);
end GetPercPart;
/

-- Creazione estrazione MONANNL104 per la legge 104/1992
INSERT INTO t151_assenteismo
  (codice, descrizione, cod_tipoaccorpcausali, cod_codiciaccorpcausali, modo_accorpcausali, stampa_generatore, righe, righe_vuote, dettaglio_dip, colonne, numdip_periodo, 
numdip_arrot, presenza_gglav, presenza_arrot, assenza_gglav, assenza_qm, assenza_ggint, assenza_arrot, riepilogo_arrot, ass_familiari, 
ass_fruizione_gg, ass_fruizione_mg, ass_fruizione_hh, ass_fruizione_dh, ass_maxperiodo_gg, ass_debito_ggint, totale_generale, esporta_xml,ass_dettaglio)
VALUES
  ('MONANNL104', 'MONITORAGGIO ANNUALE LEGGE 104/1992', '', '', 'T', '_ASSPRESL104', 
'001#T430DC_INQUADRAMENTO,002#T430INIZIO,003#T430DC_DURATACONTR,004#T430DC_TIPOCONTR,005#T430DC_TIPOPT,006#T430DC_PERCPT,007#T430DC_COMUNERES,008#DATANAS,009#T430DC_COMUNENAS,010#SESSO', 
'N', 'S', '304,305', 'F', 
'N', 'N', 'N', 'S', 'N', 'N', 'N', 'N', 'S', 
'S', 'S', 'S', 'S', 9999, 'C', 'S', 'L','S');

-- Eliminazione gestione nazionalità estere su P430
DELETE P121_NAZIONALITAESTERE;
ALTER TABLE P430_ANAGRAFICO DROP CONSTRAINT P430_FK_P121;
comment on column P430_ANAGRAFICO.COD_NAZIONALITAESTERE  is 'Non gestito';

-- Correzione formato data di GiornoInizio e GiornoFine inseriti manualmente sull'UNIEMENS
UPDATE P673_XMLDATIINDIVIDUALI T SET T.VALORE=TRIM(TO_CHAR(TO_DATE(T.VALORE,'YYYY-MM-DD')))
where t.numero in('F005','F010','H005','H010') and INSTR(t.valore,'/')=0;

-- Rimozione P205.COD_VOCE_SPECIALE_DETTAGLIO e attivazione Riduce i giorni delle voci in quota
-- per assenze 15075 e 15115
UPDATE P205_QUOTE t SET T.COD_VOCE_SPECIALE_DETTAGLIO=''
WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE_DA_QUOTARE IN('15075','15115');

UPDATE P200_VOCI t SET T.NO_CEDOLINO_NORMALE='S'
WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE IN('15075','15115');

-- *********************************************************************************
-- CREAZIONE SCAGLIONI DI INIZIO ANNO E NUOVE PERCENTUALI
-- PER VOCI RELATIVE A CPDEL, CPS, ENPAM EX CONVENZIONATI,
-- INPGI, OPTANTI INPS, PERSONALE RELIGIOSO INPS E GESTIONE SEPARATA INPS
-- ****************  2014 (FATTO SU SQL PATCH) ****************
-- *********************************************************************************

declare 
  i integer;
  AnnoNuovo integer;
  CodVoce varchar2(5);
  CodVoceSpeciale varchar2(5);
  PercDipCP_1 real;
  PercDipCP_2 real;
  PercDipGI_1 real;
  PercDipGI_2 real;
  PercDipIN_1 real;
  PercDipIN_2 real;
  PercDipINRel_1 real;
  PercDipINRel_2 real;
  PercDip11110 real;
  PercEnte11115 real;
  PercDip11120 real;
  PercEnte11125 real;
  PercDip11130 real;
  PercEnte11135 real;
  ID_P233 integer;

  CURSOR C1 IS  
  SELECT '11010' AS COD_VOCE, 'BASE' AS COD_VOCE_SPECIALE FROM DUAL UNION
  SELECT '11010', 'ENTE' FROM DUAL UNION
  SELECT '11020', 'BASE' FROM DUAL UNION
  SELECT '11020', 'ENTE' FROM DUAL UNION
  
  SELECT '11090', 'BASE' FROM DUAL UNION

  SELECT '11110', 'BASE' FROM DUAL UNION
  SELECT '11115', 'BASE' FROM DUAL UNION
  SELECT '11120', 'BASE' FROM DUAL UNION
  SELECT '11125', 'BASE' FROM DUAL UNION
  SELECT '11130', 'BASE' FROM DUAL UNION
  SELECT '11135', 'BASE' FROM DUAL UNION

  SELECT '11140', 'BASE' FROM DUAL UNION
  SELECT '11140', 'ENTE' FROM DUAL UNION
  SELECT '11150', 'BASE' FROM DUAL UNION
  SELECT '11150', 'ENTE' FROM DUAL UNION

  SELECT '11160', 'BASE' FROM DUAL UNION
  SELECT '11170', 'BASE' FROM DUAL UNION

  SELECT '11410', 'BASE' FROM DUAL;  

  CURSOR C2 IS  
  SELECT '11010' AS COD_VOCE, 'BASE' AS COD_VOCE_SPECIALE FROM DUAL UNION
  SELECT '11010', 'ENTE' FROM DUAL UNION
  SELECT '11020', 'BASE' FROM DUAL UNION
  SELECT '11020', 'ENTE' FROM DUAL UNION
  SELECT '11410', 'BASE' FROM DUAL;  

begin
  -- IMPOSTARE QUI IL NUOVO ANNO DA GESTIRE
  AnnoNuovo:=2014;
  
select COUNT(*) into i from P232_SCAGLIONI T
WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE='11010' AND T.COD_VOCE_SPECIALE='BASE'
AND T.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo-1),'DDMMYYYY') AND NOT EXISTS
(select 'X' from P232_SCAGLIONI V
WHERE V.COD_CONTRATTO='EDP' AND V.COD_VOCE='11010' AND V.COD_VOCE_SPECIALE='BASE'
AND V.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

if i > 0 then


  FOR T1 IN C1 LOOP
    CodVoce:=T1.COD_VOCE;
    CodVoceSpeciale:=T1.COD_VOCE_SPECIALE;
    
    SELECT P233_ID_SCAGLIONE.NEXTVAL INTO ID_P233 FROM DUAL;
   
    INSERT INTO P232_SCAGLIONI
    SELECT COD_CONTRATTO, COD_VOCE, COD_VOCE_SPECIALE, TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'), ID_P233, TIPO_IMPORTO, TIPO_RITENUTA, TIPO_APPLICAZIONE, CONGUAGLIO_ANNUALE, CONGUAGLIO_FINE_RAPPORTO, CONGUAGLIO_DOPO_FINE_RAPPORTO, COD_VOCE_CONGUAGLIO, COD_VOCE_SPECIALE_CONGUAGLIO, MENSILITA_ANNUE, MASSIMALE1, MASSIMALE2 FROM P232_SCAGLIONI P232 
    WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=CodVoce AND P232.COD_VOCE_SPECIALE=CodVoceSpeciale AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo-1),'DDMMYYYY');
  
    INSERT INTO P233_SCAGLIONIFASCE
    SELECT ID_P233, IMPORTO_DA, IMPORTO_A, PERC_IMP FROM P233_SCAGLIONIFASCE P233,P232_SCAGLIONI P232 WHERE P233.ID_SCAGLIONE=P232.ID_SCAGLIONE
    AND P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=CodVoce AND P232.COD_VOCE_SPECIALE=CodVoceSpeciale AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo-1),'DDMMYYYY');
  END LOOP;
  
  -- IMPOSTARE QUI LE NUOVE PERCENTUALI PER I DIPENDENTI CPDEL, CPS E ENPAM EX CONVENZIONATI
  PercDipCP_1:=8.85;
  PercDipCP_2:=9.85;
  -- IMPOSTARE QUI LE NUOVE PERCENTUALI PER I DIPENDENTI INPGI
  PercDipGI_1:=8.69;
  PercDipGI_2:=9.69;
  -- IMPOSTARE QUI LE NUOVE PERCENTUALI PER I DIPENDENTI OPTANTI INPS
  PercDipIN_1:=9.19;
  PercDipIN_2:=10.19;
  -- IMPOSTARE QUI LE NUOVE PERCENTUALI PER I DIPENDENTI PERSONALE RELIGIOSO INPS
  PercDipINRel_1:=8.84;
  PercDipINRel_2:=9.84;
  -- IMPOSTARE QUI LE NUOVE PERCENTUALI PER I PARASUBORDINATI CON COPERTURE ASSICURATIVE
  PercDip11110:=7.333333;
  PercEnte11115:=14.666667;
  -- IMPOSTARE QUI LE NUOVE PERCENTUALI PER I PARASUBORDINATI SENZA COPERTURE ASSICURATIVE
  PercDip11120:=9.573333;
  PercEnte11125:=19.146667;
  -- IMPOSTARE QUI LE NUOVE PERCENTUALI PER I PARASUBORDINATI PENSIONATI ANZIANITA’
  PercDip11130:=7.333333;
  PercEnte11135:=14.666667;

  FOR T2 IN C2 LOOP
    -- CPDEL, CPS E ENPAM EX CONVENZIONATI
    UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipCP_1 WHERE P233.IMPORTO_DA=0
    AND P233.ID_SCAGLIONE=
    (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=T2.COD_VOCE AND P232.COD_VOCE_SPECIALE=T2.COD_VOCE_SPECIALE AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

    UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipCP_2 WHERE P233.IMPORTO_A=0
    AND P233.ID_SCAGLIONE=
    (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE=T2.COD_VOCE AND P232.COD_VOCE_SPECIALE=T2.COD_VOCE_SPECIALE AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));
  END LOOP;

-- INPGI
  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipGI_1 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11090' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipGI_2 WHERE P233.IMPORTO_A=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11090' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));
  
-- OPTANTI INPS
  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipIN_1 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11160' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipIN_2 WHERE P233.IMPORTO_A=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11160' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));
  
-- PERSONALE RELIGIOSO INPS
  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipINRel_1 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11170' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDipINRel_2 WHERE P233.IMPORTO_A=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11170' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));
  
-- Inps con coperture assicurative
  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDip11110 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11110' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercEnte11115 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11115' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

-- Inps no coperture assicurative
  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDip11120 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11120' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercEnte11125 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11125' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

-- Inps pensionati anzianita’
  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercDip11130 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11130' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

  UPDATE P233_SCAGLIONIFASCE P233 SET PERC_IMP=PercEnte11135 WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11135' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

end if;
end;

/
 
-- *********************************************************************************
-- NUOVA PERCENTUALE CARICO ENTE PER INGI (Circolare n. 9 del 10/11/2011)
-- ****************  2014 (FATTO SU SQL PATCH) ****************
-- *********************************************************************************

declare 
  i integer;
  ID_P200 integer;
  PercEnte real;

begin
  PercEnte:=22.28;

select COUNT(*) into i from P200_VOCI T
WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE='11095' AND T.COD_VOCE_SPECIALE='BASE'
AND T.DECORRENZA=TO_DATE('01012012','DDMMYYYY') AND NOT EXISTS
(select 'X' from P200_VOCI V
WHERE V.COD_CONTRATTO='EDP' AND V.COD_VOCE='11095' AND V.COD_VOCE_SPECIALE='BASE'
AND V.DECORRENZA=TO_DATE('01012014','DDMMYYYY'));

if i > 0 then

  SELECT P200_ID_VOCE.NEXTVAL INTO ID_P200 FROM DUAL;
    
  insert into p200_voci
  select cod_contratto, cod_voce, cod_voce_speciale, TO_DATE('01012014','DDMMYYYY'), ID_P200, descrizione, cod_voce_stampa, descrizione_stampa, protetta, tipo, rid_mese_ass_cess, cassa_competenza, voce_importo, importo_automatico, importo_automatico_tipo, importo, importo_colonna, voce_quantita, cod_misuraquantita, ritenuta_massimali_scaglioni, PercEnte, imponibile_minimali, cod_arrotondamento, perc_matura13a, mostra_video, confronto_mensile, stampa_cedolino, stampa_competenza, stampa_competenza_quote, cod_causaleirpef, ridotta_parttime_vert, ridotta_parttime_orizz, no_cedolino_normale, forza_ggcalcolo_quote, abbatte_ggminimali, abbatte_ggdetraz_caricofam, abbatte_ggdetraz_lavdip, abbatte_gganf, cumulo_annuale_cedolone, cod_raggruppamento, perc_abbatte13a, note, cumulo_in_calcolo, cod_voce_link_assog, cod_voce_speciale_link_assog, divisore_quote, abbatte_gginp, abbatte_ggina, programmata, oneri_detrazioni, eccezioni_sensibili, cod_raggruppamento_assogg, retribuzione_contrattuale,ritenuta_anagrafica,decorrenza_fine,cod_beneficiario,importo_massimo from p200_voci t
  WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE='11095' AND T.COD_VOCE_SPECIALE='BASE'
  AND T.DECORRENZA=TO_DATE('01012012','DDMMYYYY');

  UPDATE p200_voci t SET T.DECORRENZA_FINE=TO_DATE('01012014','DDMMYYYY')-1
  WHERE T.COD_CONTRATTO='EDP' AND T.COD_VOCE='11095' AND T.COD_VOCE_SPECIALE='BASE'
  AND T.DECORRENZA=TO_DATE('01012012','DDMMYYYY');

end if;
end;
/

-- *********************************************************************************
-- IMPOSTAZIONE PROVVISORIA NUOVO SCAGLIONE PER INPGI
-- ****************  2014 ****************
-- *********************************************************************************

declare 
  AnnoNuovo integer;
  Scaglione real;

begin
  -- IMPOSTARE QUI IL NUOVO ANNO DA GESTIRE
  AnnoNuovo:=2014;
  -- IMPOSTARE QUI IL NUOVO SCAGLIONE PER MAGGIORAZIONE 1%
  Scaglione:=44655;

  UPDATE P233_SCAGLIONIFASCE P233 SET IMPORTO_A=Scaglione WHERE P233.IMPORTO_DA=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11090' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));

  UPDATE P233_SCAGLIONIFASCE P233 SET IMPORTO_DA=Scaglione+0.01 WHERE P233.IMPORTO_A=0
  AND P233.ID_SCAGLIONE=
  (SELECT P232.ID_SCAGLIONE FROM P232_SCAGLIONI P232 WHERE P232.COD_CONTRATTO='EDP' AND P232.COD_VOCE='11090' AND P232.COD_VOCE_SPECIALE='BASE' AND P232.DECORRENZA=TO_DATE('0101'||TO_CHAR(AnnoNuovo),'DDMMYYYY'));
 
end;
/
