CREATE OR REPLACE PROCEDURE TIMB_TRIGGER_AFTER 
  (TABELLA IN VARCHAR2, P_PROGRESSIVO IN INTEGER, P_DATA IN DATE, P_ORA IN DATE, P_VERSO IN VARCHAR2, P_FLAG IN VARCHAR2, IN_RILEVATORE IN VARCHAR2, P_CAUSALE IN VARCHAR2) AS
BEGIN
END;
/
