ALTER TABLE T350_REGREPERIB ADD ORENONCAUS VARCHAR2(1);

ALTER TABLE T350_REGREPERIB ADD TOLLERANZA NUMBER(38,2);

ALTER TABLE T275_CAUPRESENZE Add DETREPERIB VARCHAR2(1);

ALTER TABLE T275_CAUPRESENZE Add RIPLIQ VARCHAR2(1);

ALTER TABLE T265_CAUASSENZE ADD DETREPERIB VARCHAR2(1);

ALTER TABLE T020_ORARI ADD DETRAUTCONT VARCHAR2(1);
