ALTER TABLE T192_PARPAGHEDATI DROP CONSTRAINT T192_PK;
ALTER TABLE T192_PARPAGHEDATI ADD CONSTRAINT T192_PK PRIMARY KEY (CODICE,POS) USING INDEX TABLESPACE INDICI;
ALTER TABLE T192_PARPAGHEDATI ADD NOME VARCHAR2(20);

ALTER TABLE T191_PARPAGHE ADD FORMATOORE VARCHAR2(1);
ALTER TABLE T191_PARPAGHE ADD PRECISIONE VARCHAR2(1);
