ALTER TABLE T265_CAUASSENZE ADD VOCEPAGHE2 VARCHAR2(6);
ALTER TABLE T265_CAUASSENZE ADD VOCEPAGHE3 VARCHAR2(6);
ALTER TABLE T265_CAUASSENZE ADD VOCEPAGHE4 VARCHAR2(6);
ALTER TABLE T265_CAUASSENZE ADD VOCEPAGHE5 VARCHAR2(6);
ALTER TABLE T265_CAUASSENZE ADD VOCEPAGHE6 VARCHAR2(6);

CREATE TABLE T042_PERIODIASSENZA (
  PROGRESSIVO NUMBER(8),
  CAUSALE VARCHAR2(5),
  DAL DATE,
  AL DATE,
  TIPOGIUST VARCHAR2(1),
  DAORE DATE,
  AORE DATE,
  DATA_AGG DATE,
  OPERAZIONE VARCHAR2(1),
  FLAG VARCHAR2(1)
  )
TABLESPACE LAVORO;

CREATE INDEX T042_IDX ON T042_PERIODIASSENZA (PROGRESSIVO,CAUSALE,DAL) TABLESPACE INDICI;

ALTER TABLE T190_INTPAGHE ADD P180 VARCHAR2(6);
ALTER TABLE T190_INTPAGHE ADD F180 VARCHAR2(1);

CREATE TABLE T192_PARPAGHEDATI (
  CODICE VARCHAR2(5),
  POS NUMBER(3),
  LUNG NUMBER(3),
  DEF VARCHAR2(80),
  TIPO VARCHAR2(1),
  CONSTRAINT T192_PK PRIMARY KEY (CODICE,POS) USING INDEX TABLESPACE INDICI
  ) TABLESPACE LAVORO;

RENAME T191_PARPAGHE TO T191_OLD;

CREATE TABLE MONDOEDP.T191_PARPAGHE (
  CODICE VARCHAR2(5) NOT NULL,
  DESCRIZIONE VARCHAR2(40),
  TIPOFILE VARCHAR2(1),
  DEFAULTENTE VARCHAR2(20),
  TABELLAENTE VARCHAR2(50),
  CAMPOENTE VARCHAR2(30),
  NOMEFILE VARCHAR2(80),
  DATAFILE VARCHAR2(10),
  MESEANNO VARCHAR2(10),
  CONSTRAINT T191_PK PRIMARY KEY (CODICE) USING INDEX TABLESPACE INDICI
) 
  TABLESPACE LAVORO;

INSERT INTO T191_PARPAGHE
  (CODICE,DESCRIZIONE,TIPOFILE,DEFAULTENTE,TABELLAENTE,CAMPOENTE,NOMEFILE,DATAFILE,MESEANNO)
  SELECT CODICE,DESCRIZIONE,'F',DEFAULTENTE,TABELLAENTE,CAMPOENTE,NOMEFILE,DATAFILE,MESEANNO FROM T191_OLD;

