UPDATE I090_ENTI SET PAROLACHIAVE = 'WJQT^UZ' WHERE UTENTE = 'MONDOEDP';

CREATE TABLE T002_QUERYPERSONALIZZATE (
  NOME VARCHAR2(30) NOT NULL,
  POSIZ NUMBER(2) NOT NULL,
  RIGA VARCHAR2(255),
  CONSTRAINT T002_PK PRIMARY KEY (NOME,POSIZ) USING INDEX TABLESPACE INDICI
)
TABLESPACE LAVORO;
