ALTER TABLE T195_VOCIVARIABILI ADD UM VARCHAR2(1);
ALTER TABLE T195_BACKUP ADD UM VARCHAR2(1);

CREATE TABLE T043_RIEPILOGOASSENZE (
  PROGRESSIVO NUMBER(8),
  ANNO NUMBER(4),
  MESE NUMBER(2),
  CODRAGGR VARCHAR2(5),
  UM VARCHAR2(1),
  COMPETENZEAP NUMBER,
  COMPETENZEAC NUMBER,
  FRUITO NUMBER,
  RESIDUO NUMBER,
  CONSTRAINT T043_PK PRIMARY KEY (PROGRESSIVO,ANNO,MESE,CODRAGGR) USING INDEX
  STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0) TABLESPACE INDICI
)
STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0)
TABLESPACE LAVORO;

