ALTER TABLE T910_RIEPILOGO ADD APPLICAZIONE VARCHAR2(6);
UPDATE T910_RIEPILOGO SET APPLICAZIONE = 'RILPRE';
ALTER TABLE T910_RIEPILOGO MODIFY ASSENZE VARCHAR2(300);
ALTER TABLE T910_RIEPILOGO ADD VOCI_PAGHE VARCHAR2(300);
ALTER TABLE T910_RIEPILOGO ADD IMPOSTAZIONI VARCHAR2(300);

ALTER TABLE T911_DATIRIEPILOGO ADD CONTATORE VARCHAR2(1) DEFAULT 'N';