ALTER TABLE M030_TARIFFAORARIA ADD( 
  CODICERIMBORSO VARCHAR2(5), 
  ORERIMBORSO VARCHAR2(5), 
  TARIFFARIMBORSO NUMBER);

ALTER TABLE M040_MISSIONI ADD(
  PARTENZA VARCHAR2(80),
  DESTINAZIONE VARCHAR2(80));

