ALTER TABLE T670_REGOLEBUONI ADD (
  LIMITI_SEPARATI VARCHAR2(1) DEFAULT 'N',
  ORE_MATTINA VARCHAR2(5),
  ORE_POMERIGGIO VARCHAR2(5));

ALTER TABLE T360_TERMENSA ADD MENSA_STIMBRATA VARCHAR2(1);
ALTER TABLE T360_TERMENSA ADD MENSA_NON_STIMBRATA VARCHAR2(1) DEFAULT 'N';
UPDATE T360_TERMENSA SET MENSA_STIMBRATA = TIMBDOPOUSCITA;
UPDATE T360_TERMENSA SET TIMBDOPOUSCITA = TIMBANTECENTRATA;



