UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.4.6' WHERE AZIENDA = :AZIENDA;

ALTER INDEX T340_PK STORAGE (NEXT 256K);

ALTER TABLE T164_ASSOCIAZIONIINDENNITA ADD SCADENZA DATE;
ALTER TABLE T164_ASSOCIAZIONIINDENNITA MODIFY ESPRESSIONE VARCHAR2(2000);
ALTER TABLE T164_ASSOCIAZIONIINDENNITA DROP CONSTRAINT T164_PK;
CREATE INDEX T164_CODICE ON T164_ASSOCIAZIONIINDENNITA (CODICE) TABLESPACE INDICI STORAGE (INITIAL 32K NEXT 64K PCTINCREASE 0);

ALTER TABLE T162_INDENNITA ADD PRIORITA NUMBER(8);
ALTER TABLE T162_INDENNITA ADD INDENNITA_INCOMPATIBILI VARCHAR2(200);

UPDATE T277_CAUFASCEABILITATE SET TIPO_GIORNO = 'T' WHERE TIPO_GIORNO = '*';

ALTER TABLE T370_TIMBMENSA DROP PRIMARY KEY;
ALTER TABLE T370_TIMBMENSA ADD CONSTRAINT T370_PK  PRIMARY KEY (PROGRESSIVO,DATA,ORA,FLAG) 
  USING INDEX TABLESPACE INDICI STORAGE (PCTINCREASE 0 INITIAL 32K NEXT 5M);
  
ALTER TABLE T291_PARMESSAGGI ADD TIPO_FILTRO VARCHAR2(1) DEFAULT '0';
ALTER TABLE T292_PARMESSAGGIDATI ADD CODICE_DATO VARCHAR2(50);

INSERT INTO T913_SERBATOIKEY
  (CODICE,ID_SERBATOIO,POS,DATO,TOTALE)
SELECT CODICE,9,0,'IR_Data','N' FROM T910_RIEPILOGO WHERE APPLICAZIONE = 'RILPRE';

ALTER TABLE T275_CAUPRESENZE ADD MINMINUTI NUMBER(3);
ALTER TABLE T275_CAUPRESENZE ADD TIPO_MINMINIMI VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T275_CAUPRESENZE ADD TIPO_NONAUTORIZZATE VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T275_CAUPRESENZE ADD TIPO_U_NONAUTORIZZATE VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T275_CAUPRESENZE ADD GETTONE_TIPO_ORESUP VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T275_CAUPRESENZE ADD GETTONE_TIPO_OREINF VARCHAR2(1) DEFAULT 'N';
ALTER TABLE T275_CAUPRESENZE ADD GETTONE_ORE VARCHAR2(5) DEFAULT '00.00';
ALTER TABLE T275_CAUPRESENZE ADD GETTONE_INDENNITA VARCHAR2(5);
ALTER TABLE T275_CAUPRESENZE ADD GETTONE_SPEZZONI VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T073_SCHEDACAUSPRES ADD GETTONE_RESIDUO VARCHAR2(7);

alter table T162_INDENNITA modify TURNO1 NUMBER(5,2);
alter table T162_INDENNITA modify TURNO2 NUMBER(5,2);
alter table T162_INDENNITA modify TURNO3 NUMBER(5,2);
alter table T162_INDENNITA modify TURNO4 NUMBER(5,2);

ALTER TABLE T020_ORARI MODIFY FLAGPRES DEFAULT NULL;

ALTER TABLE T191_PARPAGHE ADD SEPARATOREDECIMALI VARCHAR2(1) DEFAULT ',';
UPDATE T191_PARPAGHE SET SEPARATOREDECIMALI = '.' WHERE PRECISIONE = '2';