-- PIANTA ORGANICA
ALTER TABLE SG506_PIANTADISTRIBUZIONE ADD NUMERO_CALCOLATI NUMBER(10,2) not null;
ALTER TABLE SG506_PIANTADISTRIBUZIONE ADD PERCORSO VARCHAR2(1000) not null;
ALTER TABLE SG506_PIANTADISTRIBUZIONE DROP CONSTRAINT SGG06_FK_SG506;

UPDATE T020_ORARI SET
TUTTOCOMP = 'N',
MINSCOSTR = NULL,
ARRSCOSTR = NULL,
ARRSCOSTR_COMP = 'S',
MinimiStr = NULL,
ArrivRang = NULL,
MinGioStr = NULL,
MaxGioStr = NULL,
ArrotGior = NULL,
InterUsc = NULL,
STR_DOPO_HHMAX = 'N'
WHERE CODICE IN (SELECT CODICE FROM T020_OLD WHERE STRAORDINARIO = 'N');

DELETE FROM T021_FASCEORARI
WHERE TIPO_FASCIA = 'STR' AND
CODICE IN (SELECT CODICE FROM T020_OLD WHERE STRAORDINARIO = 'N');

UPDATE T020_ORARI T020 SET CAUOBFAC = 'O' WHERE
TIPOMENSA <> 'Z' AND NOT EXISTS 
  (SELECT 'X' FROM T021_FASCEORARI WHERE CODICE = T020.CODICE AND DECORRENZA = T020.DECORRENZA AND TIPO_FASCIA = 'PMT');

INSERT INTO T021_FASCEORARI 
  (CODICE,DECORRENZA,TIPO_FASCIA,ENTRATA,USCITA,MMANTICIPOU,MMRITARDO)
SELECT CODICE,DECORRENZA,'PMT','12.00','12.01','12.00','12.01'
FROM T020_ORARI T020 
WHERE TIPOMENSA <> 'Z' AND NOT EXISTS 
  (SELECT 'X' FROM T021_FASCEORARI WHERE CODICE = T020.CODICE AND DECORRENZA = T020.DECORRENZA AND TIPO_FASCIA = 'PMT');

ALTER TABLE T240_ORGANIZZAZIONISINDACALI MODIFY COD_MINISTERIALE VARCHAR2(4);

ALTER TABLE MONDOEDP.IA100_STRUTTUREDATI ADD SCRIPT_BEFORE VARCHAR2(500);
ALTER TABLE MONDOEDP.IA100_STRUTTUREDATI ADD SCRIPT_AFTER VARCHAR2(500);
