UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.5.1' WHERE AZIENDA = :AZIENDA;

ALTER TABLE T460_PARTTIME ADD DESCRIZIONE_ESTESA VARCHAR2(200);

ALTER TABLE T265_CAUASSENZE ADD DESCRIZIONE_ESTESA VARCHAR2(200);

ALTER TABLE SG500_DATILIBERI ADD DECODIFICA_VALORE VARCHAR2(500);
ALTER TABLE SG100_PROVVEDIMENTO MODIFY NOTE VARCHAR2(2000);

ALTER TABLE T021_FASCEORARI ADD ENTRATA_OBB VARCHAR2(5);
ALTER TABLE T021_FASCEORARI ADD USCITA_OBB VARCHAR2(5);

DECLARE
 CURSOR C1 IS
   SELECT ROWID,T021.* FROM T021_FASCEORARI T021 WHERE 
     CODICE IN (SELECT CODICE FROM T020_ORARI WHERE TIPOORA = 'C') AND
     TIPO_FASCIA = 'PN' AND 
     ENTRATA = (SELECT MIN(ENTRATA) FROM T021_FASCEORARI WHERE CODICE = T021.CODICE AND TIPO_FASCIA = 'PN') AND
     USCITA = (SELECT MIN(USCITA) FROM T021_FASCEORARI WHERE CODICE = T021.CODICE AND TIPO_FASCIA = 'PN')
     ORDER BY CODICE;
 E VARCHAR2(5);
 U VARCHAR2(5);
BEGIN
  FOR T1 IN C1 LOOP
    SELECT MAX(ENTRATA) INTO E FROM T021_FASCEORARI WHERE CODICE = T1.CODICE AND TIPO_FASCIA = 'PN';
    SELECT MAX(USCITA) INTO U FROM T021_FASCEORARI WHERE CODICE = T1.CODICE AND TIPO_FASCIA = 'PN';
    DELETE FROM T021_FASCEORARI T021 
      WHERE CODICE = T1.CODICE AND TIPO_FASCIA = 'PN' AND
            ENTRATA = (SELECT MAX(ENTRATA) FROM T021_FASCEORARI WHERE CODICE = T1.CODICE AND TIPO_FASCIA = 'PN') AND
            ROWID <> T1.ROWID;
    UPDATE T021_FASCEORARI SET 
      USCITA_OBB = T1.USCITA,
      ENTRATA_OBB = E,
      USCITA = U
      WHERE ROWID = T1.ROWID;
  END LOOP;
END;
/

create or replace function GetDatoOrario(Cod in varchar2, Data in date, Fascia in Varchar2, Pos in integer, Dato in varchar2) return varchar2 is
  cursor c1 is
    select * from t021_fasceorari t021 
    where codice = Cod and 
          tipo_fascia = fascia and
          decorrenza = (select max(decorrenza) from t021_fasceorari where codice = t021.codice and decorrenza <= Data)
    order by entrata,uscita; 
  i integer;
begin
  i:=0;
  for t1 in c1 loop
    i:=i + 1;
    if i = Pos then
      if upper(Dato) = 'ENTRATA' then
        return(t1.entrata);
      elsif upper(Dato) = 'USCITA' then
        return(t1.uscita);
      end if;
    end if;
  end loop;
  return(Null);
end GetDatoOrario;
/

DECLARE
  --Correzione orari a turni aventi i turni non in ordine cronologico e usati in pianificazione
  CURSOR C1 IS
  SELECT * FROM T020_OLD WHERE TIPOORA = 'E' AND
    (ENTRATA2 IS NOT NULL AND (ENTRATA2 < ENTRATA1 OR (ENTRATA2 = ENTRATA1 AND USCITA2 < USCITA1))
     OR
     ENTRATA3 IS NOT NULL AND (ENTRATA3 < ENTRATA1 OR (ENTRATA3 = ENTRATA1 AND USCITA3 < USCITA1))
     OR
     ENTRATA3 IS NOT NULL AND (ENTRATA3 < ENTRATA2 OR (ENTRATA3 = ENTRATA2 AND USCITA3 < USCITA2))
     OR
     ENTRATA4 IS NOT NULL AND (ENTRATA4 < ENTRATA1 OR (ENTRATA4 = ENTRATA1 AND USCITA4 < USCITA1)) 
     OR
     ENTRATA4 IS NOT NULL AND (ENTRATA4 < ENTRATA2 OR (ENTRATA4 = ENTRATA2 AND USCITA4 < USCITA2)) 
     OR
     ENTRATA4 IS NOT NULL AND (ENTRATA4 < ENTRATA3 OR (ENTRATA4 = ENTRATA3 AND USCITA4 < USCITA3))
    );
  PREC1 VARCHAR2(1);
  ATT1 VARCHAR2(1);
  PREC2 VARCHAR2(1);
  ATT2 VARCHAR2(1);
  PREC3 VARCHAR2(1);
  ATT3 VARCHAR2(1);
  PREC4 VARCHAR2(1);
  ATT4 VARCHAR2(1);
  I INTEGER;
BEGIN
  FOR T1 IN C1 LOOP
    PREC1:=NULL;
    ATT1:=NULL;
    PREC2:=NULL;
    ATT2:=NULL;
    PREC3:=NULL;
    ATT3:=NULL;
    PREC4:=NULL;
    ATT4:=NULL;
    FOR I IN 1..4 LOOP
      IF I <> 1 AND T1.ENTRATA1 IS NOT NULL THEN 
        IF OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'ENTRATA')) = OREMINUTI(TO_CHAR(T1.ENTRATA1,'HH24.MI')) AND
           OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'USCITA')) = OREMINUTI(TO_CHAR(T1.USCITA1,'HH24.MI')) THEN
          PREC1:=1;
          ATT1:=I;
        END IF;
      END IF;
      IF I <> 2 AND T1.ENTRATA2 IS NOT NULL THEN 
        IF OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'ENTRATA')) = OREMINUTI(TO_CHAR(T1.ENTRATA2,'HH24.MI')) AND
           OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'USCITA')) = OREMINUTI(TO_CHAR(T1.USCITA2,'HH24.MI')) THEN
          PREC2:=2;
          ATT2:=I;
        END IF;
      END IF;
      IF I <> 3 AND T1.ENTRATA3 IS NOT NULL THEN 
        IF OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'ENTRATA')) = OREMINUTI(TO_CHAR(T1.ENTRATA3,'HH24.MI')) AND
           OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'USCITA')) = OREMINUTI(TO_CHAR(T1.USCITA3,'HH24.MI')) THEN
          PREC3:=3;
          ATT3:=I;
        END IF;
      END IF;
      IF I <> 4 AND T1.ENTRATA4 IS NOT NULL THEN 
        IF OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'ENTRATA')) = OREMINUTI(TO_CHAR(T1.ENTRATA4,'HH24.MI')) AND
           OREMINUTI(GETDATOORARIO(T1.CODICE,SYSDATE,'PN',I,'USCITA')) = OREMINUTI(TO_CHAR(T1.USCITA4,'HH24.MI')) THEN
          PREC4:=4;
          ATT4:=I;
        END IF;
      END IF;
    END LOOP;
    IF ATT1 IS NOT NULL OR ATT2 IS NOT NULL OR ATT3 IS NOT NULL OR ATT4 IS NOT NULL THEN
      IF ATT1 IS NULL THEN ATT1:='1'; END IF;
      IF ATT2 IS NULL THEN ATT2:='2'; END IF;
      IF ATT3 IS NULL THEN ATT3:='3'; END IF;
      IF ATT4 IS NULL THEN ATT4:='4'; END IF;
      UPDATE T080_PIANIFORARI SET TURNO1 = DECODE(TURNO1,'1',ATT1,'2',ATT2,'3',ATT3,'4',ATT4) WHERE ORARIO = T1.CODICE AND TURNO1 IN ('1','2','3','4');
      UPDATE T080_PIANIFORARI SET TURNO2 = DECODE(TURNO2,'1',ATT1,'2',ATT2,'3',ATT3,'4',ATT4) WHERE ORARIO = T1.CODICE AND TURNO2 IN ('1','2','3','4');
      UPDATE T611_CICLIGIORNALIERI SET TURNO1 = DECODE(TURNO1,'1',ATT1,'2',ATT2,'3',ATT3,'4',ATT4) WHERE ORARIO = T1.CODICE AND TURNO1 IN ('1','2','3','4');      
      UPDATE T611_CICLIGIORNALIERI SET TURNO2 = DECODE(TURNO2,'1',ATT1,'2',ATT2,'3',ATT3,'4',ATT4) WHERE ORARIO = T1.CODICE AND TURNO2 IN ('1','2','3','4');      
    END IF;
  END LOOP;
END;
/

ALTER TABLE T275_CAUPRESENZE ADD NO_ECCEDENZA_IN_FASCIA VARCHAR2(1) DEFAULT 'N';

COMMENT ON COLUMN T275_CAUPRESENZE.NO_ECCEDENZA_IN_FASCIA IS
  'N = No limite - P = Parziale: solo su prima E ed ultima U - C = Completo: tutte le fruizioni della causale';
  
ALTER TABLE T020_ORARI ADD CARENZA_OBB_NO_LIQ VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T275_CAUPRESENZE ADD LINK_ASSENZA VARCHAR2(5);