UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.4.8' WHERE AZIENDA = :AZIENDA;

-- Aggiunta campi alla tabella T291_PARMESSAGGI
ALTER TABLE T291_PARMESSAGGI ADD REGISTRA_MSG VARCHAR2(1) DEFAULT 'N';

-- Creazione della tabella T295_MESSAGGIINVIATI
create table T295_MESSAGGIINVIATI
( PROGRESSIVO NUMBER,
  DATA_MSG    DATE,
  ORA_MSG     DATE,
  TESTO_MSG   VARCHAR2(1000),
  OPERATORE   VARCHAR2(10),
  DATA_SCAD_MSG DATE)
tablespace LAVORO
  pctfree 10 pctused 80 initrans 1 maxtrans 255
  storage  (initial 32K next 256K minextents 1 pctincrease 0);

alter table T295_MESSAGGIINVIATI
  add constraint T295_PK primary key (PROGRESSIVO)
  using index 
tablespace INDICI
  pctfree 10 initrans 2 maxtrans 255
  storage
  (initial 32K next 256K minextents 1 pctincrease 0);

-- Aggiunta campo alla tabella T670_REGOLEBUONI
ALTER TABLE T670_REGOLEBUONI ADD CONGUAGLIO_PREC_MAX NUMBER(3) DEFAULT 999;

-- Aggiunta campi alla tabella T690_ACQUISTOBUONI
ALTER TABLE T690_ACQUISTOBUONI ADD BUONI_RECUPERATI_PREC NUMBER(3);
ALTER TABLE T690_ACQUISTOBUONI ADD TICKET_RECUPERATI_PREC NUMBER(3);

UPDATE T020_ORARI SET TUTTOCOMP = 'N' WHERE COMPFASCIA = '3';

ALTER TABLE MONDOEDP.I100_PARSCARICO ADD TRIGGER_BEFORE VARCHAR2(1) DEFAULT 'N';
ALTER TABLE MONDOEDP.I100_PARSCARICO ADD TRIGGER_AFTER VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T025_CONTMENSILI ADD RICALCOLO_MAX_SCOSTNEG NUMBER(2);

-- Pulizia (se sono ancora in tabella) delle vecchie colonne di abilitazioni assenze e presenze 
UPDATE T430_STORICO SET ABCAUSALE2 = NULL, ABCAUSALE3 = NULL, ABCAUSALE4 = NULL, ABCAUSALE5 = NULL, ABCAUSALE6 = NULL,
  ABPRESENZA2 = NULL, ABPRESENZA3 = NULL, ABPRESENZA4 = NULL, ABPRESENZA5 = NULL, ABPRESENZA6 = NULL, ABPRESENZA7 = NULL,
  ABPRESENZA8 = NULL;

-- Nuovo campo per formato data nella definizione delle variabili per lo stato giuridico
ALTER TABLE SG500_DATILIBERI ADD FORMATO_DATA VARCHAR2(20);

ALTER TABLE MONDOEDP.I071_PERMESSI ADD ELIMINA_DATA_CASSA VARCHAR2(1) DEFAULT 'N';
UPDATE MONDOEDP.I071_PERMESSI SET ELIMINA_DATA_CASSA = 'S';

ALTER TABLE MONDOEDP.I071_PERMESSI ADD RICREA_SCARICO_PAGHE VARCHAR2(1) DEFAULT 'N';
UPDATE MONDOEDP.I071_PERMESSI SET RICREA_SCARICO_PAGHE = 'S';

ALTER TABLE T275_CAUPRESENZE ADD STACCO_MINIMO_SCOST NUMBER(3);
ALTER TABLE T275_CAUPRESENZE ADD LIMITE_DEBITOGG VARCHAR2(1) DEFAULT 'N';
