UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.5.4' WHERE AZIENDA = :AZIENDA;

ALTER TABLE T025_CONTMENSILI ADD ABBATT_MOBILE_RIFERIMENTO VARCHAR2(1) DEFAULT 'M';

ALTER TABLE T020_ORARI ADD ECC_COMP_CAUSALIZZATA VARCHAR2(1) DEFAULT 'N';

INSERT INTO I091_DATIENTE (SELECT AZIENDA,'C10_CREDITIFORMATIVI', '' FROM I090_ENTI);

ALTER TABLE T242_COMPETENZESINDACATI ADD TIPO VARCHAR2(1) DEFAULT 'C';

comment on column T242_COMPETENZESINDACATI.TIPO
  is 'I = Individuale - C = Collettivo';

ALTER TABLE T242_COMPETENZESINDACATI DROP PRIMARY KEY;

alter table T242_COMPETENZESINDACATI
  add constraint T242_PK primary key (CODICE,AREA_SINDACALE,TIPO,DECORRENZA)
  using index 
  tablespace INDICI
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  ( initial 10K  next 10K  minextents 1  pctincrease 0);
