ALTER TABLE T350_REGREPERIB ADD VP_TURNI_OLTREMAX VARCHAR2(6) DEFAULT '<NO>';
ALTER TABLE T350_REGREPERIB DROP COLUMN VP_MAX_MESE;
ALTER TABLE T350_REGREPERIB DROP COLUMN GETTONE_CHIAMATA;

ALTER TABLE T350_REGREPERIB MODIFY VP_GETTONE_CHIAMATA DEFAULT '<NO>';
UPDATE T350_REGREPERIB SET VP_GETTONE_CHIAMATA = '<NO>' WHERE VP_GETTONE_CHIAMATA IS NULL;

ALTER TABLE T340_TURNIREPERIB MODIFY VP_GETTONE_CHIAMATA DEFAULT '<NO>';
UPDATE T340_TURNIREPERIB SET VP_GETTONE_CHIAMATA = '<NO>' WHERE VP_GETTONE_CHIAMATA IS NULL;

ALTER TABLE T340_TURNIREPERIB MODIFY VP_TURNI_OLTREMAX DEFAULT '<NO>';
UPDATE T340_TURNIREPERIB SET VP_TURNI_OLTREMAX = '<NO>' WHERE VP_TURNI_OLTREMAX IS NULL;

ALTER TABLE T340_TURNIREPERIB DROP CONSTRAINT T340_PK CASCADE;

DROP INDEX T340_PK;

ALTER TABLE T340_TURNIREPERIB
  ADD CONSTRAINT T340_PK PRIMARY KEY (PROGRESSIVO, ANNO, MESE, VP_TURNO, VP_ORE, VP_MAGGIORATE, VP_NONMAGGIORATE, VP_GETTONE_CHIAMATA, VP_TURNI_OLTREMAX)
  USING INDEX TABLESPACE INDICI STORAGE (INITIAL 256K NEXT 256K PCTINCREASE 0);