CREATE OR REPLACE PROCEDURE ELIMINA_TIMBRI_DOPPI (MAT IN VARCHAR2, DAL IN VARCHAR2, AL IN VARCHAR2) AS
  CURSOR C1 IS 
    SELECT * FROM T100_TIMBRATURE WHERE
    PROGRESSIVO = (SELECT PROGRESSIVO FROM T030_ANAGRAFICO WHERE MATRICOLA = MAT) AND
    DATA BETWEEN TO_DATE(DAL,'DD/MM/YYYY') AND TO_DATE(AL,'DD/MM/YYYY') AND
    FLAG IN ('C','M');
  CURSOR C2 IS 
    SELECT * FROM T100_TIMBRATURE WHERE
    DATA BETWEEN TO_DATE(DAL,'DD/MM/YYYY') AND TO_DATE(AL,'DD/MM/YYYY') AND
    FLAG IN ('C','M');
BEGIN
  IF MAT = '*' THEN
  FOR T1 IN C2 LOOP
    BEGIN
      INSERT INTO T100_DOPPI
        SELECT * FROM T100_TIMBRATURE WHERE
        PROGRESSIVO = T1.PROGRESSIVO AND
        DATA = T1.DATA AND
        ORA = T1.ORA AND     
        VERSO = T1.VERSO AND
        FLAG = 'O';
      DELETE FROM T100_TIMBRATURE WHERE
        PROGRESSIVO = T1.PROGRESSIVO AND
        DATA = T1.DATA AND
        ORA = T1.ORA AND     
        VERSO = T1.VERSO AND
        FLAG = 'O';
      COMMIT;     
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        EXIT;
    END;
  END LOOP;
  ELSE
  FOR T1 IN C1 LOOP
    BEGIN
      INSERT INTO T100_DOPPI
        SELECT * FROM T100_TIMBRATURE WHERE
        PROGRESSIVO = T1.PROGRESSIVO AND
        DATA = T1.DATA AND
        ORA = T1.ORA AND     
        VERSO = T1.VERSO AND
        FLAG = 'O';
      DELETE FROM T100_TIMBRATURE WHERE
        PROGRESSIVO = T1.PROGRESSIVO AND
        DATA = T1.DATA AND
        ORA = T1.ORA AND     
        VERSO = T1.VERSO AND
        FLAG = 'O';
      COMMIT;     
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        EXIT;
    END;
  END LOOP;
  END IF; 
END;
/
