CREATE OR REPLACE PROCEDURE GENERAPROFILI (ANNOX IN OUT INTEGER, DUPLICATI IN OUT VARCHAR2) AS
  CURSOR T262(A INTEGER) IS
    SELECT * FROM T262_PROFASSANN WHERE ANNO = A;
  TMP  VARCHAR2(20);
BEGIN
  DUPLICATI:=NULL;
  FOR REC262 IN T262(ANNOX - 1) LOOP
    BEGIN
      INSERT INTO T262_PROFASSANN
        (ANNO,CODPROFILO,CODRAGGR,UMISURA,COMPETENZA1,RETRIBUZIONE1,COMPETENZA2,RETRIBUZIONE2,COMPETENZA3,RETRIBUZIONE3,COMPETENZA4,RETRIBUZIONE4,COMPETENZA5,RETRIBUZIONE5,COMPETENZA6,RETRIBUZIONE6,
         PROPORZIONE,SOMMA,MG,ARRFAV,PROPGGMM,DATARES,
         ARR_COMPETENZA_IN_ORE,
         MAX_FRUIZIONE_GIORN_IN_ORE,
         FRUIZ_ANNO_MINIMA,
         FRUIZ_ANNO_CONTINUATIVA,
         FRUIZ_MINIMA_DAL,
         RAPPORTI_UNITI, 
         COMPETENZE_PERSONALIZZATE, 
         FORMULA_PROPORZIONE)
      VALUES
        (ANNOX,REC262.CODPROFILO,REC262.CODRAGGR,REC262.UMISURA,REC262.COMPETENZA1,REC262.RETRIBUZIONE1,REC262.COMPETENZA2,REC262.RETRIBUZIONE2,REC262.COMPETENZA3,REC262.RETRIBUZIONE3,REC262.COMPETENZA4,REC262.RETRIBUZIONE4,REC262.COMPETENZA5,REC262.RETRIBUZIONE5,REC262.COMPETENZA6,REC262.RETRIBUZIONE6,
         REC262.PROPORZIONE,REC262.SOMMA,REC262.MG,REC262.ARRFAV,REC262.PROPGGMM,ADD_MONTHS(REC262.DATARES,12),
         REC262.ARR_COMPETENZA_IN_ORE,
         REC262.MAX_FRUIZIONE_GIORN_IN_ORE,
         REC262.FRUIZ_ANNO_MINIMA,
         REC262.FRUIZ_ANNO_CONTINUATIVA,
         ADD_MONTHS(REC262.FRUIZ_MINIMA_DAL,12),
         REC262.RAPPORTI_UNITI, 
         REC262.COMPETENZE_PERSONALIZZATE, 
         REC262.FORMULA_PROPORZIONE);
    EXCEPTION
      WHEN DUP_VAL_ON_INDEX THEN 
        TMP:=REC262.CODPROFILO||'='||REC262.CODRAGGR||',';
        IF DUPLICATI IS NULL THEN
          DUPLICATI:=TMP;
        ELSIF LENGTH(DUPLICATI||TMP) <= 2000 THEN
          DUPLICATI:=DUPLICATI||TMP;
        END IF;
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
  COMMIT;
END;
/
