CREATE OR REPLACE TRIGGER T722_AFTERUPDATE
  AFTER UPDATE OF DECORRENZA, DECORRENZA_FINE ON T722_PERIODI_EVENTI_STR 
  FOR EACH ROW
begin
  update T724_EVENTI_STR_INDIVIDUALI
  set DAL = NEW.DECORRENZA,
      AL = NEW.DECORRENZA_FINE
  where ID = NEW.ID
  and DAL = OLD.DECORRENZA
  and AL = OLD.DECORRENZA_FINE;
end;
/