ALTER TABLE T200_CONTRATTI ADD TOLINDNOT NUMERIC (38,2);
ALTER TABLE T200_CONTRATTI ADD ARRINDNOT NUMERIC (38,2);
ALTER TABLE T020_ORARI ADD MMINDMPRES DATE;
ALTER TABLE T020_ORARI ADD FLAGMPRES VARCHAR2(1);
ALTER TABLE T020_ORARI ADD OREINDFEST DATE;

CREATE TABLE T900_STAMPABASE (
  CODICEINTERNO VARCHAR(6) NOT NULL,
  NOMESTAMPA VARCHAR(10) NOT NULL,
  DESCRIZIONE VARCHAR(40),
  SETTAGGI LONG,
  PRIMARY KEY (CODICEINTERNO, NOMESTAMPA)
)
