ALTER TABLE I090_ENTI ADD FRAZIONANOTTE VARCHAR2(1);
UPDATE I090_ENTI SET FRAZIONANOTTE = 'S';

ALTER TABLE I070_OPERATORI ADD INTEGRAZIONEANAGRAFE VARCHAR2(1);
UPDATE I070_OPERATORI SET INTEGRAZIONEANAGRAFE = 'S';

ALTER TABLE T020_ORARI ADD NUMTURNO1 NUMBER(1);
ALTER TABLE T020_ORARI ADD NUMTURNO2 NUMBER(1);
ALTER TABLE T020_ORARI ADD NUMTURNO3 NUMBER(1);
ALTER TABLE T020_ORARI ADD NUMTURNO4 NUMBER(1);
UPDATE T020_ORARI SET NUMTURNO1 = 1,NUMTURNO2 = 2,NUMTURNO3 = 3,NUMTURNO4 = 4;
COMMIT;
