CREATE TABLE T170_INDTURNO (
  CODICE VARCHAR2(5),
  TIPO VARCHAR2(1),
  IMPORTO NUMBER,
  VOCEPAGHE VARCHAR2(6),
  NUMTURNI NUMBER,
  TURNI VARCHAR2(4),
  ASSENZE VARCHAR2(120),
  CODICE2 VARCHAR2(5),
  CONSTRAINT T170_PK PRIMARY KEY (CODICE) USING INDEX TABLESPACE INDICI
) TABLESPACE LAVORO;

CREATE TABLE T171_LIMITI (
  CODICE VARCHAR2(5),
  GIORNI NUMBER,
  ESPRESSIONE VARCHAR2(40),
  CONSTRAINT T171_PK PRIMARY KEY (CODICE,GIORNI) USING INDEX TABLESPACE INDICI
) TABLESPACE LAVORO;

ALTER TABLE T070_SCHEDARIEPIL ADD CODINDTURNO VARCHAR2(5);
ALTER TABLE T070_SCHEDARIEPIL ADD NUMINDTURNO NUMBER;

ALTER TABLE T190_INTPAGHE ADD P160 VARCHAR2(6);
ALTER TABLE T190_INTPAGHE ADD F160 VARCHAR2(1);

ALTER TABLE T265_CAUASSENZE ADD RICORSIONE VARCHAR2(1);
