CREATE TABLE T500_PIANTAORG (
  MANSIONE VARCHAR2(20),
  DELIBERA VARCHAR2(20),
  VARIAZ DATE,
  DPR VARCHAR2(20),
  DATADPR DATE,
  NOTE VARCHAR2(255),
  LIVSTRUT VARCHAR2(20),
  NUMPOSTI NUMBER,
  PARTTIME NUMBER,
  CONSTRAINT T500_PK PRIMARY KEY (MANSIONE,DELIBERA,VARIAZ,LIVSTRUT) USING INDEX TABLESPACE INDICI
) 
TABLESPACE LAVORO;

CREATE TABLE T501_PIANTADETT (
  MANSIONE VARCHAR2(20),
  DELIBERA VARCHAR2(20),
  VARIAZ DATE,
  LIVSTRUT VARCHAR2(20),
  TIPO VARCHAR2(1),
  VALORE VARCHAR2(20),
  NUMPOSTI NUMBER,
  CONSTRAINT T501_PK PRIMARY KEY (MANSIONE,DELIBERA,VARIAZ,LIVSTRUT,TIPO,VALORE) USING INDEX TABLESPACE INDICI
)
TABLESPACE LAVORO;
ALTER TABLE T042_PERIODIASSENZA ADD FLAG VARCHAR2(1);

CREATE TABLE I092_LOGTABELLE (
  AZIENDA VARCHAR2(30),
  TABELLA VARCHAR2(80)
) TABLESPACE LAVORO;

CREATE TABLE I000_LOG (
  OPERATORE VARCHAR2(20),
  DATA DATE,
  MASCHERA VARCHAR2(10),
  TABELLA VARCHAR2(80),
  OPERAZIONE VARCHAR2(1),
  DIPENDENTE NUMBER,
  DATARIF DATE,
  DATO VARCHAR2(100)
) TABLESPACE LAVORO;

