update MONDOEDP.I090_ENTI set VERSIONEDB = '9c.8',PATCHDB = 4 where UTENTE = (select UTENTE from MONDOEDP.I090_ENTI where AZIENDA = :AZIENDA);

alter table T670_REGOLEBUONI modify ESTENDI_INTERVALLO_PMT default 'N';
update T670_REGOLEBUONI set ESTENDI_INTERVALLO_PMT = 'N' where ESTENDI_INTERVALLO_PMT is null;
