unit A078URichiestaAssistenzaDtM1;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  DB, A000UCostanti, A000USessione,A000UInterfaccia, Oracle, OracleData, Variants;

type
  TA078FRichiestaAssistenzaDTM1 = class(TDataModule)
    EsportaDipendente: TOracleQuery;
    selVersion: TOracleQuery;
    SelTab: TOracleDataSet;
    SelPrimaryKey: TOracleDataSet;
    DtsI500: TOracleDataSet;
    DtsI500NOMECAMPO: TStringField;
    DtsT360T760: TOracleDataSet;
    selI091: TOracleDataSet;
    procedure DtM1Create(Sender: TObject);
    procedure DtM1Destroy(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
    Data:TDateTime;
  end;

const
  A078ElencoQuery:array[1..125] of String =
{1}  ('SELECT * FROM T030_ANAGRAFICO WHERE PROGRESSIVO = <PROGRESSIVO>', //EXP T030 PER PRIMA!
     'SELECT * FROM P254_VOCIPROGRAMMATE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P256_VOCIRIASSORBIBILI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P258_ADDIZIONALIIRPEF WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P262_MOD730TESTATA WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P264_MOD730IMPORTI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P266_MODONAOSI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P268_RAPPORTIPRECEDENTI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P270_REDDITIANNUALI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P272_RETRIBUZIONE_CONTRATTUALE WHERE PROGRESSIVO = <PROGRESSIVO>',
{10} 'SELECT * FROM P430_ANAGRAFICO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P430_APPOGGIO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P440_CEDOLINOSTATO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P441_CEDOLINO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P445_CEDOLINOTEMP WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P448_CEDOLINOPARKVOCI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P450_DATIMENSILI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P504_CUDTESTATE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P605_770DATIINDIVIDUALI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM P663_FLUSSIDATIINDIVIDUALI WHERE PROGRESSIVO = <PROGRESSIVO>',
{20} 'SELECT * FROM P673_XMLDATIINDIVIDUALI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM SG100_PROVVEDIMENTO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM SG101_FAMILIARI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM SG102_DOCUMENTI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM SG110_CURRICULUM WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM SG113_PREFERENZE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM SG651_PIANIFICAZIONECORSI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM SG656_RESIDUOCREDITI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T012_CALENDINDIVID WHERE PROGRESSIVO = <PROGRESSIVO>',
{30} 'SELECT * FROM T040_GIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T041_PROVVISORIO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T042_PERIODIASSENZA WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T044_STORICOGIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T046_GIUSTIFICATIVIFAMILIARI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T050_RICHIESTEASSENZA WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T070_SCHEDARIEPIL WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T071_SCHEDAFASCE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T072_SCHEDAINDPRES WHERE PROGRESSIVO = <PROGRESSIVO>',
{40} 'SELECT * FROM T073_SCHEDACAUSPRES WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T074_CAUSPRESFASCE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T075_STRESTERNO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T076_CAUSPRESPAGHE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T081_PROVVISORIO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T090_PLUSORAINDIV WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T100_TIMBRATURE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T101_ANOMALIE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T102_FESTELAVORATE WHERE PROGRESSIVO = <PROGRESSIVO>',
{50} 'SELECT * FROM T130_RESIDANNOPREC WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T131_RESIDPRESENZE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T134_ORELIQUIDATEANNIPREC WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T180_DATIBLOCCATI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T195_VOCIVARIABILI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T246_ISCRIZIONISINDACATI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T247_PARTECIPAZIONISINDACATI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T248_PERMESSISINDACALI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T263_PROFASSIND WHERE PROGRESSIVO = <PROGRESSIVO>',
{60} 'SELECT * FROM T264_RESIDASSANN WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T280_MESSAGGIWEB WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T295_MESSAGGIINVIATI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T299_MESSAGGIRICHIESTI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T320_PIANLIBPROFESSIONE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T332_PIAN_ATT_AGGIUNTIVE WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T340_TURNIREPERIB WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T370_TIMBMENSA WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T375_ACCESSIMENSA WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T380_PIANIFREPERIB WHERE PROGRESSIVO = <PROGRESSIVO>',
{70} 'SELECT * FROM T410_PASTI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T433_CDC_PERCENT WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T435_BADGESERVIZIO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T620_TURNAZIND WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T630_SPOSTSQUADRA WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T680_BUONIMENSILI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T690_ACQUISTOBUONI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T692_RESIDUOBUONI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T760_REGOLEINCENTIVI',
{80} 'SELECT * FROM T762_INCENTIVIMATURATI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T775_QUOTEINDIVIDUALI WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T820_LIMITIIND WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T825_LIQUIDINDANNUO WHERE PROGRESSIVO = <PROGRESSIVO>',
     'SELECT * FROM T220_PROFILIORARI WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
     'SELECT * FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
     //'SELECT * FROM T020_ORARI WHERE CODICE IN (SELECT DISTINCT ORARIO FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>)',
{87} 'SELECT * FROM T020_ORARI WHERE CODICE IN (' +
     'SELECT ORARIO FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT LUNEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT MARTEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT MERCOLEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT GIOVEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT VENERDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT SABATO FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT DOMENICA FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT NONLAV FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT FESTIVO FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)) ',
     //'AND CODICE NOT IN (SELECT CODICE FROM T020_ORARI WHERE CODICE IN (SELECT DISTINCT ORARIO FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>))',
{88} 'SELECT * FROM T021_FASCEORARI WHERE CODICE IN ( ' +
     'SELECT ORARIO FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT LUNEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT MARTEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT MERCOLEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT GIOVEDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT VENERDI FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT SABATO FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT DOMENICA FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT NONLAV FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ' +
     'UNION ' +
     'SELECT FESTIVO FROM T221_PROFILISETTIMANA WHERE CODICE IN (SELECT DISTINCT PORARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)) ',
     //'AND CODICE NOT IN (SELECT CODICE FROM T020_ORARI WHERE CODICE IN (SELECT DISTINCT ORARIO FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>))'*),
{89} 'SELECT * FROM T025_CONTMENSILI  WHERE CODICE IN (SELECT DISTINCT PERSELASTICO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{90} 'SELECT * FROM T460_PARTTIME WHERE CODICE IN (SELECT DISTINCT PARTTIME FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{91} 'SELECT * FROM T160_PROFILIINDENNITA WHERE CODICE IN (' +
     'SELECT IPRESENZA FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT INDPRESENZA FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>)',
{92} 'SELECT * FROM T162_INDENNITA WHERE CODICE IN ( ' +
     'SELECT INDENNITA FROM ' +
     'T160_PROFILIINDENNITA WHERE CODICE IN ( ' +
     'SELECT IPRESENZA FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT INDPRESENZA FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>))',
{93} 'SELECT * FROM T171_LIMITI WHERE CODICE IN ( ' +
     'SELECT INDENNITA FROM ' +
     'T160_PROFILIINDENNITA WHERE CODICE IN ( ' +
     'SELECT IPRESENZA FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT INDPRESENZA FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>))',
{94} 'SELECT * FROM T164_ASSOCIAZIONIINDENNITA WHERE CODICE IN ( ' +
     'SELECT INDENNITA FROM ' +
     'T160_PROFILIINDENNITA WHERE CODICE IN ( ' +
     'SELECT IPRESENZA FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT INDPRESENZA FROM T080_PIANIFORARI WHERE PROGRESSIVO = <PROGRESSIVO>))',
{95} 'SELECT *  FROM T265_CAUASSENZE WHERE CODICE IN (SELECT DISTINCT CAUSALE FROM T040_GIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>)',
{96} 'SELECT * FROM T260_RAGGRASSENZE WHERE CODICE IN (SELECT DISTINCT CODRAGGR FROM T265_CAUASSENZE WHERE CODICE IN (SELECT DISTINCT CAUSALE FROM T040_GIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>))',
{97} 'SELECT * FROM T262_PROFASSANN WHERE CODPROFILO IN (SELECT DISTINCT PASSENZE FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) ',
{98} 'SELECT * FROM T275_CAUPRESENZE WHERE CODICE IN ( ' +
     'SELECT DISTINCT CAUSALE FROM T100_TIMBRATURE WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE FROM T040_GIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>)',
{99} 'SELECT * FROM T270_RAGGRPRESENZE WHERE CODICE IN (SELECT DISTINCT CODRAGGR FROM T275_CAUPRESENZE WHERE CODICE IN ( ' +
     'SELECT DISTINCT CAUSALE FROM T100_TIMBRATURE WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE FROM T040_GIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>))',
{100}'SELECT * FROM T276_VOCIPAGHEPRESENZA WHERE CODICE IN ( ' +
     'SELECT DISTINCT CAUSALE FROM T100_TIMBRATURE WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE FROM T040_GIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>)',
{101}'SELECT * FROM T277_CAUFASCEABILITATE WHERE CODICE IN ( ' +
     'SELECT DISTINCT CAUSALE FROM T100_TIMBRATURE WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE FROM T040_GIUSTIFICATIVI WHERE PROGRESSIVO = <PROGRESSIVO>)',
{102}'SELECT * FROM T350_REGREPERIB WHERE CODICE IN ( ' +
     'SELECT TURNO1 FROM T380_PIANIFREPERIB WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT TURNO2 FROM T380_PIANIFREPERIB WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT TURNO3 FROM T380_PIANIFREPERIB WHERE PROGRESSIVO = <PROGRESSIVO> )',
{103}'SELECT * FROM T360_TERMENSA',
{104}'SELECT * FROM T670_REGOLEBUONI',
{105}'SELECT * FROM T305_CAUGIUSTIF WHERE CODICE IN ( ' +
     'SELECT DISTINCT CAUSALE FROM T100_TIMBRATURE WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE1MINASS FROM T070_SCHEDARIEPIL WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE2MINASS FROM T070_SCHEDARIEPIL WHERE PROGRESSIVO = <PROGRESSIVO>)',
{106}'SELECT * FROM T300_RAGGRGIUSTIF WHERE CODICE IN (SELECT DISTINCT CODRAGGR FROM T305_CAUGIUSTIF WHERE CODICE IN ( ' +
     'SELECT DISTINCT CAUSALE FROM T100_TIMBRATURE WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE1MINASS FROM T070_SCHEDARIEPIL WHERE PROGRESSIVO = <PROGRESSIVO> ' +
     'UNION ' +
     'SELECT DISTINCT CAUSALE2MINASS FROM T070_SCHEDARIEPIL WHERE PROGRESSIVO = <PROGRESSIVO>))',
{107}'SELECT * FROM T163_CODICIINDENNITA WHERE CODICE IN (SELECT DISTINCT IPRESENZA FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{108}'SELECT * FROM T200_CONTRATTI WHERE CODICE IN (SELECT DISTINCT CONTRATTO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{109}'SELECT * FROM T201_MAGGIORAZIONI WHERE CODICE IN (SELECT DISTINCT CONTRATTO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{110}'SELECT * FROM T210_MAGGIORAZIONI',
{111}'SELECT * FROM T450_TIPORAPPORTO WHERE CODICE IN (SELECT DISTINCT TIPORAPPORTO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{112}'SELECT * FROM T010_CALENDIMPOSTAZ WHERE CODICE IN (SELECT DISTINCT CALENDARIO FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{113}'SELECT * FROM M040_MISSIONI WHERE PROGRESSIVO = <PROGRESSIVO>',
{114}'SELECT * FROM M010_PARAMETRICONTEGGIO M010 WHERE M010.CODICE IN (SELECT DISTINCT(<C8_MISSIONE>) FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{115}'SELECT * FROM M065_TARIFFE_INDENNITA WHERE CODICE IN (SELECT <C8_MISSIONE> FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{116}'SELECT * FROM M066_RIDUZIONI WHERE CODICE IN (SELECT <C8_MISSIONE> FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>)',
{117}'SELECT * FROM M060_ANTICIPI WHERE PROGRESSIVO = <PROGRESSIVO>',
{118}'SELECT * FROM M052_INDENNITAKM WHERE PROGRESSIVO = <PROGRESSIVO>',
{119}'SELECT * FROM M051_DETTAGLIORIMBORSO WHERE PROGRESSIVO = <PROGRESSIVO>',
{120}'SELECT * FROM M050_RIMBORSI WHERE PROGRESSIVO = <PROGRESSIVO>',
{121}'SELECT * FROM M011_TIPOMISSIONE WHERE CODICE IN (SELECT DISTINCT TIPOREGISTRAZIONE FROM M040_MISSIONI WHERE PROGRESSIVO = <PROGRESSIVO>)',
{122}'SELECT * FROM M020_TIPIRIMBORSI M020 WHERE EXISTS (SELECT ''X'' FROM M010_PARAMETRICONTEGGIO M010 WHERE M010.CODICE IN (SELECT DISTINCT(<C8_MISSIONE>) ' +
     'FROM T430_STORICO WHERE PROGRESSIVO = <PROGRESSIVO>) AND CODICI_RIMBORSI IS NOT NULL AND INSTR('',''||CODICI_RIMBORSI||'','', M020.CODICE) > 0)',
{123}'SELECT * FROM M025_MOTIVAZIONI',
{124}'SELECT * FROM M140_RICHIESTE_MISSIONI WHERE PROGRESSIVO = <PROGRESSIVO>',
{125}'SELECT M150.* FROM M150_RICHIESTE_RIMBORSI M150, M140_RICHIESTE_MISSIONI M140 WHERE M150.ID = M140.ID AND M140.PROGRESSIVO = <PROGRESSIVO>',
{126}'SELECT M160.* FROM M160_RICHIESTE_ANTICIPI M160, M140_RICHIESTE_MISSIONI M140 WHERE M160.ID = M140.ID AND M140.PROGRESSIVO = <PROGRESSIVO>',
{127}'SELECT M170.* FROM M170_RICHIESTE_MEZZI M170, M140_RICHIESTE_MISSIONI M140 WHERE M170.ID = M140.ID AND M140.PROGRESSIVO = <PROGRESSIVO>',
{128}'SELECT M175.* FROM M175_RICHIESTE_MOTIVAZIONI M175, M140_RICHIESTE_MISSIONI M140 WHERE M175.ID = M140.ID AND M140.PROGRESSIVO = <PROGRESSIVO>');
var
  A078FRichiestaAssistenzaDTM1: TA078FRichiestaAssistenzaDTM1;

implementation

{$R *.DFM}

procedure TA078FRichiestaAssistenzaDTM1.DtM1Create(Sender: TObject);
var i:Integer;
begin
  if not(SessioneOracle.Connected) then
  begin
    Password(Application.Name);
    A000ParamDBOracle(SessioneOracle);
  end;
  for i:=0 to Self.ComponentCount - 1 do
  begin
    if Components[i] is TOracleQuery then
      (Components[i] as TOracleQuery).Session:=SessioneOracle;
    if Components[i] is TOracleDataSet then
      (Components[i] as TOracleDataSet).Session:=SessioneOracle;
  end;
end;

procedure TA078FRichiestaAssistenzaDTM1.DtM1Destroy(Sender: TObject);
var i:Integer;
begin
  for i:=0 to Self.ComponentCount - 1 do
    if Self.Components[i] is TDataSet then
      (Self.Components[i] as TDataSet).Close;
end;

end.
