ALTER TABLE T200_CONTRATTI ADD 
DATADECORRENZA DATE;

DROP TABLE T101_ANOMALIE;

CREATE TABLE T101_ANOMALIE (
  PROGRESSIVO NUMBER(38, 2) NOT NULL,
  DATA DATE NOT NULL,
  LIVELLO NUMBER(38, 2),
  ANOMALIA VARCHAR2(60)
)
  TABLESPACE LAVORO;

CREATE  INDEX INDICE ON T101_ANOMALIE (PROGRESSIVO, DATA) TABLESPACE INDICI;

ALTER TABLE I090_ENTI ADD TSLAVORO VARCHAR2(20);
ALTER TABLE I090_ENTI ADD TSINDICI VARCHAR2(20);
