CREATE TABLE T310_DESCLIBPROF (
  CODICE VARCHAR2(5),
  DESCRIZIONE VARCHAR2(40),
  CONSTRAINT T310_PK PRIMARY KEY (CODICE)
  USING INDEX STORAGE (PCTINCREASE 0) TABLESPACE INDICI
)
STORAGE (PCTINCREASE 0) TABLESPACE LAVORO;

CREATE TABLE T311_DETTLIBPROF (
  CODICE VARCHAR2(5),
  GIORNO NUMBER(2),
  DALLE VARCHAR2(5),
  ALLE VARCHAR2(5),
  CAUSALE VARCHAR2(5),
  CONSTRAINT T311_PK PRIMARY KEY (CODICE,GIORNO,DALLE)
  USING INDEX STORAGE (PCTINCREASE 0) TABLESPACE INDICI
)
STORAGE (PCTINCREASE 0) TABLESPACE LAVORO;

CREATE TABLE T320_PIANLIBPROFESSIONE (
  PROGRESSIVO NUMBER(38),
  DATA DATE,
  DALLE VARCHAR2(5),
  ALLE VARCHAR2(5),
  CAUSALE VARCHAR2(5),
  CONSTRAINT T320_PK PRIMARY KEY (PROGRESSIVO,DATA,DALLE)
  USING INDEX STORAGE (PCTINCREASE 0) TABLESPACE INDICI
)
STORAGE (PCTINCREASE 0) TABLESPACE LAVORO;
