ALTER TABLE T911_DATIRIEPILOGO MODIFY FORMATO VARCHAR2(200);
ALTER TABLE T670_REGOLEBUONI ADD TIPO_CALCOLO VARCHAR2(1) DEFAULT 'A';
ALTER TABLE T670_REGOLEBUONI ADD MESE_ASSENZE NUMBER(2) DEFAULT '2';
ALTER TABLE T071_SCHEDAFASCE MODIFY ORE1ASSEST VARCHAR2(7);
ALTER TABLE T071_SCHEDAFASCE MODIFY ORE2ASSEST VARCHAR2(7);