UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.4.7' WHERE AZIENDA = :AZIENDA;

-- Modifica tabella definizione dati liberi
alter table I500_DATILIBERI add STORICO VARCHAR2(1) DEFAULT 'N';
alter table I500_DATILIBERI add LUNG_DESC NUMBER;
UPDATE I500_DATILIBERI SET LUNG_DESC=40 WHERE TABELLA='S';

-- Modifica tabella indennità di presenza
ALTER TABLE T162_INDENNITA ADD COEFFICIENTE NUMBER DEFAULT 0;

-- Modifica tabella Regole accessi mensa
alter table T360_TERMENSA add MENSA_STIMBRATA_INTERO varchar2(1);
alter table T360_TERMENSA add MENSA_NON_STIMBRATA_INTERO varchar2(1) default 'N';
alter table T360_TERMENSA add TIMBANTECENTRATA_INTERO varchar2(1);
alter table T360_TERMENSA add TIMBDOPOUSCITA_INTERO varchar2(1);
alter table T360_TERMENSA add CONTROLLOPRESENZA_INTERO varchar2(1);
alter table T360_TERMENSA add ORARIOSPEZZATO_INTERO varchar2(1);
alter table T360_TERMENSA add PAUSAMENSAGESTITA_INTERO varchar2(1);
alter table T360_TERMENSA add PRESENZAMINIMA_INTERO varchar2(1);
alter table T360_TERMENSA add INTERVALLO_INTERO varchar2(1);
alter table T360_TERMENSA add ORE_MINIME_INTERO varchar2(1);

UPDATE T360_TERMENSA SET MENSA_STIMBRATA_INTERO = 'N';
UPDATE T360_TERMENSA SET MENSA_NON_STIMBRATA_INTERO = 'N';
UPDATE T360_TERMENSA SET TIMBANTECENTRATA_INTERO = TIMBANTECENTRATA;
UPDATE T360_TERMENSA SET TIMBDOPOUSCITA_INTERO = TIMBDOPOUSCITA;
UPDATE T360_TERMENSA SET CONTROLLOPRESENZA_INTERO = CONTROLLOPRESENZA;
UPDATE T360_TERMENSA SET ORARIOSPEZZATO_INTERO = ORARIOSPEZZATO;
UPDATE T360_TERMENSA SET PAUSAMENSAGESTITA_INTERO = PAUSAMENSAGESTITA;
UPDATE T360_TERMENSA SET PRESENZAMINIMA_INTERO = PRESENZAMINIMA;
UPDATE T360_TERMENSA SET INTERVALLO_INTERO = DECODE(oreminuti(INTERVALLO),0,'N','S');
UPDATE T360_TERMENSA SET ORE_MINIME_INTERO = DECODE(oreminuti(ORE_MINIME),0,'N','S');

-- Modifica contenuto tabella registrazione log
UPDATE I000_LOGINFO SET TABELLA = RTRIM(LTRIM(TABELLA));

-- Aggiunta campo alla tabella T025_CONTMENSILI
alter table T025_CONTMENSILI add RICALCOLO_DEBITO_GG varchar2(1) default 'N';

ALTER TABLE T020_ORARI ADD PM_AUTO_URIT VARCHAR2(1) DEFAULT 'N';

ALTER TABLE IA010_PARAMETRIP00 ADD PACKAGE_P00 VARCHAR2(1) DEFAULT 'N';

ALTER TABLE T291_PARMESSAGGI ADD TIPO_FILTRO VARCHAR2(1) DEFAULT '0';

ALTER TABLE T025_CONTMENSILI ADD RICALCOLO_MAX_SCOSTNEG NUMBER(2);