ALTER TABLE T020_ORARI ADD ARRSCOSTR_COMP VARCHAR2(1) DEFAULT 'S';

ALTER TABLE T025_CONTMENSILI ADD SALDO_NEGATIVO_MINIMO VARCHAR2(7);

ALTER TABLE T070_SCHEDARIEPIL ADD ORECOMP_RECUPERATE VARCHAR2(6);

ALTER TABLE T825_LIQUIDINDANNUO ADD RESIDUABILE VARCHAR2(7);

ALTER TABLE T820_LIMITIIND ADD LIQUIDABILE_TEORICO VARCHAR2(7);
ALTER TABLE T820_LIMITIIND ADD RESIDUABILE_TEORICO VARCHAR2(7);

ALTER TABLE T134_ORELIQUIDATEANNIPREC MODIFY VARIAZIONE_ORE VARCHAR2(8);

UPDATE T275_CAUPRESENZE SET STACCO_MINIMO_SCOST = NULL;
ALTER TABLE T275_CAUPRESENZE MODIFY STACCO_MINIMO_SCOST VARCHAR2(1) DEFAULT 'N';
UPDATE T275_CAUPRESENZE SET STACCO_MINIMO_SCOST = 'N';

create package SELECT_APERTE is
  type t_badgeliberi is ref cursor;
  procedure GET_BADGE_USATI(C_BADGE IN OUT T_BADGELIBERI, DAL IN DATE, AL IN DATE);
  procedure B014Personalizzata(p in integer, dal in date, dato in varchar2, valore in varchar2, struttura in varchar2, sequenza in varchar2, rowid_riga in varchar2);
end SELECT_APERTE;
/

create package body SELECT_APERTE is
  procedure GET_BADGE_USATI(C_BADGE IN OUT T_BADGELIBERI, DAL IN DATE, AL IN DATE) is
  begin
    OPEN C_BADGE FOR 
      SELECT DISTINCT BADGE FROM T430_STORICO WHERE DATADECORRENZA <= AL AND DATAFINE >= DAL;
  end;

  procedure B014Personalizzata(p in integer, dal in date, dato in varchar2, valore in varchar2, struttura in varchar2, sequenza in varchar2, rowid_riga in varchar2) is
  begin
    null;
  end;
end SELECT_APERTE;
/
