UPDATE MONDOEDP.I090_ENTI SET VERSIONEDB = '5.5.5' WHERE AZIENDA = :AZIENDA;

ALTER TABLE T292_PARMESSAGGIDATI ADD CHIAVE VARCHAR2(1) DEFAULT 'N';

CREATE TABLE T299_MESSAGGIRICHIESTI
(PROGRESSIVO NUMBER(8),
 DATA DATE,
 PARAMETRIZZAZIONE VARCHAR2(5)
) 
TABLESPACE LAVORO PCTFREE 5 PCTUSED 80 STORAGE (PCTINCREASE 0 INITIAL 16K NEXT 256K);

ALTER TABLE T299_MESSAGGIRICHIESTI ADD CONSTRAINT T299_PK PRIMARY KEY (PROGRESSIVO,DATA,PARAMETRIZZAZIONE)
USING INDEX TABLESPACE INDICI STORAGE (PCTINCREASE 0 INITIAL 16K NEXT 256K);

ALTER TABLE T291_PARMESSAGGI ADD NUM_MMIND_VALID NUMBER(3);

ALTER TABLE T025_CONTMENSILI ADD BANCA_ORE_LIMITATA_SALDO_COMP VARCHAR2(1) DEFAULT 'N';
COMMENT ON COLUMN T025_CONTMENSILI.BANCA_ORE_LIMITATA_SALDO_COMP IS
  'Le ore mensili attribuibili alla banca ore non possono superare il saldo complessivo';
ALTER TABLE T025_CONTMENSILI ADD BANCA_ORE_LIMITATA_STR_LIQ VARCHAR2(1) DEFAULT 'N';
COMMENT ON COLUMN T025_CONTMENSILI.BANCA_ORE_LIMITATA_STR_LIQ IS
  'Le ore mensili attribuibili alla banca ore non possono superare il limite dello straordinario liquidabile annuale, considerando anche le ore già liquidate';

ALTER TABLE T020_ORARI ADD STRRIPFASCE VARCHAR2(1) DEFAULT 'S' NOT NULL;
COMMENT ON COLUMN T020_ORARI.STRRIPFASCE IS
  'Indica se le ore di straordinario vengono ripartite nelle fasce di maggiorazione o se vengono considerate tutte nella fascia piu'' bassa';

ALTER TABLE T262_PROFASSANN ADD ARR_COMPETENZA_IN_ORE VARCHAR2(5);
COMMENT ON COLUMN T262_PROFASSANN.ARR_COMPETENZA_IN_ORE  IS
  'Arrotondamento espresso in hh.mm da applicare alle competenze';
ALTER TABLE T262_PROFASSANN ADD MAX_FRUIZIONE_GIORN_IN_ORE VARCHAR2(5);
COMMENT ON COLUMN T262_PROFASSANN.MAX_FRUIZIONE_GIORN_IN_ORE  IS
  'Massima quantita'' in ore e minuti fruibile nella singola giornata';

ALTER TABLE T265_CAUASSENZE MODIFY UM_INSERIMENTO DEFAULT 'S';
COMMENT ON COLUMN T265_CAUASSENZE.UM_INSERIMENTO  IS
  'Indica se la causale di assenza puo'' essere inserita a giornate intere. Valori ammessi (S/N).';
ALTER TABLE T265_CAUASSENZE ADD UM_INSERIMENTO_MG VARCHAR2(1) DEFAULT 'S';
COMMENT ON COLUMN T265_CAUASSENZE.UM_INSERIMENTO_MG  IS
  'Indica se la causale di assenza puo'' essere inserita a mezze giornate. Valori ammessi (S/N).';
ALTER TABLE T265_CAUASSENZE ADD UM_INSERIMENTO_H VARCHAR2(1) DEFAULT 'S';
COMMENT ON COLUMN T265_CAUASSENZE.UM_INSERIMENTO_H  IS
  'Indica se la causale di assenza puo'' essere inserita ad ore. Valori ammessi (S/N).';

UPDATE T265_CAUASSENZE SET UM_INSERIMENTO_MG = 'N' WHERE UM_INSERIMENTO = 'O';
UPDATE T265_CAUASSENZE SET UM_INSERIMENTO_H = 'N' WHERE UM_INSERIMENTO = 'G';
UPDATE T265_CAUASSENZE SET UM_INSERIMENTO = DECODE(UM_INSERIMENTO,'E','S','G','S','N');

ALTER TABLE T041_PROVVISORIO ADD FLAGAGG VARCHAR2(1) DEFAULT 'N' NOT NULL;
alter table T041_PROVVISORIO drop primary key;
alter table T041_PROVVISORIO
  add constraint T041_PK primary key (PROGRESSIVO,DATA,CAUSALE,FLAGAGG)
  using index 
  tablespace INDICI
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 32K
    next 256K
    minextents 1
  );
ALTER TABLE T081_PROVVISORIO ADD FLAGAGG VARCHAR2(1) DEFAULT 'N' NOT NULL;
alter table T081_PROVVISORIO drop primary key;
alter table T081_PROVVISORIO
  add constraint T081_PK primary key (PROGRESSIVO,DATA,FLAGAGG)
  using index 
  tablespace INDICI
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 32K
    next 256K 
    minextents 1
  );
alter table I071_PERMESSI add A058_OPERATIVA varchar2(1) default 'S';
alter table I071_PERMESSI add A058_NONOPERATIVA varchar2(1) default 'S';
INSERT INTO MONDOEDP.I091_DATIENTE (SELECT AZIENDA,'C11_PIANIFORARIPROG', 'N' FROM I090_ENTI);

COMMENT ON COLUMN P430_ANAGRAFICO.TIPO_DIPENDENTE IS
  'Tipo dipendente: RU=A ruolo, IN=Incaricato, ER=Erede, BO=Borsista, CO=Co.Co.Co., LU=L.S.U., LA=Lav.autonomo';