CREATE OR REPLACE PROCEDURE DCEVO.EMK_SCARICO_TIMBRATURE(BADGEC IN NUMBER, DATAC IN DATE, ORAC IN DATE, SENSOC IN VARCHAR2, TERMINALEC IN NUMBER, CAUSALEC IN NUMBER, INSERIMENTO IN OUT VARCHAR2) AS
  CAUSALEC1 VARCHAR2(3);
  P NUMBER;
  SECONDI NUMBER;
  NT NUMBER;
  TR VARCHAR2(1);
  CM VARCHAR2(5);
BEGIN
  INSERIMENTO:='S';
  IF CAUSALEC = 0 THEN
    CAUSALEC1:=NULL;
  ELSE
    CAUSALEC1:=LPAD(TO_CHAR(CAUSALEC),3,'0');
  END IF;
  SELECT PROGRESSIVO INTO P FROM MEDPT430_STORICO WHERE
    BADGEC = BADGE AND
    DATAC BETWEEN DATADECORRENZA AND DATAFINE AND
    INIZIO<=DATAC AND (FINE IS NULL OR FINE>=DATAC) AND
    ROWNUM = 1;
    BEGIN
      BEGIN
        /*Modif. da Annalisa il 30/03/2010 per gestire ultime 2 cifre dei terminali e non prime 2*/
        /*SELECT FUNZIONE,CAUSMENSA INTO TR,CM FROM MEDPT361_OROLOGI WHERE CODICE = LPAD(TO_CHAR(TERMINALEC),2,'0');*/
        SELECT FUNZIONE,CAUSMENSA INTO TR,CM FROM MEDPT361_OROLOGI WHERE CODICE = SUBSTR(LPAD(TO_CHAR(TERMINALEC),3,'0'),2,2);
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          TR:='P';
      END;
      IF TR = 'E' AND (CM IS NOT NULL) THEN
        IF CM = CAUSALEC THEN
          TR:='M';
        ELSE
          TR:='P';
        END IF;
      END IF;
      IF TR IN ('M','E') THEN
        /*Timbrature mensa*/
        SECONDI:=0;
        WHILE SECONDI <= 59 LOOP
          BEGIN
            /*Modif. da Annalisa il 30/03/2010 per gestire ultime 2 cifre dei terminali e non prime 2*/
           /*INSERT INTO MEDPT370_TIMBMENSA
               (PROGRESSIVO,DATA,ORA,VERSO,RILEVATORE,FLAG)
            VALUES
               (P,DATAC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI')||LPAD(TO_CHAR(SECONDI),2,'0'),'DDMMYYYYHH24MISS'),
                SENSOC,LPAD(TO_CHAR(TERMINALEC),2,'0'),'O');*/
            INSERT INTO MEDPT370_TIMBMENSA
               (PROGRESSIVO,DATA,ORA,VERSO,RILEVATORE,FLAG)
            VALUES
               (P,DATAC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI')||LPAD(TO_CHAR(SECONDI),2,'0'),'DDMMYYYYHH24MISS'),
                SENSOC,SUBSTR(LPAD(TO_CHAR(TERMINALEC),3,'0'),2,2),'O');
            EXIT;
          EXCEPTION
            WHEN OTHERS THEN
              SECONDI:=SECONDI + 1;
          END;
        END LOOP;
      END IF;
      IF TR IN ('P','E') THEN
        /*Timbrature presenza*/
        SECONDI:=0;
        IF SENSOC = 'E' THEN
          SELECT COUNT(*) INTO NT FROM MEDPT100_TIMBRATURE WHERE 
            PROGRESSIVO = P AND 
            DATA = DATAC AND 
            ORA = TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI'),'DDMMYYYYHH24MI') AND
            VERSO = 'U';
           IF NT > 0 THEN
             SECONDI:=1;
           END IF;
        END IF;  
        /*Modif. da Annalisa il 30/03/2010 per gestire ultime 2 cifre dei terminali e non prime 2*/
        /*INSERT INTO MEDPT100_TIMBRATURE
          (PROGRESSIVO,DATA,ORA,VERSO,CAUSALE,RILEVATORE,FLAG)
        VALUES          
          --(P,DATAC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI'),'DDMMYYYYHH24MI'),
          (P,DATAC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI')||LPAD(TO_CHAR(SECONDI),2,'0'),'DDMMYYYYHH24MISS'),
           SENSOC,CAUSALEC1,LPAD(TO_CHAR(TERMINALEC),2,'0'),'O');*/
        INSERT INTO MEDPT100_TIMBRATURE
          (PROGRESSIVO,DATA,ORA,VERSO,CAUSALE,RILEVATORE,FLAG)
        VALUES          
          --(P,DATAC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI'),'DDMMYYYYHH24MI'),
          (P,DATAC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI')||LPAD(TO_CHAR(SECONDI),2,'0'),'DDMMYYYYHH24MISS'),
           SENSOC,CAUSALEC1,SUBSTR(LPAD(TO_CHAR(TERMINALEC),3,'0'),2,2),'O');
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
    /*Modif. da Annalisa il 30/03/2010 per gestire ultime 2 cifre dei terminali e non prime 2*/
  /*EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO MEDPI101_TIMBIRREGOLARI
          (DATA,BADGE,ORA,VERSO,RILEV,CAUSALE)
        VALUES
          (DATAC,BADGEC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI'),'DDMMYYYYHH24MI'),SENSOC,
           LPAD(TO_CHAR(TERMINALEC),2,'0'),CAUSALEC1);*/
  EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO MEDPI101_TIMBIRREGOLARI
          (DATA,BADGE,ORA,VERSO,RILEV,CAUSALE)
        VALUES
          (DATAC,BADGEC,TO_DATE('01011900'||TO_CHAR(ORAC,'HH24MI'),'DDMMYYYYHH24MI'),SENSOC,
           SUBSTR(LPAD(TO_CHAR(TERMINALEC),3,'0'),2,2),CAUSALEC1);
END;